const fs = require('fs');
const base = 'C:/Users/Os/.gemini/antigravity/scratch/InmuFacil_Project/frontend/assets/translations/';

function setVal(obj, path, val) {
  const parts = path.split('.');
  const last = parts.pop();
  const target = parts.reduce((o, k) => { if (!o[k]) o[k] = {}; return o[k]; }, obj);
  target[last] = val;
}

const translations = {
  'solvency.step_disclaimer': { 'en-US':'Disclaimer','fr-FR':'Avertissement','ca-ES':'Responsabilitat','eu-ES':'Ardura','gl-ES':'Responsabilidade' },
  'solvency.step_declaration': { 'en-US':'Declaration','fr-FR':'Déclaration','ca-ES':'Declaració','eu-ES':'Aitorpena','gl-ES':'Declaración' },
  'solvency.debt_ratio_warning': { 'en-US':'A ratio above 35% is usually grounds for rejection by most banks.','fr-FR':'Un ratio supérieur à 35 % est généralement un motif de refus pour la plupart des banques.','ca-ES':'Un ràtio superior al 35% sol ser motiu de rebuig per la majoria de bancs.','eu-ES':'%35 baino handiagoko ratioa, bankuek ezesteko arrazoia izaten da.','gl-ES':'Un ratio superior ao 35% adoita ser motivo de rexeitamento pola maioría dos bancos.' },
  'solvency.no': { 'en-US':'No','fr-FR':'Non','ca-ES':'No','eu-ES':'Ez','gl-ES':'Non' },
  'solvency.declaration_title': { 'en-US':'Solvency Declaration','fr-FR':'Déclaration de Solvabilité','ca-ES':'Declaració de Solvència','eu-ES':'Kaudimenaren Aitorpena','gl-ES':'Declaración de Solvencia' },
  'solvency.declaration_subtitle': { 'en-US':'Your current financing status','fr-FR':'État actuel de votre financement','ca-ES':'Estat actual del teu finançament','eu-ES':'Zure finantzaketa-egoera oraingoa','gl-ES':'Estado actual do teu financiamento' },
  'solvency.preapproval_hint': { 'en-US':'A pre-approval document from your bank gives the seller great confidence.','fr-FR':'Un document de préapprobation de votre banque rassure beaucoup le vendeur.','ca-ES':'Un document de preaprovació del teu banc dona molta confiança al venedor.','eu-ES':'Zure bankuaren aldeko dokumentuak konfiantza handia ematen dio saltzaileari.','gl-ES':'Un documento de preaprobación do teu banco dá moita confianza ao vendedor.' },
  'solvency.debt_label_solo': { 'en-US':'Current monthly debts','fr-FR':'Dettes mensuelles actuelles','ca-ES':'Deutes mensuals actuals','eu-ES':'Uneko hileko zorrak','gl-ES':'Débedas mensuais actuais' },
  'solvency.debt_label_joint': { 'en-US':'Current monthly debts (total buyers)','fr-FR':'Dettes mensuelles actuelles (total acheteurs)','ca-ES':'Deutes mensuals actuals (total compradors)','eu-ES':'Uneko hileko zorrak (erosleak guztira)','gl-ES':'Débedas mensuais actuais (total compradores)' },
  'solvency.debt_hint': { 'en-US':'e.g. 300 (loans, credit cards...)','fr-FR':'ex. 300 (crédits, cartes...)','ca-ES':'ex. 300 (préstecs, targetes...)','eu-ES':'adib. 300 (maileguak, txartelak...)','gl-ES':'ex. 300 (préstamos, tarxetas...)' },
  'solvency.dna_skip_hint': { 'en-US':'If you prefer not to fill in these fields now, you can do so later by updating your passport.','fr-FR':'Si vous préférez ne pas remplir ces champs maintenant, vous pourrez le faire plus tard en mettant à jour votre passeport.','ca-ES':'Si prefereixes no omplir aquests camps ara, pots fer-ho més endavant actualitzant el teu passaport.','eu-ES':'Eremu hauek orain bete nahi ez badituzu, geroago egin dezakezu zure pasaportea eguneratuz.','gl-ES':'Se prefires non cubrir estes campos agora, podes facelo máis adiante actualizando o teu pasaporte.' },
  'solvency.level_estimate': { 'en-US':'Estimate: ','fr-FR':'Estimation : ','ca-ES':'Estimació: ','eu-ES':'Estimazioa: ','gl-ES':'Estimación: ' },
  'solvency.level_label': { 'en-US':'Level: ','fr-FR':'Niveau : ','ca-ES':'Nivell: ','eu-ES':'Maila: ','gl-ES':'Nivel: ' },
  'solvency.level_gold': { 'en-US':'GOLD','fr-FR':'OR','ca-ES':'OR','eu-ES':'URRE','gl-ES':'OURO' },
  'solvency.level_silver': { 'en-US':'SILVER','fr-FR':'ARGENT','ca-ES':'PLATA','eu-ES':'ZILAR','gl-ES':'PRATA' },
  'solvency.level_bronze': { 'en-US':'BRONZE','fr-FR':'BRONZE','ca-ES':'BRONZE','eu-ES':'BRONTZE','gl-ES':'BRONCE' },
  'solvency.level_gold_desc': { 'en-US':'Solid financial profile. Stands out among other buyers.','fr-FR':'Profil financier solide. Se démarque des autres acheteurs.','ca-ES':'Perfil financer sòlid. Destaca davant d\'altres compradors.','eu-ES':'Profil finantzario sendo bat. Beste erosle batzuen gainetik nabarmentzen da.','gl-ES':'Perfil financeiro sólido. Destaca fronte a outros compradores.' },
  'solvency.level_silver_desc': { 'en-US':'Good profile. You can improve with mortgage pre-approval or reduced debt.','fr-FR':'Bon profil. Vous pouvez l\'améliorer avec une préapprobation hypothécaire ou en réduisant votre endettement.','ca-ES':'Bon perfil. Pots millorar amb preaprovació hipotecària o reduint l\'endeutament.','eu-ES':'Profil ona. Hipotekaren aurre-onespenarekin edo zor txikiagorekin hobetu dezakezu.','gl-ES':'Bo perfil. Podes mellorar coa preaprobación hipotecaria ou reducindo o endebedamento.' },
  'solvency.level_bronze_desc': { 'en-US':'Basic profile. Completing your Financial DNA can improve your score.','fr-FR':'Profil de base. Compléter votre ADN Financier peut améliorer votre score.','ca-ES':'Perfil bàsic. Completar el teu ADN Financer pot millorar la teva puntuació.','eu-ES':'Oinarrizko profila. ADN Finantzarioa osatzeak zure puntuazioa hobetu dezake.','gl-ES':'Perfil básico. Completar o ADN Financeiro pode mellorar a túa puntuación.' },
  'solvency.loading_error': { 'en-US':'Error loading your passport: {error}','fr-FR':'Erreur lors du chargement de votre passeport : {error}','ca-ES':'Error en carregar el teu passaport: {error}','eu-ES':'Zure pasaportea kargatzean errorea: {error}','gl-ES':'Erro ao cargar o teu pasaporte: {error}' },
  'solvency.retry': { 'en-US':'Retry','fr-FR':'Réessayer','ca-ES':'Reintentar','eu-ES':'Saiatu berriro','gl-ES':'Reintentar' },
  'solvency.no_passport_title': { 'en-US':'Solvency Passport','fr-FR':'Passeport de Solvabilité','ca-ES':'Passaport de Solvència','eu-ES':'Kaudimenaren Pasaportea','gl-ES':'Pasaporte de Solvencia' },
  'solvency.no_passport_desc': { 'en-US':'Complete the wizard to generate your passport. This will help sellers accept your visits and offers.','fr-FR':'Complétez l\'assistant pour générer votre passeport. Cela facilitera l\'acceptation de vos visites et offres par les vendeurs.','ca-ES':'Completa l\'assistent per generar el teu passaport. Això facilitarà que els venedors acceptin les teves visites i ofertes.','eu-ES':'Osatu laguntzailea zure pasaportea sortzeko. Honek saltzaileek zure bisitak eta eskaintzak onartzea erraztuko du.','gl-ES':'Completa o asistente para xerar o teu pasaporte. Isto facilitará que os vendedores acepten as túas visitas e ofertas.' },
  'solvency.complete_wizard': { 'en-US':'Complete Wizard','fr-FR':'Compléter l\'Assistant','ca-ES':'Completar l\'Assistent','eu-ES':'Osatu Laguntzailea','gl-ES':'Completar Asistente' },
  'solvency.passport_title': { 'en-US':'SOLVENCY PASSPORT','fr-FR':'PASSEPORT DE SOLVABILITÉ','ca-ES':'PASSAPORT DE SOLVÈNCIA','eu-ES':'KAUDIMENAREN PASAPORTEA','gl-ES':'PASAPORTE DE SOLVENCIA' },
  'solvency.expires_on': { 'en-US':'Expires on ','fr-FR':'Expire le ','ca-ES':'Expira el ','eu-ES':'Iraungitzen da ','gl-ES':'Expira o ' },
  'solvency.days': { 'en-US':' days','fr-FR':' jours','ca-ES':' dies','eu-ES':' egun','gl-ES':' días' },
  'solvency.no_expiry': { 'en-US':'No expiry','fr-FR':'Sans expiration','ca-ES':'Sense expiració','eu-ES':'Iraungipen gabe','gl-ES':'Sen expiración' },
  'solvency.valid_status': { 'en-US':'VALID','fr-FR':'VALIDE','ca-ES':'VÀLID','eu-ES':'BALIOZKOA','gl-ES':'VÁLIDO' },
  'solvency.expiring_soon': { 'en-US':'EXPIRING SOON','fr-FR':'EXPIRE BIENTÔT','ca-ES':'EXPIRA AVIAT','eu-ES':'LASTER IRAUNGITZEN','gl-ES':'EXPIRA PRONTO' },
  'solvency.stress_index': { 'en-US':'Financial Stress Index','fr-FR':'Indice de Stress Financier','ca-ES':'Índex d\'Estrès Financer','eu-ES':'Finantza-Estres Indizea','gl-ES':'Índice de Estrés Financeiro' },
  'solvency.debt_ratio': { 'en-US':'Debt ratio: ','fr-FR':'Ratio d\'endettement : ','ca-ES':'Ràtio d\'endeutament: ','eu-ES':'Zor-ratioa: ','gl-ES':'Ratio de endebedamento: ' },
  'solvency.statement_summary': { 'en-US':'Declaration Summary','fr-FR':'Résumé des Déclarations','ca-ES':'Resum de Declaracions','eu-ES':'Aitorpenen Laburpena','gl-ES':'Resumo de Declaracións' },
  'solvency.knows_extra_costs': { 'en-US':'Aware of extra costs (10-12%)','fr-FR':'Connait les frais supplémentaires (10-12%)','ca-ES':'Coneix les despeses extra (10-12%)','eu-ES':'Gastu gehigarriak ezagutzen ditu (%10-12)','gl-ES':'Coñece os gastos extra (10-12%)' },
  'solvency.has_emergency_fund': { 'en-US':'Has an emergency fund','fr-FR':'Dispose d\'un fonds d\'urgence','ca-ES':'Disposa de fons d\'emergència','eu-ES':'Larrialdirako funtsa du','gl-ES':'Dispón de fondo de emerxencia' },
  'solvency.has_initial_savings': { 'en-US':'Has savings for the down payment (20%)','fr-FR':'Dispose d\'une épargne pour l\'apport (20%)','ca-ES':'Té estalvis per a l\'entrada (20%)','eu-ES':'Sarrerarako aurrezkiak ditu (%20)','gl-ES':'Ten aforros para a entrada (20%)' },
  'solvency.has_preapproval': { 'en-US':'Has bank pre-approval','fr-FR':'Dispose d\'une préapprobation bancaire','ca-ES':'Té preaprovació bancària','eu-ES':'Bankuaren aurre-onespena du','gl-ES':'Ten preaprobación bancaria' },
  'solvency.payment_method': { 'en-US':'Payment method: ','fr-FR':'Mode de paiement : ','ca-ES':'Mètode de pagament: ','eu-ES':'Ordainketa-metodoa: ','gl-ES':'Método de pago: ' },
  'solvency.refresh': { 'en-US':'Refresh Data','fr-FR':'Actualiser les Données','ca-ES':'Actualitzar Dades','eu-ES':'Eguneratu Datuak','gl-ES':'Actualizar Datos' },
  'solvency.go_to_profile': { 'en-US':'Go to my profile','fr-FR':'Aller à mon profil','ca-ES':'Anar al meu perfil','eu-ES':'Joan nire profilera','gl-ES':'Ir ao meu perfil' },
  'solvency.passport_visibility_info': { 'en-US':'This passport is visible to sellers when you request a visit or send an offer.','fr-FR':'Ce passeport est visible par les vendeurs lorsque vous demandez une visite ou envoyez une offre.','ca-ES':'Aquest passaport és visible pels venedors quan sol·licites una visita o envies una oferta.','eu-ES':'Pasaporte hau saltzaileei ikusgai dago bisita eskatzean edo eskaintza bidaltzean.','gl-ES':'Este pasaporte é visible para os vendedores cando solicitas unha visita ou envías unha oferta.' },
  'solvency.gold': { 'en-US':'GOLD','fr-FR':'OR','ca-ES':'OR','eu-ES':'URRE','gl-ES':'OURO' },
  'solvency.silver': { 'en-US':'SILVER','fr-FR':'ARGENT','ca-ES':'PLATA','eu-ES':'ZILAR','gl-ES':'PRATA' },
  'solvency.bronze': { 'en-US':'BRONZE','fr-FR':'BRONZE','ca-ES':'BRONZE','eu-ES':'BRONTZE','gl-ES':'BRONCE' },
  'solvency.low_risk': { 'en-US':'Low Risk','fr-FR':'Risque Faible','ca-ES':'Risc Baix','eu-ES':'Arrisku Baxua','gl-ES':'Risco Baixo' },
  'solvency.medium_risk': { 'en-US':'Medium Risk','fr-FR':'Risque Moyen','ca-ES':'Risc Mitjà','eu-ES':'Arrisku Ertaina','gl-ES':'Risco Medio' },
  'solvency.high_risk': { 'en-US':'High Risk','fr-FR':'Risque Élevé','ca-ES':'Risc Alt','eu-ES':'Arrisku Altua','gl-ES':'Risco Alto' },
  'solvency.unknown_risk': { 'en-US':'Unknown','fr-FR':'Inconnu','ca-ES':'Desconegut','eu-ES':'Ezezaguna','gl-ES':'Descoñecido' },
  'solvency.cash': { 'en-US':'Cash','fr-FR':'Comptant','ca-ES':'Al comptat','eu-ES':'Eskudirutan','gl-ES':'Ao contado' },
  'solvency.mortgage_approved': { 'en-US':'Mortgage already approved','fr-FR':'Hypothèque déjà approuvée','ca-ES':'Hipoteca ja aprovada','eu-ES':'Hipoteka dagoeneko onartuta','gl-ES':'Hipoteca xa aprobada' },
  'solvency.mortgage_pending': { 'en-US':'Mortgage in progress','fr-FR':'Hypothèque en cours','ca-ES':'Hipoteca en tràmit','eu-ES':'Hipoteka tramitazioan','gl-ES':'Hipoteca en trámite' },
  'solvency.house_to_sell': { 'en-US':'Pending sale of another property','fr-FR':'En attente de vente d\'un autre bien','ca-ES':'Pendent de vendre un altre habitatge','eu-ES':'Beste etxe bat saltzeko zain','gl-ES':'Pendente de vender outra casa' },
  'solvency.savings_plus_mortgage': { 'en-US':'Savings + Mortgage','fr-FR':'Épargne + Hypothèque','ca-ES':'Estalvis + Hipoteca','eu-ES':'Aurrezkiak + Hipoteka','gl-ES':'Aforros + Hipoteca' },
  'solvency.bridge_mortgage': { 'en-US':'Bridge mortgage','fr-FR':'Prêt relais','ca-ES':'Hipoteca pont','eu-ES':'Zubi-hipoteka','gl-ES':'Hipoteca ponte' },
  'solvency.unspecified_payment': { 'en-US':'Not specified','fr-FR':'Non spécifié','ca-ES':'No especificat','eu-ES':'Zehaztu gabe','gl-ES':'Non especificado' },
  'solvency.save_error': { 'en-US':'Error saving: {error}','fr-FR':'Erreur lors de la sauvegarde : {error}','ca-ES':'Error en desar: {error}','eu-ES':'Gordetzean errorea: {error}','gl-ES':'Erro ao gardar: {error}' },
  'solvency.step_buyer_type': { 'en-US':'Purchase Type','fr-FR':'Type d\'Achat','ca-ES':'Tipus de Compra','eu-ES':'Erosketa Mota','gl-ES':'Tipo de Compra' },
  'solvency.step_financial_awareness': { 'en-US':'Financial Awareness','fr-FR':'Conscience Financière','ca-ES':'Consciència Financera','eu-ES':'Finantza-Kontzientzia','gl-ES':'Conciencia Financeira' },
  'solvency.step_financial_dna': { 'en-US':'Financial DNA','fr-FR':'ADN Financier','ca-ES':'ADN Financer','eu-ES':'ADN Finantzarioa','gl-ES':'ADN Financeiro' },
  'solvency.get_passport_btn': { 'en-US':'Generate Passport','fr-FR':'Générer le Passeport','ca-ES':'Generar Passaport','eu-ES':'Sortu Pasaportea','gl-ES':'Xerar Pasaporte' },
  'solvency.buyer_type_title': { 'en-US':'How will you buy?','fr-FR':'Comment allez-vous acheter ?','ca-ES':'Com vas a comprar?','eu-ES':'Nola erosiko duzu?','gl-ES':'Como vas a comprar?' },
  'solvency.buyer_type_desc': { 'en-US':'Indicate whether you are buying alone or with someone else so the analysis can be accurate.','fr-FR':'Indiquez si vous achetez seul ou avec quelqu\'un d\'autre pour que l\'analyse soit précise.','ca-ES':'Indica si la compra la fas tu sol o amb una altra persona perquè l\'anàlisi sigui precisa.','eu-ES':'Adierazi bakarrik edo beste batekin erosten duzun, analisia zehatza izan dadin.','gl-ES':'Indica se a compra a realizas ti só ou cunha outra persoa para que a análise sexa precisa.' },
  'solvency.just_me': { 'en-US':'Just me','fr-FR':'Juste moi','ca-ES':'Només jo','eu-ES':'Ni bakarrik','gl-ES':'Só eu' },
  'solvency.individual_purchase': { 'en-US':'Individual purchase','fr-FR':'Achat individuel','ca-ES':'Compra individual','eu-ES':'Erosketa banakoa','gl-ES':'Compra individual' },
  'solvency.with_someone_else': { 'en-US':'With someone else','fr-FR':'Avec quelqu\'un d\'autre','ca-ES':'Amb algú més','eu-ES':'Beste norbait batekin','gl-ES':'Con alguén máis' },
  'solvency.joint_purchase': { 'en-US':'Joint purchase (couple, partner...)','fr-FR':'Achat conjoint (couple, associé...)','ca-ES':'Compra conjunta (parella, soci...)','eu-ES':'Erosketa bateratua (bikotea, bazkidea...)','gl-ES':'Compra conxunta (parella, socio...)' },
  'solvency.joint_purchase_info': { 'en-US':'In a joint purchase, income and savings data must be the total for all buyers.','fr-FR':'Dans un achat conjoint, les données de revenus et d\'épargne doivent être le total de tous les acheteurs.','ca-ES':'En una compra conjunta, les dades d\'ingressos i estalvis han de ser el total de tots els participants.','eu-ES':'Erosketa bateratuan, diru-sarreren eta aurrezpenen datuak parte-hartzaile guztien batura izan behar da.','gl-ES':'Nunha compra conxunta, os datos de ingresos e aforros deben ser o total de todos os participantes.' },
  'solvency.liability_notice_title': { 'en-US':'Liability Notice','fr-FR':'Avis de Responsabilité','ca-ES':'Avís de Responsabilitat','eu-ES':'Erantzukizun-Oharra','gl-ES':'Aviso de Responsabilidade' },
  'solvency.read_carefully': { 'en-US':'Please read carefully','fr-FR':'Veuillez lire attentivement','ca-ES':'Si us plau, llegeix amb atenció','eu-ES':'Mesedez, irakurri arretaz','gl-ES':'Por favor, le con atención' },
  'solvency.accept_terms': { 'en-US':'I understand and accept that the information provided must be truthful.','fr-FR':'Je comprends et j\'accepte que les informations fournies doivent être réelles.','ca-ES':'Entenc i accepto que la informació facilitada ha de ser real.','eu-ES':'Ulertzen eta onartzen dut emandako informazioa benetakoa izan behar dela.','gl-ES':'Entendo e acepto que a información facilitada debe ser real.' },
  'solvency.financial_awareness_subtitle': { 'en-US':'Risk analysis and knowledge','fr-FR':'Analyse des risques et connaissances','ca-ES':'Anàlisi de riscos i coneixements','eu-ES':'Arrisku-analisia eta ezagutzak','gl-ES':'Análise de riscos e coñecementos' },
  'solvency.knows_extra_costs_multi': { 'en-US':'Do you all know about the additional purchase costs?','fr-FR':'Connaissez-vous les frais supplémentaires liés à l\'achat ?','ca-ES':'Coneixeu les despeses addicionals de la compravenda?','eu-ES':'Ezagutzen al dituzue erosketa-salmenten gastu gehigarriak?','gl-ES':'Coñecedes os gastos adicionais da compravenda?' },
  'solvency.knows_extra_costs_single': { 'en-US':'Do you know about the additional purchase costs?','fr-FR':'Connaissez-vous les frais supplémentaires liés à l\'achat ?','ca-ES':'Coneixes les despeses addicionals de la compravenda?','eu-ES':'Ezagutzen al dituzu erosketa-salmenten gastu gehigarriak?','gl-ES':'Coñeces os gastos adicionais da compravenda?' },
  'solvency.extra_costs_hint': { 'en-US':'Taxes (ITP/VAT), Notary, Registry and Management fees typically add 10-12% to the price.','fr-FR':'Les impôts (ITP/TVA), frais de notaire, d\'enregistrement et de gestion ajoutent généralement 10-12% au prix.','ca-ES':'Impostos (ITP/IVA), Notaria, Registre i Gestoria solen sumar un 10-12% addicional al preu.','eu-ES':'Zergak (ITP/BEZ), Notaria, Erregistroa eta Gestoria, oro har, %10-12 gehitzen dute prezioari.','gl-ES':'Impostos (ITP/IVE), Notaría, Rexistro e Xestoría adoitan sumar un 10-12% adicional ao prezo.' },
  'solvency.monthly_debt_ratio': { 'en-US':'Estimated monthly debt ratio','fr-FR':'Ratio d\'endettement mensuel estimé','ca-ES':'Ràtio d\'endeutament mensual estimat','eu-ES':'Hileko zor-ratio estimatua','gl-ES':'Ratio de endebedamento mensual estimado' },
  'solvency.debt_ratio_formula': { 'en-US':'(Mortgage payment + other loans) / Net income','fr-FR':'(Mensualité hypothèque + autres crédits) / Revenus nets','ca-ES':'(Quota hipoteca + altres préstecs) / Ingressos nets','eu-ES':'(Hipoteka-kuota + beste maileguak) / Sarrera garbiak','gl-ES':'(Cota hipoteca + outros préstamos) / Ingresos netos' },
  'solvency.has_emergency_fund_multi': { 'en-US':'Do you all have an emergency fund after the purchase?','fr-FR':'Disposez-vous d\'un fonds d\'urgence après l\'achat ?','ca-ES':'Disposeu d\'un fons d\'emergència després de la compra?','eu-ES':'Baduzue larrialdirako funts bat erosketa ondoren?','gl-ES':'Dispoñedes dun fondo de emerxencia tras a compra?' },
  'solvency.has_emergency_fund_single': { 'en-US':'Do you have an emergency fund after the purchase?','fr-FR':'Disposez-vous d\'un fonds d\'urgence après l\'achat ?','ca-ES':'Disposes d\'un fons d\'emergència després de la compra?','eu-ES':'Badaukazu larrialdirako funts bat erosketa ondoren?','gl-ES':'Dispós dun fondo de emerxencia tras a compra?' },
  'solvency.emergency_fund_hint': { 'en-US':'It is recommended to have savings equivalent to 6 months of expenses after paying the down payment.','fr-FR':'Il est recommandé d\'avoir épargné l\'équivalent de 6 mois de dépenses après le versement de l\'apport.','ca-ES':'Es recomana tenir estalviat l\'equivalent a 6 mesos de despeses després de pagar l\'entrada.','eu-ES':'Gomendatzen da sarrera ordaindu ondoren 6 hilabeteko gastuei baliokide den aurrezkia edukitzea.','gl-ES':'Recoméndase ter aforrado o equivalente a 6 meses de gastos tras pagar a entrada.' },
  'solvency.how_to_finance': { 'en-US':'How are you planning to finance the purchase?','fr-FR':'Comment envisagez-vous de financer l\'achat ?','ca-ES':'Com tens pensat finançar la compra?','eu-ES':'Nola planifikatzen duzu erosketa finantzatzea?','gl-ES':'Como tes pensado financiar a compra?' },
  'solvency.savings_only': { 'en-US':'Own savings only','fr-FR':'Uniquement épargne personnelle','ca-ES':'Només estalvis propis','eu-ES':'Neure aurrezkiak bakarrik','gl-ES':'Só aforros propios' },
  'solvency.no_process': { 'en-US':'No process started','fr-FR':'Aucune démarche entamée','ca-ES':'Sense iniciar tràmits','eu-ES':'Tramitazioa hasi gabe','gl-ES':'Sen iniciar trámites' },
  'solvency.has_initial_savings_multi': { 'en-US':'Do you all have 20% of the price saved (the down payment)?','fr-FR':'Avez-vous épargné 20 % du prix (l\'apport) ?','ca-ES':'Teniu estalviat el 20% del preu (l\'entrada)?','eu-ES':'Prezioaren %20 gordetuta duzue (sarrera)?','gl-ES':'Tendes aforrado o 20% do prezo (a entrada)?' },
  'solvency.has_initial_savings_single': { 'en-US':'Do you have 20% of the price saved (the down payment)?','fr-FR':'Avez-vous épargné 20 % du prix (l\'apport) ?','ca-ES':'Tens estalviat el 20% del preu (l\'entrada)?','eu-ES':'Prezioaren %20 gordetuta duzu (sarrera)?','gl-ES':'Tes aforrado o 20% do prezo (a entrada)?' },
  'solvency.initial_savings_hint': { 'en-US':'Most banks only finance up to 80% of the appraisal/purchase value.','fr-FR':'La plupart des banques ne financent que jusqu\'à 80 % de la valeur d\'expertise/d\'achat.','ca-ES':'La majoria de bancs només financen fins al 80% del valor de taxació/compra.','eu-ES':'Bankuek gehienetan tasazio/erosketa balioaren %80 arte bakarrik finantzatzen dute.','gl-ES':'A maioría dos bancos só financian ata o 80% do valor de taxación/compra.' },
  'solvency.has_preapproval_multi': { 'en-US':'Have you spoken with a bank and received pre-approval?','fr-FR':'Avez-vous parlé avec une banque et obtenu une préapprobation ?','ca-ES':'Heu parlat amb un banc i teniu preaprovació?','eu-ES':'Bankuarekin hitz egin duzue eta aurre-onespena duzue?','gl-ES':'Falastes cun banco e tendes preaprobación?' },
  'solvency.has_preapproval_single': { 'en-US':'Have you spoken with a bank and received pre-approval?','fr-FR':'Avez-vous parlé avec une banque et obtenu une préapprobation ?','ca-ES':'Has parlat amb un banc i tens preaprovació?','eu-ES':'Bankuarekin hitz egin duzu eta aurre-onespena duzu?','gl-ES':'Falaches cun banco e tes preaprobación?' },
  'solvency.financial_dna_subtitle': { 'en-US':'Quantitative data (Optional)','fr-FR':'Données quantitatives (Optionnel)','ca-ES':'Dades quantitatives (Opcional)','eu-ES':'Datu kuantitatiboak (Aukerakoa)','gl-ES':'Datos cuantitativos (Opcional)' },
  'solvency.data_privacy_info': { 'en-US':'This data is PRIVATE. It is only used to calculate your passport level (Gold, Silver, Bronze). The seller will NOT see the exact figures.','fr-FR':'Ces données sont PRIVÉES. Elles sont uniquement utilisées pour calculer votre niveau de passeport (Or, Argent, Bronze). Le vendeur ne verra PAS les chiffres exacts.','ca-ES':'Aquestes dades són PRIVADES. Només s\'utilitzen per calcular el teu nivell de passaport (Or, Plata, Bronze). El venedor NO veurà les xifres exactes.','eu-ES':'Datu hauek PRIBATUAK dira. Bakarrik pasaporte-maila kalkulatzeko erabiltzen dira (Urre, Zilar, Brontze). Saltzaileak ez ditu zifra zehatzak ikusiko.','gl-ES':'Estes datos son PRIVADOS. Só se utilizan para calcular o teu nivel de pasaporte (Ouro, Prata, Bronce). O vendedor NON verá as cifras exactas.' },
  'solvency.monthly_income_multi': { 'en-US':'Monthly Net Income (Total household)','fr-FR':'Revenus Nets Mensuels (Total du foyer)','ca-ES':'Ingressos Nets Mensuals (Total unitat)','eu-ES':'Hileko Sarrera Garbiak (Unitate osoa)','gl-ES':'Ingresos Netos Mensuais (Total unidade)' },
  'solvency.monthly_income_single': { 'en-US':'Your Monthly Net Income','fr-FR':'Vos Revenus Nets Mensuels','ca-ES':'Els teus Ingressos Nets Mensuals','eu-ES':'Zure Hileko Sarrera Garbiak','gl-ES':'Os teus Ingresos Netos Mensuais' },
  'solvency.example_income': { 'en-US':'E.g.: 2500','fr-FR':'Ex : 2500','ca-ES':'Ex: 2500','eu-ES':'Adib.: 2500','gl-ES':'Ex: 2500' },
  'solvency.total_savings_multi': { 'en-US':'Total Available Savings','fr-FR':'Épargne Totale Disponible','ca-ES':'Estalvis Totals Disponibles','eu-ES':'Eskuragarri dauden Aurrezki Guztiak','gl-ES':'Aforros Totais Dispoñibles' },
  'solvency.total_savings_single': { 'en-US':'Your Total Savings','fr-FR':'Votre Épargne Totale','ca-ES':'Els teus Estalvis Totals','eu-ES':'Zure Aurrezki Guztiak','gl-ES':'Os teus Aforros Totais' },
  'solvency.example_savings': { 'en-US':'E.g.: 45000','fr-FR':'Ex : 45000','ca-ES':'Ex: 45000','eu-ES':'Adib.: 45000','gl-ES':'Ex: 45000' },
  'solvency.monthly_debt_multi': { 'en-US':'Other monthly debts (Loans, etc.)','fr-FR':'Autres dettes mensuelles (Prêts, etc.)','ca-ES':'Altres deutes mensuals (Préstecs, etc.)','eu-ES':'Beste hileko zorrak (Maileguak, etab.)','gl-ES':'Outras débedas mensuais (Préstamos, etc.)' },
  'solvency.monthly_debt_single': { 'en-US':'Your monthly debts','fr-FR':'Vos dettes mensuelles','ca-ES':'Els teus deutes mensuals','eu-ES':'Zure hileko zorrak','gl-ES':'As túas débedas mensuais' },
  'solvency.example_debt': { 'en-US':'E.g.: 150','fr-FR':'Ex : 150','ca-ES':'Ex: 150','eu-ES':'Adib.: 150','gl-ES':'Ex: 150' },
  'solvency.optional_fields_hint': { 'en-US':'Filling in these fields allows us to assign you a Gold or Silver level, making you a much more attractive buyer.','fr-FR':'Remplir ces champs nous permet de vous attribuer un niveau Or ou Argent, ce qui vous rend beaucoup plus attractif pour les vendeurs.','ca-ES':'Omplir aquests camps ens permet assignar-te un nivell Or o Plata, la qual cosa et fa un comprador molt més atractiu.','eu-ES':'Eremu hauek betetzeak Or edo Zilar maila esleitzeko aukera ematen digu, erosle erakargarriagoa eginez.','gl-ES':'Cubrir estes campos permítenos asignarte un nivel Ouro ou Prata, o que te fai un comprador moito máis atractivo.' },
  'solvency.estimation_label': { 'en-US':'CURRENT ESTIMATE: ','fr-FR':'ESTIMATION ACTUELLE : ','ca-ES':'ESTIMACIÓ ACTUAL: ','eu-ES':'UNEKO ESTIMAZIOA: ','gl-ES':'ESTIMACIÓN ACTUAL: ' },
  'solvency.gold_desc': { 'en-US':'Solid financial profile. Stands out among other buyers.','fr-FR':'Profil financier solide. Se démarque des autres acheteurs.','ca-ES':'Perfil financer sòlid. Destaca davant d\'altres compradors.','eu-ES':'Profil finantzario sendo bat. Beste erosle batzuen gainetik nabarmentzen da.','gl-ES':'Perfil financeiro sólido. Destaca fronte a outros compradores.' },
  'solvency.silver_desc': { 'en-US':'Good profile. You can improve with mortgage pre-approval or reduced debt.','fr-FR':'Bon profil. Vous pouvez l\'améliorer avec une préapprobation hypothécaire ou en réduisant votre endettement.','ca-ES':'Bon perfil. Pots millorar amb preaprovació hipotecària o reduint l\'endeutament.','eu-ES':'Profil ona. Hipotekaren aurre-onespenarekin edo zor txikiagorekin hobetu dezakezu.','gl-ES':'Bo perfil. Podes mellorar coa preaprobación hipotecaria ou reducindo o endebedamento.' },
  'solvency.bronze_desc': { 'en-US':'Basic profile. Completing your Financial DNA can improve your score.','fr-FR':'Profil de base. Compléter votre ADN Financier peut améliorer votre score.','ca-ES':'Perfil bàsic. Completar el teu ADN Financer pot millorar la teva puntuació.','eu-ES':'Oinarrizko profila. ADN Finantzarioa osatzeak zure puntuazioa hobetu dezake.','gl-ES':'Perfil básico. Completar o ADN Financeiro pode mellorar a túa puntuación.' },
  'solvency.pts': { 'en-US':' pts','fr-FR':' pts','ca-ES':' pts','eu-ES':' pts','gl-ES':' pts' },
  'solvency.second_buyer_data': { 'en-US':'Second buyer\'s data','fr-FR':'Données du second acheteur','ca-ES':'Dades del segon comprador','eu-ES':'Bigarren eroslearen datuak','gl-ES':'Datos do segundo comprador' },
  'solvency.second_buyer_desc': { 'en-US':'Enter the details of the co-buyer.','fr-FR':'Saisissez les informations du co-acheteur.','ca-ES':'Introdueix les dades del co-titular de la compra.','eu-ES':'Sartu erosketa-kotituraren datuak.','gl-ES':'Introduce os datos do co-titular da compra.' },
  'solvency.co_titular': { 'en-US':'CO-BUYER','fr-FR':'CO-ACHETEUR','ca-ES':'CO-TITULAR','eu-ES':'KO-TITULAR','gl-ES':'CO-TITULAR' },
  'solvency.verifying_second_buyer': { 'en-US':'We are verifying the second buyer','fr-FR':'Nous vérifions le second acheteur','ca-ES':'Estem verificant el segon titular','eu-ES':'Bigarren titularra egiaztatzen ari gara','gl-ES':'Estamos verificando o segundo titular' },
  'solvency.ai_verifying_desc': { 'en-US':'Our AI system is comparing the face with the official document. This may take a few minutes.','fr-FR':'Notre système d\'IA compare le visage avec le document officiel. Cela peut prendre quelques minutes.','ca-ES':'El nostre sistema d\'IA està comparant el rostre amb el document oficial. Això pot trigar uns minuts.','eu-ES':'Gure AI sistemak aurpegia dokumentu ofizialarekin alderatzen ari da. Honek minutu batzuk har ditzake.','gl-ES':'O noso sistema de IA está comparando o rostro co documento oficial. Isto pode tardar uns minutos.' },
  'solvency.second_buyer_verified': { 'en-US':'2ND BUYER VERIFIED','fr-FR':'2ÈME ACHETEUR VÉRIFIÉ','ca-ES':'2N TITULAR VERIFICAT','eu-ES':'2. TITULARRA EGIAZTATUTA','gl-ES':'2º TITULAR VERIFICADO' },
  'solvency.second_buyer_verified_desc': { 'en-US':'The second buyer\'s identity has been verified and their data stored securely (AES-256).','fr-FR':'L\'identité du second acheteur a été vérifiée et ses données stockées de manière sécurisée (AES-256).','ca-ES':'La identitat del segon comprador ha estat verificada i les seves dades guardades de forma segura (AES-256).','eu-ES':'Bigarren eroslearen identitatea egiaztatu da eta datuak modu seguruan gorde dira (AES-256).','gl-ES':'A identidade do segundo comprador foi verificada e os seus datos gardados de forma segura (AES-256).' },
  'solvency.step_counter': { 'en-US':'Step {x} of {y}','fr-FR':'Étape {x} sur {y}','ca-ES':'Pas {x} de {y}','eu-ES':'{x}. urratsa {y}-tik','gl-ES':'Paso {x} de {y}' },
  'solvency.liability_notice_body': { 'en-US':'InmuFácil is not a financial institution. The solvency passport is based solely on the declarations you provide. Lying about your financial capacity will only waste your time and the seller\'s time on processes the bank will ultimately reject. By continuing, you declare that the information is truthful.','fr-FR':'InmuFácil n\'est pas un établissement financier. Le passeport de solvabilité est basé uniquement sur les déclarations que vous fournissez. Mentir sur votre capacité financière vous fera perdre votre temps et celui du vendeur dans des démarches que la banque finira par refuser. En continuant, vous déclarez que les informations sont véridiques.','ca-ES':'InmuFácil no és una entitat financera. El passaport de solvència es basa exclusivament en les declaracions que tu facilites. Mentir sobre la teva capacitat financera només et farà perdre temps a tu i al venedor en tràmits que el banc acabarà rebutjant. En continuar, declares que la informació és verídica.','eu-ES':'InmuFácil ez da finantza-erakunde bat. Kaudimenaren pasaportea zuk ematen dituzun aitorpenetan oinarritzen da soilik. Zure finantza-gaitasunari buruz gezurra esateak denbora galduko dizu eta saltzaileari ere bai, bankuak azkenean ezetsiko dituen tramiteetan. Jarraitzean, informazioa egiazkoa dela adierazten duzu.','gl-ES':'InmuFácil non é unha entidade financeira. O pasaporte de solvencia baséase exclusivamente nas declaracións que ti facilitas. Mentir sobre a túa capacidade financeira só che fará perder o tempo a ti e ao vendedor en trámites que o banco acabará rexeitando. Ao continuar, declaras que a información é verídica.' },
  'solvency.risk_high': { 'en-US':'Very High Risk (>38%)','fr-FR':'Risque Très Élevé (>38%)','ca-ES':'Risc Molt Alt (>38%)','eu-ES':'Arrisku Oso Altua (>%38)','gl-ES':'Risco Moi Alto (>38%)' },
  'solvency.risk_medium': { 'en-US':'Medium Risk (35-38%)','fr-FR':'Risque Moyen (35-38%)','ca-ES':'Risc Mitjà (35-38%)','eu-ES':'Arrisku Ertaina (%35-38)','gl-ES':'Risco Medio (35-38%)' },
  'solvency.risk_low': { 'en-US':'Healthy Risk (<35%)','fr-FR':'Risque Sain (<35%)','ca-ES':'Risc Saludable (<35%)','eu-ES':'Arrisku Osasungarria (<%35)','gl-ES':'Risco Saudable (<35%)' },
  'solvency.center_face': { 'en-US':'Centre your face','fr-FR':'Centrez votre visage','ca-ES':'Centra el teu rostre','eu-ES':'Zentratu zure aurpegia','gl-ES':'Centra o teu rostro' },
  'solvency.lighting_hint': { 'en-US':'Uniform lighting, no accessories','fr-FR':'Éclairage uniforme, sans accessoires','ca-ES':'Il·luminació uniforme, sense accessoris','eu-ES':'Argiztapen uniformea, osagarririk gabe','gl-ES':'Iluminación uniforme, sen accesorios' },
  'solvency.repeat_photo': { 'en-US':'Retake photo','fr-FR':'Reprendre la photo','ca-ES':'Repetir foto','eu-ES':'Argazkia errepikatu','gl-ES':'Repetir foto' },
  'solvency.start_camera': { 'en-US':'Start Camera','fr-FR':'Démarrer la Caméra','ca-ES':'Iniciar Càmera','eu-ES':'Kamera hasi','gl-ES':'Iniciar Cámara' },
  'solvency.identity_verified': { 'en-US':'Identity Verified','fr-FR':'Identité Vérifiée','ca-ES':'Identitat Verificada','eu-ES':'Identitatea Egiaztatuta','gl-ES':'Identidade Verificada' },
  'solvency.center_face_hint': { 'en-US':'Centre your face and press capture','fr-FR':'Centrez votre visage et appuyez sur capturer','ca-ES':'Centra el teu rostre i prem capturar','eu-ES':'Zentratu zure aurpegia eta sakatu harrapatu','gl-ES':'Centra o teu rostro e preme capturar' },
  'solvency.capture_btn': { 'en-US':'Capture','fr-FR':'Capturer','ca-ES':'Capturar','eu-ES':'Harrapatu','gl-ES':'Capturar' },
  'solvency.level_gold_title': { 'en-US':'Gold Level','fr-FR':'Niveau Or','ca-ES':'Nivell Or','eu-ES':'Urrezko Maila','gl-ES':'Nivel Ouro' },
  'solvency.level_silver_title': { 'en-US':'Silver Level','fr-FR':'Niveau Argent','ca-ES':'Nivell Plata','eu-ES':'Zilarrezko Maila','gl-ES':'Nivel Prata' },
  'solvency.level_bronze_title': { 'en-US':'Bronze Level','fr-FR':'Niveau Bronze','ca-ES':'Nivell Bronze','eu-ES':'Brontzezko Maila','gl-ES':'Nivel Bronce' },
  'solvency.gold_preview_desc': { 'en-US':'Your solvency looks excellent. You have strong chances of success.','fr-FR':'Votre solvabilité semble excellente. Vous avez de grandes chances de succès.','ca-ES':'La teva solvència sembla excel·lent. Tens moltes possibilitats d\'èxit.','eu-ES':'Zure kaudimena bikaina dirudi. Arrakasta izateko aukera handiak dituzu.','gl-ES':'A túa solvencia parece excelente. Tes moitas posibilidades de éxito.' },
  'solvency.silver_preview_desc': { 'en-US':'Your profile is solid, though some points could be improved.','fr-FR':'Votre profil est solide, bien que certains points puissent être améliorés.','ca-ES':'El teu perfil és sòlid, tot i que alguns punts podrien millorar.','eu-ES':'Zure profila sendoa da, nahiz eta zenbait puntu hobetu daitezkeen.','gl-ES':'O teu perfil é sólido, aínda que algúns puntos poderían mellorar.' },
  'solvency.bronze_preview_desc': { 'en-US':'Basic profile. We recommend reviewing your savings capacity.','fr-FR':'Profil de base. Nous vous recommandons de revoir votre capacité d\'épargne.','ca-ES':'Perfil bàsic. Et recomanem revisar la teva capacitat d\'estalvi.','eu-ES':'Oinarrizko profila. Zure aurrezki-gaitasuna berrikustea gomendatzen dizugu.','gl-ES':'Perfil básico. Recomendámosche revisar a túa capacidade de aforro.' },
};

const langs = ['en-US','en-GB','en-CA','fr-FR','fr-CA','ca-ES','va-ES','eu-ES','gl-ES'];

langs.forEach(lang => {
  const fp = base + lang + '.json';
  const json = JSON.parse(fs.readFileSync(fp, 'utf8'));
  let count = 0;
  Object.entries(translations).forEach(([path, vals]) => {
    // Determine source language for this locale
    let src = lang;
    if (lang === 'en-GB' || lang === 'en-CA') src = 'en-US';
    if (lang === 'fr-CA') src = 'fr-FR';
    if (lang === 'va-ES') src = 'ca-ES';
    const val = vals[src] || vals['en-US'];
    if (val !== undefined) {
      setVal(json, path, val);
      count++;
    }
  });
  fs.writeFileSync(fp, JSON.stringify(json, null, 2), 'utf8');
  console.log(lang + ': updated ' + count + ' solvency keys');
});
