const fs = require('fs');
const base = 'C:/Users/Os/.gemini/antigravity/scratch/InmuFacil_Project/frontend/assets/translations/';

function setVal(obj, path, val) {
  const parts = path.split('.');
  const last = parts.pop();
  const target = parts.reduce((o, k) => { if (!o[k]) o[k] = {}; return o[k]; }, obj);
  target[last] = val;
}

const translations = {
  // VISITS
  'visits.configured_windows': { 'en-US':'CONFIGURED WINDOWS','fr-FR':'FENÊTRES CONFIGURÉES','ca-ES':'FINESTRES CONFIGURADES','eu-ES':'KONFIGURATUTAKO LEIHOAK','gl-ES':'XANELAS CONFIGURADAS' },
  'visits.error_loading_windows': { 'en-US':'Error loading availability windows.','fr-FR':'Erreur lors du chargement des créneaux de disponibilité.','ca-ES':'Error en carregar les finestres de disponibilitat.','eu-ES':'Erabilgarritasun-leihoak kargatzean errorea.','gl-ES':'Erro ao cargar as xanelas de dispoñibilidade.' },
  'visits.no_windows_configured': { 'en-US':'You have no availability windows configured for this property.','fr-FR':'Vous n\'avez aucun créneau de disponibilité configuré pour ce bien.','ca-ES':'No tens finestres de disponibilitat configurades per a aquesta propietat.','eu-ES':'Propietate honetarako ez duzu erabilgarritasun-leihorik konfiguratuta.','gl-ES':'Non tes xanelas de dispoñibilidade configuradas para esta propiedade.' },
  'visits.create_new_window': { 'en-US':'New Availability Window','fr-FR':'Nouveau Créneau de Disponibilité','ca-ES':'Nova Finestra de Disponibilitat','eu-ES':'Erabilgarritasun-leiho berria','gl-ES':'Nova Xanela de Dispoñibilidade' },
  'visits.define_block_desc': { 'en-US':'Define a time block so interested buyers can book {duration}-minute appointments.','fr-FR':'Définissez un bloc horaire pour que les acheteurs intéressés puissent réserver des rendez-vous de {duration} minutes.','ca-ES':'Defineix un bloc de temps perquè els interessats puguin reservar cites de {duration} minuts.','eu-ES':'Definitu denbora-bloke bat interesatuek {duration} minutuko hitzorduak erreserbatu ditzaten.','gl-ES':'Define un bloque de tempo para que os interesados poidan reservar citas de {duration} minutos.' },
  'visits.start_time': { 'en-US':'Start time','fr-FR':'Heure de début','ca-ES':'Hora inici','eu-ES':'Hasiera-ordua','gl-ES':'Hora inicio' },
  'visits.end_time': { 'en-US':'End time','fr-FR':'Heure de fin','ca-ES':'Hora fi','eu-ES':'Amaiera-ordua','gl-ES':'Hora fin' },
  'visits.slot_duration': { 'en-US':'Appointment duration','fr-FR':'Durée du rendez-vous','ca-ES':'Durada cita','eu-ES':'Hitzordu-iraupena','gl-ES':'Duración cita' },
  'visits.visit_duration_title': { 'en-US':'Visit duration','fr-FR':'Durée de la visite','ca-ES':'Durada de la visita','eu-ES':'Bisitaren iraupena','gl-ES':'Duración da visita' },
  'visits.minutes': { 'en-US':'{min} minutes','fr-FR':'{min} minutes','ca-ES':'{min} minuts','eu-ES':'{min} minutu','gl-ES':'{min} minutos' },
  'visits.preview_creating': { 'en-US':'{count} slots of {duration} min will be created between {start} and {end}.','fr-FR':'{count} créneaux de {duration} min seront créés entre {start} et {end}.','ca-ES':'Es crearan {count} espais de {duration} min entre les {start} i les {end}.','eu-ES':'{start} eta {end} artean {count} tarte sortuko dira {duration} minutukoak.','gl-ES':'Crearanse {count} espazos de {duration} min entre as {start} e as {end}.' },
  'visits.error_end_after_start': { 'en-US':'The end time must be after the start time.','fr-FR':'L\'heure de fin doit être postérieure à l\'heure de début.','ca-ES':'L\'hora de fi ha de ser posterior a la d\'inici.','eu-ES':'Amaiera-ordua hasiera-orduaren ondoren egon behar da.','gl-ES':'A hora de fin debe ser posterior á de inicio.' },
  'visits.success_created': { 'en-US':'Availability window created successfully.','fr-FR':'Créneau de disponibilité créé avec succès.','ca-ES':'Finestra de disponibilitat creada amb èxit.','eu-ES':'Erabilgarritasun-leihoa behar bezala sortu da.','gl-ES':'Xanela de dispoñibilidade creada con éxito.' },
  'visits.error_overlap': { 'en-US':'This time slot overlaps with an existing window.','fr-FR':'Ce créneau horaire chevauche une fenêtre existante.','ca-ES':'Aquest horari se solapa amb una finestra existent.','eu-ES':'Ordu-tarte hau dagoen leiho batekin gainjarri egiten da.','gl-ES':'Este horario solápase cunha xanela existente.' },
  'visits.past': { 'en-US':'PAST','fr-FR':'PASSÉ','ca-ES':'PASSAT','eu-ES':'IRAGANA','gl-ES':'PASADO' },
  'visits.active': { 'en-US':'ACTIVE','fr-FR':'ACTIVE','ca-ES':'ACTIVA','eu-ES':'AKTIBO','gl-ES':'ACTIVA' },
  'visits.slots_duration_text': { 'en-US':'Appointments of {duration} min','fr-FR':'Rendez-vous de {duration} min','ca-ES':'Cites de {duration} min','eu-ES':'{duration} minutuko hitzorduak','gl-ES':'Citas de {duration} min' },
  'visits.success_requested': { 'en-US':'Visit requested successfully. The seller will receive your proposal.','fr-FR':'Visite demandée avec succès. Le vendeur recevra votre proposition.','ca-ES':'Visita sol·licitada amb èxit. El venedor rebrà la teva proposta.','eu-ES':'Bisita behar bezala eskatu da. Saltzaileak zure proposamena jasoko du.','gl-ES':'Visita solicitada con éxito. O vendedor recibirá a túa proposta.' },
  'visits.error_booking': { 'en-US':'Error requesting the visit.','fr-FR':'Erreur lors de la demande de visite.','ca-ES':'Error en sol·licitar la visita.','eu-ES':'Bisita eskatzerakoan errorea.','gl-ES':'Erro ao solicitar a visita.' },
  'visits.already_scheduled_title': { 'en-US':'You already have a scheduled visit','fr-FR':'Vous avez déjà une visite planifiée','ca-ES':'Ja tens una visita programada','eu-ES':'Dagoeneko bisita programatua duzu','gl-ES':'Xa tes unha visita programada' },
  'visits.status_label': { 'en-US':'Status: {status}','fr-FR':'Statut : {status}','ca-ES':'Estat: {status}','eu-ES':'Egoera: {status}','gl-ES':'Estado: {status}' },
  'visits.status_pending_confirm': { 'en-US':'Pending confirmation','fr-FR':'En attente de confirmation','ca-ES':'Pendent de confirmar','eu-ES':'Baieztapena zain','gl-ES':'Pendente de confirmar' },
  'visits.status_confirmed': { 'en-US':'Confirmed','fr-FR':'Confirmée','ca-ES':'Confirmada','eu-ES':'Berretsia','gl-ES':'Confirmada' },
  'visits.view_my_visits': { 'en-US':'View my visits','fr-FR':'Voir mes visites','ca-ES':'Veure les meves visites','eu-ES':'Ikusi nire bisitak','gl-ES':'Ver as miñas visitas' },
  'visits.no_slots_available': { 'en-US':'No available slots at the moment.','fr-FR':'Aucun créneau disponible actuellement.','ca-ES':'No hi ha espais disponibles actualment.','eu-ES':'Oraingoz ez dago tarterik eskuragarri.','gl-ES':'Non hai espazos dispoñibles actualmente.' },
  'visits.select_date_time': { 'en-US':'Select day and time','fr-FR':'Sélectionner jour et heure','ca-ES':'Selecciona dia i hora','eu-ES':'Hautatu eguna eta ordua','gl-ES':'Selecciona día e hora' },
  'visits.available_hours': { 'en-US':'AVAILABLE TIMES','fr-FR':'HORAIRES DISPONIBLES','ca-ES':'HORARIS DISPONIBLES','eu-ES':'ORDU ESKURAGARRIAK','gl-ES':'HORARIOS DISPOÑIBLES' },
  'visits.free_slots': { 'en-US':'{count} free','fr-FR':'{count} libres','ca-ES':'{count} lliures','eu-ES':'{count} libre','gl-ES':'{count} libres' },
  'visits.select_day_hint': { 'en-US':'Select a day on the calendar\nto see available times.','fr-FR':'Sélectionnez un jour dans le calendrier\npour voir les horaires disponibles.','ca-ES':'Selecciona un dia al calendari\nper veure els horaris disponibles.','eu-ES':'Hautatu egun bat egutegian\nerabilgarri dauden orduak ikusteko.','gl-ES':'Selecciona un día no calendario\npara ver os horarios dispoñibles.' },
  'visits.notes_label': { 'en-US':'Notes for the seller (optional)','fr-FR':'Notes pour le vendeur (optionnel)','ca-ES':'Notes per al venedor (opcional)','eu-ES':'Oharrak saltzailearentzat (aukerakoa)','gl-ES':'Notas para o vendedor (opcional)' },
  'visits.notes_hint': { 'en-US':'E.g.: Is it possible to see the storage room? / We are a couple...','fr-FR':'Ex : Est-il possible de voir le débarras ? / Nous sommes un couple...','ca-ES':'Ex: És possible veure el traster? / Som una parella...','eu-ES':'Adib.: Posible al da biltegia ikustea? / Bikotea gara...','gl-ES':'Ex: ¿É posible ver o trasteiro? / Somos parella...' },
  'visits.protected_visit_title': { 'en-US':'Visit Protected by InmuFácil','fr-FR':'Visite Protégée par InmuFácil','ca-ES':'Visita Protegida per InmuFácil','eu-ES':'InmuFácil-ek Babestutako Bisita','gl-ES':'Visita Protexida por InmuFácil' },
  'visits.protected_visit_desc': { 'en-US':'Your personal data is not shared until the visit is confirmed. Communication is secure.','fr-FR':'Vos données personnelles ne sont pas partagées tant que la visite n\'est pas confirmée. La communication est sécurisée.','ca-ES':'Les teves dades personals no es comparteixen fins que la visita és confirmada. La comunicació és segura.','eu-ES':'Zure datu pertsonalak ez dira partekatzen bisita baieztatu arte. Komunikazioa segurua da.','gl-ES':'Os teus datos persoais non se comparten ata que a visita é confirmada. A comunicación é segura.' },
  'visits.visit_summary': { 'en-US':'VISIT SUMMARY','fr-FR':'RÉSUMÉ DE LA VISITE','ca-ES':'RESUM DE LA VISITA','eu-ES':'BISITAREN LABURPENA','gl-ES':'RESUMO DA VISITA' },
  'visits.confirm_request': { 'en-US':'Confirm Request','fr-FR':'Confirmer la Demande','ca-ES':'Confirmar Sol·licitud','eu-ES':'Baieztatu Eskaera','gl-ES':'Confirmar Solicitude' },
  'visits.visit_summary_text': { 'en-US':'{day} {month} at {time}','fr-FR':'{day} {month} à {time}','ca-ES':'Dia {day} de {month} a les {time}','eu-ES':'{month}ren {day}an {time}etan','gl-ES':'Día {day} de {month} ás {time}' },
  'visits.email_request_success': { 'en-US':'Proposal sent successfully.','fr-FR':'Proposition envoyée avec succès.','ca-ES':'Proposta enviada correctament.','eu-ES':'Proposamena behar bezala bidali da.','gl-ES':'Proposta enviada correctamente.' },
  'visits.email_request_error': { 'en-US':'Error sending the proposal.','fr-FR':'Erreur lors de l\'envoi de la proposition.','ca-ES':'Error en enviar la proposta.','eu-ES':'Proposamena bidaltzean errorea.','gl-ES':'Erro ao enviar a proposta.' },
  'visits.no_seller_windows': { 'en-US':'Seller has no active calendar','fr-FR':'Le vendeur n\'a pas de calendrier actif','ca-ES':'Venedor sense calendari actiu','eu-ES':'Saltzaileak ez du egutegi aktiborik','gl-ES':'Vendedor sen calendario activo' },
  'visits.no_seller_windows_desc': { 'en-US':'This seller has not yet configured their availability windows for automatic visits.','fr-FR':'Ce vendeur n\'a pas encore configuré ses créneaux de disponibilité pour les visites automatiques.','ca-ES':'Aquest venedor encara no ha configurat les seves finestres de disponibilitat per a visites automàtiques.','eu-ES':'Saltzaile honek oraindik ez ditu bisita automatikoen erabilgarritasun-leihoak konfiguratu.','gl-ES':'Este vendedor aínda non configurou as súas xanelas de dispoñibilidade para visitas automáticas.' },
  'visits.email_message_label': { 'en-US':'Optional message for the seller...','fr-FR':'Message optionnel pour le vendeur...','ca-ES':'Missatge opcional per al venedor...','eu-ES':'Aukerako mezua saltzailearentzat...','gl-ES':'Mensaxe opcional para o vendedor...' },
  'visits.request_visit_email_btn': { 'en-US':'Propose visit by email','fr-FR':'Proposer une visite par email','ca-ES':'Proposar visita per email','eu-ES':'Bisita proposatu emailez','gl-ES':'Propoñer visita por email' },
  'visits.no_slots_email_title': { 'en-US':'No immediate availability','fr-FR':'Aucune disponibilité immédiate','ca-ES':'Sense disponibilitat immediata','eu-ES':'Ez dago berehala erabilgarritasunik','gl-ES':'Sen dispoñibilidade inmediata' },
  'visits.no_slots_email_desc': { 'en-US':'The seller has no configured slots. You can send them a message to propose a date.','fr-FR':'Le vendeur n\'a pas de créneaux configurés. Vous pouvez lui envoyer un message pour proposer une date.','ca-ES':'El venedor no té espais configurats. Pots enviar-li un missatge per proposar una data.','eu-ES':'Saltzaileak ez ditu tarterik konfiguratuta. Mezu bat bidal diezaiokezu data proposatzeko.','gl-ES':'O vendedor non ten espazos configurados. Podes enviarlle unha mensaxe para propoñer unha data.' },
  'visits.create_window_btn': { 'en-US':'Create availability window','fr-FR':'Créer un créneau de disponibilité','ca-ES':'Crear finestra de disponibilitat','eu-ES':'Sortu erabilgarritasun-leihoa','gl-ES':'Crear xanela de dispoñibilidade' },
  // NOTIFICATIONS
  'notifications.mark_all_read': { 'en-US':'Mark all as read','fr-FR':'Tout marquer comme lu','ca-ES':'Marcar tot com llegit','eu-ES':'Guztia irakurrita markatu','gl-ES':'Marcar todo como lido' },
  'notifications.mark_all_read_success': { 'en-US':'All notifications marked as read.','fr-FR':'Toutes les notifications marquées comme lues.','ca-ES':'Totes les notificacions marcades com llegides.','eu-ES':'Jakinarazpen guztiak irakurrita markatuta.','gl-ES':'Todas as notificacións marcadas como lidas.' },
  'notifications.empty_state': { 'en-US':'No notifications','fr-FR':'Aucune notification','ca-ES':'Sense notificacions','eu-ES':'Ez dago jakinarazpenik','gl-ES':'Sen notificacións' },
  'notifications.empty_state_desc': { 'en-US':'Your operation\'s alerts\nwill appear here.','fr-FR':'Les alertes de votre\nopération apparaîtront ici.','ca-ES':'Aquí apareixeran els avisos\nde la teva operació.','eu-ES':'Zure eragiketaren abisuak\nhemen agertuko dira.','gl-ES':'Aquí aparecerán os avisos\nda túa operación.' },
  'notifications.error_loading': { 'en-US':'Could not load notifications.','fr-FR':'Impossible de charger les notifications.','ca-ES':'No s\'han pogut carregar les notificacions.','eu-ES':'Ezin izan dira jakinarazpenak kargatu.','gl-ES':'Non se puideron cargar as notificacións.' },
  'notifications.retry': { 'en-US':'Retry','fr-FR':'Réessayer','ca-ES':'Reintentar','eu-ES':'Saiatu berriro','gl-ES':'Reintentar' },
  'notifications.time.now': { 'en-US':'Just now','fr-FR':'À l\'instant','ca-ES':'Ara mateix','eu-ES':'Orain bertan','gl-ES':'Agora mesmo' },
  'notifications.time.minutes_ago': { 'en-US':'{} min ago','fr-FR':'Il y a {} min','ca-ES':'Fa {} min','eu-ES':'Duela {} min','gl-ES':'Hai {} min' },
  'notifications.time.hours_ago': { 'en-US':'{} h ago','fr-FR':'Il y a {} h','ca-ES':'Fa {} h','eu-ES':'Duela {} h','gl-ES':'Hai {} h' },
  'notifications.time.yesterday': { 'en-US':'Yesterday','fr-FR':'Hier','ca-ES':'Ahir','eu-ES':'Atzo','gl-ES':'Onte' },
  'notifications.time.days_ago': { 'en-US':'{} days ago','fr-FR':'Il y a {} jours','ca-ES':'Fa {} dies','eu-ES':'Duela {} egun','gl-ES':'Hai {} días' },
  'notifications.settings.section_offers': { 'en-US':'Offer Activity','fr-FR':'Activité des Offres','ca-ES':'Activitat d\'Ofertes','eu-ES':'Eskaintzen Jarduera','gl-ES':'Actividade de Ofertas' },
  'notifications.settings.offer_received': { 'en-US':'Offer Received','fr-FR':'Offre Reçue','ca-ES':'Oferta Rebuda','eu-ES':'Eskaintza Jasota','gl-ES':'Oferta Recibida' },
  'notifications.settings.offer_received_desc': { 'en-US':'Alert when I receive a new offer for my property.','fr-FR':'Alerter lorsque je reçois une nouvelle offre pour mon bien.','ca-ES':'Avisar quan rebi una nova oferta per la meva propietat.','eu-ES':'Abisuak eman nire propietatearentzako eskaintza berri bat jasotzen dudanean.','gl-ES':'Avisar cando reciba unha nova oferta pola miña propiedade.' },
  'notifications.settings.offer_accepted': { 'en-US':'Offer Accepted','fr-FR':'Offre Acceptée','ca-ES':'Oferta Acceptada','eu-ES':'Eskaintza Onartuta','gl-ES':'Oferta Aceptada' },
  'notifications.settings.offer_accepted_desc': { 'en-US':'Alert when the seller accepts my offer.','fr-FR':'Alerter lorsque le vendeur accepte mon offre.','ca-ES':'Avisar quan el venedor accepti la meva oferta.','eu-ES':'Abisuak eman saltzaileak nire eskaintza onartzen duenean.','gl-ES':'Avisar cando o vendedor acepte a miña oferta.' },
  'notifications.settings.offer_countered': { 'en-US':'Counteroffer Received','fr-FR':'Contre-offre Reçue','ca-ES':'Contraoferta Rebuda','eu-ES':'Kontraeskaintza Jasota','gl-ES':'Contraoferta Recibida' },
  'notifications.settings.offer_countered_desc': { 'en-US':'Alert when I receive a counteroffer.','fr-FR':'Alerter lorsque je reçois une contre-offre.','ca-ES':'Avisar quan rebi una contraoferta.','eu-ES':'Abisuak eman kontraeskaintza bat jasotzen dudanean.','gl-ES':'Avisar cando reciba unha contraoferta.' },
  'notifications.settings.section_messages': { 'en-US':'Messages and Chat','fr-FR':'Messages et Chat','ca-ES':'Missatges i Xat','eu-ES':'Mezuak eta Txata','gl-ES':'Mensaxes e Chat' },
  'notifications.settings.new_message': { 'en-US':'New Message','fr-FR':'Nouveau Message','ca-ES':'Nou Missatge','eu-ES':'Mezu Berria','gl-ES':'Nova Mensaxe' },
  'notifications.settings.new_message_desc': { 'en-US':'Alert when I receive a message in the chat.','fr-FR':'Alerter lorsque je reçois un message dans le chat.','ca-ES':'Avisar quan rebi un missatge al xat.','eu-ES':'Abisuak eman txatean mezu bat jasotzen dudanean.','gl-ES':'Avisar cando reciba unha mensaxe no chat.' },
  'notifications.settings.section_property': { 'en-US':'My Property','fr-FR':'Mon Bien','ca-ES':'La meva Propietat','eu-ES':'Nire Propietatea','gl-ES':'A miña Propiedade' },
  'notifications.settings.property_status_change': { 'en-US':'Status Change','fr-FR':'Changement de Statut','ca-ES':'Canvi d\'Estat','eu-ES':'Egoera-Aldaketa','gl-ES':'Cambio de Estado' },
  'notifications.settings.property_status_change_desc': { 'en-US':'Alert when the status of my listing changes.','fr-FR':'Alerter lorsque le statut de ma publication change.','ca-ES':'Avisar quan canviï l\'estat de la meva publicació.','eu-ES':'Abisuak eman nire argitalpenaren egoera aldatzen denean.','gl-ES':'Avisar cando cambie o estado da miña publicación.' },
  'notifications.settings.section_marketing': { 'en-US':'News and Information','fr-FR':'Actualités et Informations','ca-ES':'Novetats i Informació','eu-ES':'Berriak eta Informazioa','gl-ES':'Novidades e Información' },
  'notifications.settings.marketing_emails': { 'en-US':'Marketing Emails','fr-FR':'Emails Marketing','ca-ES':'Emails de Màrqueting','eu-ES':'Marketing Emailak','gl-ES':'Emails de Marketing' },
  'notifications.settings.marketing_emails_desc': { 'en-US':'Receive news about new features and offers.','fr-FR':'Recevoir des actualités sur les nouvelles fonctionnalités et offres.','ca-ES':'Rebre notícies sobre noves funcions i ofertes.','eu-ES':'Jaso funtzio eta eskaintza berrien berriak.','gl-ES':'Recibir noticias sobre novas funcións e ofertas.' },
  // SEARCH
  'search.verified_this_week': { 'en-US':'Verified this week','fr-FR':'Vérifiées cette semaine','ca-ES':'Verificades aquesta setmana','eu-ES':'Aste honetan egiaztatuak','gl-ES':'Verificadas esta semana' },
  'search.property_type_all': { 'en-US':'All','fr-FR':'Tous','ca-ES':'Tots','eu-ES':'Guztiak','gl-ES':'Todos' },
  'search.property_type_apartment': { 'en-US':'Flat / Apartment','fr-FR':'Appartement','ca-ES':'Pis / Apartament','eu-ES':'Pisua / Apartamentua','gl-ES':'Piso / Apartamento' },
  'search.property_type_house': { 'en-US':'House / Villa','fr-FR':'Maison / Villa','ca-ES':'Casa / Xalet','eu-ES':'Etxea / Txaleta','gl-ES':'Casa / Chalet' },
  'search.property_type_land': { 'en-US':'Land / Plot','fr-FR':'Terrain / Parcelle','ca-ES':'Terreny / Parcel·la','eu-ES':'Lurra / Lursaila','gl-ES':'Terreo / Parcela' },
  'search.property_type_office': { 'en-US':'Office / Commercial','fr-FR':'Bureau / Local commercial','ca-ES':'Oficina / Local','eu-ES':'Bulegoa / Lokala','gl-ES':'Oficina / Local' },
  'search.property_type_garage': { 'en-US':'Garage','fr-FR':'Garage','ca-ES':'Garatge','eu-ES':'Garajea','gl-ES':'Garaxe' },
  'search.property_type_new_construction': { 'en-US':'New Build','fr-FR':'Construction Neuve','ca-ES':'Obra Nova','eu-ES':'Obra Berria','gl-ES':'Obra Nova' },
  'search.property_type_atico': { 'en-US':'Penthouse','fr-FR':'Penthouse','ca-ES':'Àtic','eu-ES':'Atico','gl-ES':'Ático' },
  'search.property_type_duplex': { 'en-US':'Duplex','fr-FR':'Duplex','ca-ES':'Dúplex','eu-ES':'Duplexа','gl-ES':'Dúplex' },
  'search.property_type_rustic_house': { 'en-US':'Rustic House','fr-FR':'Maison Rustique','ca-ES':'Casa Rústica','eu-ES':'Etxe Errustikoа','gl-ES':'Casa Rústica' },
  'search.property_type_singular_house': { 'en-US':'Singular House','fr-FR':'Maison Singulière','ca-ES':'Casa Singular','eu-ES':'Etxe Singularra','gl-ES':'Casa Singular' },
  'search.property_type_local': { 'en-US':'Commercial Premises','fr-FR':'Local Commercial','ca-ES':'Local Comercial','eu-ES':'Merkataritza Lokala','gl-ES':'Local Comercial' },
  'search.property_type_industrial': { 'en-US':'Industrial Unit','fr-FR':'Entrepôt Industriel','ca-ES':'Nau Industrial','eu-ES':'Industria Nabea','gl-ES':'Nave Industrial' },
  'search.property_type_building': { 'en-US':'Building','fr-FR':'Immeuble','ca-ES':'Edifici','eu-ES':'Eraikina','gl-ES':'Edificio' },
  'search.property_type_rustic_land': { 'en-US':'Rural Land','fr-FR':'Finca Rurale','ca-ES':'Finca Rústica','eu-ES':'Finka Errustikoа','gl-ES':'Finca Rústica' },
  'search.price_range_label': { 'en-US':'Price Range','fr-FR':'Fourchette de Prix','ca-ES':'Rang de Preu','eu-ES':'Prezio-tartea','gl-ES':'Rango de Prezo' },
  'search.price_from': { 'en-US':'From','fr-FR':'De','ca-ES':'Des de','eu-ES':'Hemendik','gl-ES':'Dende' },
  'search.price_to': { 'en-US':'To','fr-FR':'Jusqu\'à','ca-ES':'Fins a','eu-ES':'Arte','gl-ES':'Ata' },
  'search.map_loading': { 'en-US':'Loading map...','fr-FR':'Chargement de la carte...','ca-ES':'Carregant mapa...','eu-ES':'Mapa kargatzen...','gl-ES':'Cargando mapa...' },
  'search.map_error': { 'en-US':'Error loading the map','fr-FR':'Erreur lors du chargement de la carte','ca-ES':'Error en carregar el mapa','eu-ES':'Mapa kargatzean errorea','gl-ES':'Erro ao cargar o mapa' },
  'search.location_permission_denied': { 'en-US':'Location permission denied','fr-FR':'Permission de localisation refusée','ca-ES':'Permís d\'ubicació denegat','eu-ES':'Kokapenaren baimena ukatu da','gl-ES':'Permiso de localización denegado' },
  'search.reset_filters': { 'en-US':'Reset filters','fr-FR':'Réinitialiser les filtres','ca-ES':'Restablir filtres','eu-ES':'Iragazkiak berrezarri','gl-ES':'Restablecer filtros' },
  'search.property_type_label': { 'en-US':'Property type','fr-FR':'Type de bien','ca-ES':'Tipus d\'immoble','eu-ES':'Propietate mota','gl-ES':'Tipo de inmoble' },
  'search.bedrooms_filter_label': { 'en-US':'Bedrooms','fr-FR':'Chambres','ca-ES':'Habitacions','eu-ES':'Logelak','gl-ES':'Habitacións' },
  'search.extras_filter_label': { 'en-US':'Extras','fr-FR':'Extras','ca-ES':'Extres','eu-ES':'Gehigarriak','gl-ES':'Extras' },
  'search.no_results_found': { 'en-US':'Nothing found here','fr-FR':'Aucun résultat trouvé ici','ca-ES':'No hem trobat res aquí','eu-ES':'Ez da ezer aurkitu hemen','gl-ES':'Non atopamos nada aquí' },
  'search.clear_filters': { 'en-US':'Clear filters','fr-FR':'Effacer les filtres','ca-ES':'Netejar filtres','eu-ES':'Garbitu iragazkiak','gl-ES':'Limpar filtros' },
  'search.clear_filters_button': { 'en-US':'Clear Filters','fr-FR':'Effacer les filtres','ca-ES':'Netejar Filtres','eu-ES':'Garbitu Iragazkiak','gl-ES':'Limpar Filtros' },
  'search.properties_count': { 'en-US':'{count} Properties','fr-FR':'{count} Biens','ca-ES':'{count} Immobles','eu-ES':'{count} Propietate','gl-ES':'{count} Inmobles' },
  'search.custom_price_title': { 'en-US':'Custom maximum price','fr-FR':'Prix maximum personnalisé','ca-ES':'Preu màxim personalitzat','eu-ES':'Prezio gehieneko pertsonalizatua','gl-ES':'Prezo máximo personalizado' },
  'search.custom_price_label': { 'en-US':'Maximum price (€)','fr-FR':'Prix maximum (€)','ca-ES':'Preu màxim (€)','eu-ES':'Prezio gehiena (€)','gl-ES':'Prezo máximo (€)' },
  'search.apply': { 'en-US':'Apply','fr-FR':'Appliquer','ca-ES':'Aplicar','eu-ES':'Aplikatu','gl-ES':'Aplicar' },
  'search.guarantee_label': { 'en-US':'INMUFÁCIL GUARANTEE','fr-FR':'GARANTIE INMUFÁCIL','ca-ES':'GARANTIA INMUFÁCIL','eu-ES':'INMUFÁCIL BERMEA','gl-ES':'GARANTÍA INMUFÁCIL' },
  'search.verified_label': { 'en-US':'P2P VERIFIED','fr-FR':'P2P VÉRIFIÉ','ca-ES':'P2P VERIFICAT','eu-ES':'P2P EGIAZTATUTA','gl-ES':'P2P VERIFICADO' },
  'search.search_hint': { 'en-US':'Search by city, area...','fr-FR':'Rechercher par ville, zone...','ca-ES':'Cercar per ciutat, zona...','eu-ES':'Bilatu hirirako, eremuaren arabera...','gl-ES':'Buscar por cidade, zona...' },
  'search.nav_buy': { 'en-US':'Buy','fr-FR':'Acheter','ca-ES':'Comprar','eu-ES':'Erosi','gl-ES':'Comprar' },
  'search.nav_sell': { 'en-US':'Sell','fr-FR':'Vendre','ca-ES':'Vendre','eu-ES':'Saldu','gl-ES':'Vender' },
  'search.nav_how_works': { 'en-US':'How it works','fr-FR':'Comment ça marche','ca-ES':'Com funciona','eu-ES':'Nola funtzionatzen du','gl-ES':'Como funciona' },
  'search.nav_what_is': { 'en-US':'What is InmuFácil','fr-FR':'Qu\'est-ce qu\'InmuFácil','ca-ES':'Què és InmuFácil','eu-ES':'Zer da InmuFácil','gl-ES':'Que é InmuFácil' },
  'search.nav_buyer_guide': { 'en-US':'Buyer\'s Guide','fr-FR':'Guide de l\'Acheteur','ca-ES':'Guia del Comprador','eu-ES':'Eroslearen Gida','gl-ES':'Guía do Comprador' },
  'search.nav_seller_guide': { 'en-US':'Seller\'s Guide','fr-FR':'Guide du Vendeur','ca-ES':'Guia del Venedor','eu-ES':'Saltzailearen Gida','gl-ES':'Guía do Vendedor' },
  'search.nav_contact': { 'en-US':'Contact','fr-FR':'Contact','ca-ES':'Contacte','eu-ES':'Kontaktua','gl-ES':'Contacto' },
  'search.nav_guides': { 'en-US':'Guides','fr-FR':'Guides','ca-ES':'Guies','eu-ES':'Gidak','gl-ES':'Guías' },
  'search.account_required_title': { 'en-US':'Account required','fr-FR':'Compte requis','ca-ES':'Compte necessari','eu-ES':'Kontua beharrezkoa','gl-ES':'Conta necesaria' },
  'search.account_required_body': { 'en-US':'To list and sell a property you need an InmuFácil account. It\'s free and only takes a few minutes.','fr-FR':'Pour publier et vendre un bien, vous avez besoin d\'un compte InmuFácil. C\'est gratuit et ne prend que quelques minutes.','ca-ES':'Per publicar i vendre una propietat necessites un compte a InmuFácil. És gratuït i només triga uns minuts.','eu-ES':'Propietate bat argitaratu eta saltzeko InmuFácil kontu bat behar duzu. Doakoa da eta minutu gutxi batzuk baino ez du behar.','gl-ES':'Para publicar e vender unha propiedade precisas unha conta en InmuFácil. É gratuíto e só leva uns minutos.' },
  // PROPERTY LISTING
  'property_listing.sqm_unit': { 'en-US':'sqm','fr-FR':'m²','ca-ES':'m²','eu-ES':'m²','gl-ES':'m²' },
  'property_listing.extras': { 'en-US':'Extras','fr-FR':'Extras','ca-ES':'Extres','eu-ES':'Gehigarriak','gl-ES':'Extras' },
  'property_listing.extra_labels.pool': { 'en-US':'Pool','fr-FR':'Piscine','ca-ES':'Piscina','eu-ES':'Igerilekua','gl-ES':'Piscina' },
  'property_listing.extra_labels.garage': { 'en-US':'Garage','fr-FR':'Garage','ca-ES':'Garatge','eu-ES':'Garajea','gl-ES':'Garaxe' },
  'property_listing.extra_labels.terrace': { 'en-US':'Terrace','fr-FR':'Terrasse','ca-ES':'Terrassa','eu-ES':'Terraza','gl-ES':'Terraza' },
  'property_listing.extra_labels.garden': { 'en-US':'Garden','fr-FR':'Jardin','ca-ES':'Jardí','eu-ES':'Lorategia','gl-ES':'Xardín' },
  'property_listing.extra_labels.lift': { 'en-US':'Lift','fr-FR':'Ascenseur','ca-ES':'Ascensor','eu-ES':'Igogailua','gl-ES':'Ascensor' },
  'property_listing.extra_labels.ac': { 'en-US':'Air Conditioning','fr-FR':'Climatisation','ca-ES':'Aire Condicionat','eu-ES':'Aire Girotua','gl-ES':'Aire Acondicionado' },
  'property_listing.extra_labels.heating': { 'en-US':'Heating','fr-FR':'Chauffage','ca-ES':'Calefacció','eu-ES':'Berogailua','gl-ES':'Calefacción' },
  'property_listing.extra_labels.storage': { 'en-US':'Storage Room','fr-FR':'Cave / Débarras','ca-ES':'Traster','eu-ES':'Biltegiak','gl-ES':'Trasteiro' },
  'property_listing.extra_labels.wardrobes': { 'en-US':'Built-in Wardrobes','fr-FR':'Placards Intégrés','ca-ES':'Armaris Encastats','eu-ES':'Armairuak txertatuak','gl-ES':'Armarios Empotrados' },
  'property_listing.extra_labels.exterior': { 'en-US':'Exterior','fr-FR':'Extérieur','ca-ES':'Exterior','eu-ES':'Kanpokoa','gl-ES':'Exterior' },
  'property_listing.extra_labels.accessible': { 'en-US':'Disability access','fr-FR':'Accès handicapés','ca-ES':'Accés mobilitat reduïda','eu-ES':'Mugikortasun mugaturako sarrera','gl-ES':'Acceso mobilidade reducida' },
  // PROPERTY
  'property.surface_count': { 'en-US':'{count} sqm','fr-FR':'{count} m²','ca-ES':'{count} m²','eu-ES':'{count} m²','gl-ES':'{count} m²' },
  'property.exterior': { 'en-US':'Exterior','fr-FR':'Extérieur','ca-ES':'Exterior','eu-ES':'Kanpokoa','gl-ES':'Exterior' },
  'property.image_counter': { 'en-US':'{current} / {total}','fr-FR':'{current} / {total}','ca-ES':'{current} / {total}','eu-ES':'{current} / {total}','gl-ES':'{current} / {total}' },
  // CHAT
  'chat.title': { 'en-US':'Messages','fr-FR':'Messages','ca-ES':'Missatges','eu-ES':'Mezuak','gl-ES':'Mensaxes' },
  'chat.no_conversations': { 'en-US':'No conversations','fr-FR':'Aucune conversation','ca-ES':'No hi ha converses','eu-ES':'Ez dago elkarrizketarik','gl-ES':'Non hai conversas' },
  'chat.error_loading': { 'en-US':'Error loading messages','fr-FR':'Erreur lors du chargement des messages','ca-ES':'Error en carregar missatges','eu-ES':'Mezuak kargatzean errorea','gl-ES':'Erro ao cargar mensaxes' },
  'chat.retry': { 'en-US':'Retry','fr-FR':'Réessayer','ca-ES':'Reintentar','eu-ES':'Saiatu berriro','gl-ES':'Reintentar' },
  'chat.active_offer': { 'en-US':'Active offer','fr-FR':'Offre active','ca-ES':'Oferta activa','eu-ES':'Eskaintza aktiboa','gl-ES':'Oferta activa' },
  'chat.start_conversation': { 'en-US':'Write the first message to start','fr-FR':'Écrivez le premier message pour commencer','ca-ES':'Escriu el primer missatge per començar','eu-ES':'Idatzi lehenengo mezua hasteko','gl-ES':'Escribe o primeiro mensaxe para empezar' },
  'chat.message_hint': { 'en-US':'Write a message...','fr-FR':'Écrire un message...','ca-ES':'Escriu un missatge...','eu-ES':'Idatzi mezu bat...','gl-ES':'Escribe unha mensaxe...' },
  'chat.online': { 'en-US':'Online','fr-FR':'En ligne','ca-ES':'En línia','eu-ES':'Linean','gl-ES':'En liña' },
  'chat.today': { 'en-US':'TODAY','fr-FR':'AUJOURD\'HUI','ca-ES':'AVUI','eu-ES':'GAUR','gl-ES':'HOY' },
  'chat.yesterday': { 'en-US':'Yesterday','fr-FR':'Hier','ca-ES':'Ahir','eu-ES':'Atzo','gl-ES':'Onte' },
  'chat.encrypted_badge': { 'en-US':'END-TO-END ENCRYPTED','fr-FR':'CHIFFREMENT DE BOUT EN BOUT','ca-ES':'XIFRAT DE EXTREM A EXTREM','eu-ES':'MUTURRETIK MUTURRERAKO ENKRIPTATUTA','gl-ES':'CIFRADO DE EXTREMO A EXTREMO' },
  'chat.send_error': { 'en-US':'Error sending message','fr-FR':'Erreur lors de l\'envoi du message','ca-ES':'Error en enviar missatge','eu-ES':'Mezua bidaltzean errorea','gl-ES':'Erro ao enviar mensaxe' },
  'chat.respond_error': { 'en-US':'Error responding','fr-FR':'Erreur lors de la réponse','ca-ES':'Error en respondre','eu-ES':'Erantzutean errorea','gl-ES':'Erro ao responder' },
  'chat.cancel_error': { 'en-US':'Error cancelling','fr-FR':'Erreur lors de l\'annulation','ca-ES':'Error en cancel·lar','eu-ES':'Bertan behera utzi ezin','gl-ES':'Erro ao cancelar' },
  'chat.send_button': { 'en-US':'Send','fr-FR':'Envoyer','ca-ES':'Enviar','eu-ES':'Bidali','gl-ES':'Enviar' },
  'chat.action_visit_request': { 'en-US':'Visit Request','fr-FR':'Demande de Visite','ca-ES':'Sol·licitud de Visita','eu-ES':'Bisita Eskaera','gl-ES':'Solicitude de Visita' },
  'chat.action_visit_accepted': { 'en-US':'Visit Confirmed','fr-FR':'Visite Confirmée','ca-ES':'Visita Confirmada','eu-ES':'Bisita Berretsia','gl-ES':'Visita Confirmada' },
  'chat.action_visit_rejected': { 'en-US':'Visit Rejected','fr-FR':'Visite Rejetée','ca-ES':'Visita Rebutjada','eu-ES':'Bisita Ukatuta','gl-ES':'Visita Rexeitada' },
  'chat.action_offer_proposal': { 'en-US':'Offer Proposal','fr-FR':'Proposition d\'Offre','ca-ES':'Proposta d\'Oferta','eu-ES':'Eskaintza Proposamena','gl-ES':'Proposta de Oferta' },
  'chat.action_docs_request': { 'en-US':'Document Request','fr-FR':'Demande de Documents','ca-ES':'Sol·licitud de Documents','eu-ES':'Dokumentu Eskaera','gl-ES':'Solicitude de Documentos' },
  'chat.action_generic': { 'en-US':'Action','fr-FR':'Action','ca-ES':'Acció','eu-ES':'Ekintza','gl-ES':'Acción' },
  'chat.qualified_candidate': { 'en-US':'Qualified Candidate: {level}','fr-FR':'Candidat Qualifié : {level}','ca-ES':'Candidat Qualificat: {level}','eu-ES':'Hautagai Kualifikatua: {level}','gl-ES':'Candidato Cualificado: {level}' },
  'chat.solvency_draft_wip': { 'en-US':'Coming soon: Solvency-based contract draft','fr-FR':'Prochainement : Brouillon de contrat basé sur la solvabilité','ca-ES':'Properament: Esborrany de contracte basat en solvència','eu-ES':'Laster: Kaudimenean oinarritutako kontratuaren zirriborroa','gl-ES':'Proximamente: Borrador de contrato baseado en solvencia' },
  'chat.search_hint': { 'en-US':'Search chats...','fr-FR':'Rechercher des chats...','ca-ES':'Cercar xats...','eu-ES':'Bilatu txatak...','gl-ES':'Buscar chats...' },
  'chat.no_conversations_desc': { 'en-US':'When you contact a seller or receive an offer, they will appear here.','fr-FR':'Lorsque vous contactez un vendeur ou recevez une offre, ils apparaîtront ici.','ca-ES':'Quan contactis amb un venedor o rebis una oferta, apareixeran aquí.','eu-ES':'Saltzaile batekin harremanetan jartzean edo eskaintza bat jasotzen duzunean, hemen agertuko dira.','gl-ES':'Cando contactes cun vendedor ou recibas unha oferta, aparecerán aquí.' },
  'chat.secure_conv_title': { 'en-US':'Secure Conversations','fr-FR':'Conversations Sécurisées','ca-ES':'Converses Segures','eu-ES':'Elkarrizketa Seguruak','gl-ES':'Conversas Seguras' },
  'chat.secure_conv_desc': { 'en-US':'On InmuFácil, your data is protected. Negotiate with peace of mind.','fr-FR':'Sur InmuFácil, vos données sont protégées. Négociez en toute tranquillité.','ca-ES':'A InmuFácil, les teves dades estan protegides. Negocia amb tranquil·litat.','eu-ES':'InmuFácil-en, zure datuak babestuta daude. Negoziatu lasai.','gl-ES':'En InmuFácil, os teus datos están protexidos. Negocia con tranquilidade.' },
  'chat.feature_p2p': { 'en-US':'P2P SECURE','fr-FR':'P2P SÉCURISÉ','ca-ES':'P2P SEGUR','eu-ES':'P2P SEGURUA','gl-ES':'P2P SEGURO' },
  'chat.feature_legal': { 'en-US':'LEGAL FRAMEWORK','fr-FR':'CADRE LÉGAL','ca-ES':'MARC LEGAL','eu-ES':'ESPARRU LEGALA','gl-ES':'MARCO LEGAL' },
  'chat.feature_kyc': { 'en-US':'KYC PROFILE','fr-FR':'PROFIL KYC','ca-ES':'PERFIL KYC','eu-ES':'KYC PROFILA','gl-ES':'PERFIL KYC' },
  'chat.trust_gold': { 'en-US':'GOLD','fr-FR':'OR','ca-ES':'OR','eu-ES':'URRE','gl-ES':'OURO' },
  'chat.trust_silver': { 'en-US':'SILVER','fr-FR':'ARGENT','ca-ES':'PLATA','eu-ES':'ZILAR','gl-ES':'PRATA' },
  'chat.trust_bronze': { 'en-US':'BRONZE','fr-FR':'BRONZE','ca-ES':'BRONZE','eu-ES':'BRONTZE','gl-ES':'BRONCE' },
  'chat.visit_time_help': { 'en-US':'Select the visit time','fr-FR':'Sélectionnez l\'heure de la visite','ca-ES':'Selecciona l\'hora de la visita','eu-ES':'Hautatu bisitaren ordua','gl-ES':'Selecciona a hora da visita' },
  'chat.offer_proposal_title': { 'en-US':'Offer Proposal','fr-FR':'Proposition d\'Offre','ca-ES':'Proposta d\'Oferta','eu-ES':'Eskaintza Proposamena','gl-ES':'Proposta de Oferta' },
  'chat.error_amount_required': { 'en-US':'You must enter an amount','fr-FR':'Vous devez indiquer un montant','ca-ES':'Has d\'indicar un import','eu-ES':'Zenbateko bat adierazi behar duzu','gl-ES':'Debes indicar un importe' },
  'chat.error_amount_invalid': { 'en-US':'Invalid amount','fr-FR':'Montant invalide','ca-ES':'Import no vàlid','eu-ES':'Zenbateko baliogabea','gl-ES':'Importe non válido' },
  'chat.offline': { 'en-US':'Offline','fr-FR':'Hors ligne','ca-ES':'Desconnectat','eu-ES':'Lineatik kanpo','gl-ES':'Desconectado' },
  'chat.solvency_not_completed': { 'en-US':'The buyer has not yet completed their solvency passport.','fr-FR':'L\'acheteur n\'a pas encore complété son passeport de solvabilité.','ca-ES':'El comprador encara no ha completat el seu passaport de solvència.','eu-ES':'Erosleak oraindik ez du kaudimenaren pasaportea osatu.','gl-ES':'O comprador aínda non completou o seu pasaporte de solvencia.' },
  'chat.tap_for_details': { 'en-US':'Tap to see financial details','fr-FR':'Appuyez pour voir les détails financiers','ca-ES':'Toca per veure detalls financers','eu-ES':'Sakatu xehetasun finantzarioak ikusteko','gl-ES':'Toca para ver detalles financeiros' },
  'chat.accept_solvency_btn': { 'en-US':'Accept Solvency and Reserve','fr-FR':'Accepter la Solvabilité et Réserver','ca-ES':'Acceptar Solvència i Reservar','eu-ES':'Kaudimena Onartu eta Erreserbatu','gl-ES':'Aceptar Solvencia e Reservar' },
  'chat.level_gold': { 'en-US':'Gold Level','fr-FR':'Niveau Or','ca-ES':'Nivell Or','eu-ES':'Urrezko Maila','gl-ES':'Nivel Ouro' },
  'chat.level_silver': { 'en-US':'Silver Level','fr-FR':'Niveau Argent','ca-ES':'Nivell Plata','eu-ES':'Zilarrezko Maila','gl-ES':'Nivel Prata' },
  'chat.level_bronze': { 'en-US':'Bronze Level','fr-FR':'Niveau Bronze','ca-ES':'Nivell Bronze','eu-ES':'Brontzezko Maila','gl-ES':'Nivel Bronce' },
  'chat.yesterday_caps': { 'en-US':'YESTERDAY','fr-FR':'HIER','ca-ES':'AHIR','eu-ES':'ATZO','gl-ES':'ONTE' },
  'chat.action_visit_cancelled': { 'en-US':'Visit Cancelled','fr-FR':'Visite Annulée','ca-ES':'Visita Cancel·lada','eu-ES':'Bisita Bertan Behera','gl-ES':'Visita Cancelada' },
  'chat.reject': { 'en-US':'Reject','fr-FR':'Rejeter','ca-ES':'Rebutjar','eu-ES':'Ukatu','gl-ES':'Rexeitar' },
  'chat.accept': { 'en-US':'Accept','fr-FR':'Accepter','ca-ES':'Acceptar','eu-ES':'Onartu','gl-ES':'Aceptar' },
  'chat.reschedule': { 'en-US':'Reschedule','fr-FR':'Reprogrammer','ca-ES':'Reprogramar','eu-ES':'Berrezarri','gl-ES':'Reprogramar' },
  'chat.cancel': { 'en-US':'Cancel','fr-FR':'Annuler','ca-ES':'Cancel·lar','eu-ES':'Bertan behera utzi','gl-ES':'Anular' },
  'chat.quick_visit': { 'en-US':'Visit','fr-FR':'Visite','ca-ES':'Visita','eu-ES':'Bisita','gl-ES':'Visita' },
  'chat.quick_offer': { 'en-US':'Offer','fr-FR':'Offre','ca-ES':'Oferta','eu-ES':'Eskaintza','gl-ES':'Oferta' },
  'chat.encryption_note': { 'en-US':'Your messages are protected by end-to-end encryption.','fr-FR':'Vos messages sont protégés par un chiffrement de bout en bout.','ca-ES':'Els teus missatges estan protegits per xifrat de extrem a extrem.','eu-ES':'Zure mezuak muturretik muturrerako enkriptazioaz babestuta daude.','gl-ES':'Os teus mensaxes están protexidos por cifrado de extremo a extremo.' },
  'chat.reference': { 'en-US':'REF: {title}','fr-FR':'RÉF : {title}','ca-ES':'REFERÈNCIA: {title}','eu-ES':'ERREFERENTZIA: {title}','gl-ES':'REFERENCIA: {title}' },
};

const langs = ['en-US','en-GB','en-CA','fr-FR','fr-CA','ca-ES','va-ES','eu-ES','gl-ES'];

langs.forEach(lang => {
  const fp = base + lang + '.json';
  const json = JSON.parse(fs.readFileSync(fp, 'utf8'));
  let count = 0;
  Object.entries(translations).forEach(([path, vals]) => {
    let src = lang;
    if (lang === 'en-GB' || lang === 'en-CA') src = 'en-US';
    if (lang === 'fr-CA') src = 'fr-FR';
    if (lang === 'va-ES') src = 'ca-ES';
    const val = vals[src] || vals['en-US'];
    if (val !== undefined) {
      setVal(json, path, val);
      count++;
    }
  });
  fs.writeFileSync(fp, JSON.stringify(json, null, 2), 'utf8');
  console.log(lang + ': updated ' + count + ' remaining keys');
});
