const fs = require('fs');
const base = 'frontend/assets/translations/';

function setVal(obj, path, val) {
  const parts = path.split('.');
  const last = parts.pop();
  const target = parts.reduce((o, k) => { if (!o[k]) o[k] = {}; return o[k]; }, obj);
  target[last] = val;
}

const tx = {
  'en-US': {
    fein_title: 'Bank Formalization (FEIN)',
    footer_legal: 'Legal',
    tasacion_info_title: 'Appraisal Process',
    tasacion_info_body: 'The appraisal is a critical step for the bank to approve the buyer\'s mortgage. It must be carried out by an entity approved by the Bank of Spain.',
    tasacion_checklist_seller: 'Seller Preparation',
    tasacion_checklist_buyer: 'Buyer Preparation',
    tasacion_checklist_1: 'Make sure you have the keys available',
    tasacion_checklist_2: 'The property must be accessible',
    tasacion_checklist_3: 'Have the deed or property registry extract on hand',
    tasacion_checklist_4: 'The process usually takes between 30 and 60 minutes',
    tasacion_schedule_title: 'Schedule Appointment',
    tasacion_schedule_subtitle: 'Propose a date and time for the appraiser to visit the property',
    tasacion_date_label: 'Visit date',
    tasacion_time_label: 'Approximate time',
    tasacion_select: 'Select',
    tasacion_notes_label: 'Additional notes (entrance, doorbell...)',
    tasacion_send_proposal: 'Send appointment proposal',
    tasacion_snack_proposed: 'Proposal sent to seller',
    tasacion_snack_accepted: 'Appointment confirmed successfully',
    tasacion_snack_rejected: 'Counter-proposal sent to buyer',
    tasacion_snack_counter_accepted: 'New date accepted successfully',
    tasacion_waiting_title: 'Waiting for buyer',
    tasacion_waiting_body: 'The buyer must propose a date for the appraiser\'s visit. We will notify you as soon as they do.',
    tasacion_proposed_badge: 'Appointment Proposed',
    tasacion_your_proposal: 'Your proposal',
    tasacion_proposed_hint: 'Waiting for the seller to confirm or propose another time.',
    tasacion_buyer_proposes: 'The buyer proposes an appointment',
    tasacion_proposed_date: 'Proposed date',
    tasacion_accept_date: 'Accept date and time',
    tasacion_cancel_label: 'Cancel',
    tasacion_reject_propose: 'Reject and propose another',
    tasacion_alt_title: 'Your counter-proposal',
    tasacion_alt_date: 'New suggested date',
    tasacion_alt_time: 'New suggested time',
    tasacion_alt_notes: 'Reason for change / notes',
    tasacion_send_counter: 'Send counter-proposal',
    tasacion_seller_counter_title: 'The seller proposes another date',
    tasacion_seller_counter_body: 'The seller is not available on the requested date and suggests the following schedule:',
    tasacion_seller_proposal: 'Seller\'s proposal',
    tasacion_propose_other: 'Propose a different date',
    tasacion_waiting_new_title: 'Waiting for response',
    tasacion_waiting_new_body: 'You have sent a counter-proposal. The buyer must accept it or propose a new one.',
    tasacion_confirmed: 'Appointment Confirmed!',
    tasacion_confirmed_at: 'The visit will be on {date} at {time}',
    tasacion_seller_confirm_hint: 'Please make sure to be present or provide access.',
    tasacion_buyer_confirm_hint: 'The appraiser will come on the agreed date.',
    tasacion_confirm_visit_title: 'Confirm Completion',
    tasacion_confirm_visit_body: 'Once the appraiser has visited the property, please confirm it to advance to the next step (FEIN).',
    tasacion_visit_done: 'Confirm that the visit has taken place',
    tasacion_completed: 'Appraisal Completed',
    tasacion_completed_seller: 'The appraiser\'s visit has been completed successfully.',
    tasacion_completed_buyer: 'The visit is complete. The next step is the issuance of the FEIN by the bank.',
    tasacion_goto_fein: 'Go to FEIN step',
    pv_seller_banner: 'Upload the latest bills and supporting documents to facilitate the change of ownership to the buyer.',
    pv_buyer_banner: 'Here you can download the documentation provided by the seller to process the name changes.',
    pv_all_done: 'You have completed the delivery of all documentation.',
    pv_snack_uploaded: 'Document uploaded successfully.',
    pv_error_upload: 'Error uploading the document.',
    pv_error_save: 'Error saving document status.',
    pv_snack_downloaded: 'Document downloaded successfully.',
    pv_error_download: 'Error downloading the document.',
    pv_uploading: 'Uploading...',
    pv_file_uploaded: 'File uploaded',
    pv_in_person: 'Delivered in person',
    pv_upload_btn: 'Upload File',
    pv_in_person_btn: 'Hand deliver',
    pv_not_applicable_btn: 'Not applicable',
    pv_download_btn: 'Download document',
    pv_doc_available: 'Document available',
    pv_in_person_badge: 'In person / Notary',
    pv_not_applicable_badge: 'Not applicable',
    pv_pending_seller: 'Pending from seller',
    pv_elec_label: 'Electricity',
    pv_elec_sub: 'Latest bill and CUPS code',
    pv_elec_na: 'No electricity contract',
    pv_water_label: 'Water',
    pv_water_sub: 'Latest bill or receipt',
    pv_water_na: 'No water contract',
    pv_gas_label: 'Gas',
    pv_gas_sub: 'Latest bill (if applicable)',
    pv_gas_na: 'No gas contract',
    pv_ibi_label: 'IBI (Property Tax)',
    pv_ibi_sub: 'Current year payment receipt',
    pv_ibi_na: 'IBI exempt',
    pv_comm_label: 'Community Fees',
    pv_comm_sub: 'Certificate of current payment',
    pv_comm_na: 'No community fees',
    pv_buyer_elec: 'Electricity Supply',
    pv_buyer_elec_sub: 'Steps to change the account holder',
    pv_buyer_elec_1: 'Locate the CUPS code on the bill.',
    pv_buyer_elec_2: 'Call your chosen electricity supplier.',
    pv_buyer_elec_3: 'Have the purchase deed on hand.',
    pv_buyer_elec_4: 'Provide your bank account for direct debits.',
    pv_buyer_water: 'Water Supply',
    pv_buyer_water_sub: 'Steps to register / change holder',
    pv_buyer_water_1: 'Identify the local water company.',
    pv_buyer_water_2: 'Provide the bulletin if it is a new connection.',
    pv_buyer_water_3: 'Present your ID and the deed.',
    pv_buyer_water_4: 'The process may take a few days.',
    pv_buyer_gas: 'Gas Supply',
    pv_buyer_gas_sub: 'Required procedures',
    pv_buyer_gas_1: 'Check if there is an active contract.',
    pv_buyer_gas_2: 'You will need the installation certificate.',
    pv_buyer_gas_3: 'Contact the local distributor.',
    pv_buyer_gas_4: 'Request a safety inspection.',
    pv_buyer_ibi: 'IBI and Local Taxes',
    pv_buyer_ibi_sub: 'Municipal administration',
    pv_buyer_ibi_1: 'Go to the town hall with the deed.',
    pv_buyer_ibi_2: 'Register the property in the land registry.',
    pv_buyer_ibi_3: 'Set up direct debit for the next payment.',
    pv_buyer_ibi_4: 'Check for any previous outstanding debts.',
    pv_buyer_comm: 'Owners\' Community',
    pv_buyer_comm_sub: 'Registration as owner',
    pv_buyer_comm_1: 'Contact the property manager.',
    pv_buyer_comm_2: 'Provide your contact details.',
    pv_buyer_comm_3: 'Share your bank account for fees.',
    pv_buyer_comm_4: 'Request the community bylaws.',
    fein_buyer_banner: 'Confirm that you have received the FEIN (European Standardised Information Sheet) from your bank.',
    fein_seller_banner: 'The buyer is arranging bank formalization. This process is mandatory before going to the notary.',
    fein_what_is: 'What is the FEIN?',
    fein_faq1_title: 'Mandatory',
    fein_faq1_body: 'It is the document detailing the final conditions of your mortgage.',
    fein_faq2_title: 'Timeline',
    fein_faq2_body: 'You must have it at least 10 days before signing at the notary.',
    fein_faq3_title: 'Next Step',
    fein_faq3_body: 'After confirming it, we will coordinate the notary appointment.',
    fein_process_title: 'Steps to the Notary',
    fein_step1_title: 'Appraisal Completed',
    fein_step1_body: 'The property has already been valued by the bank.',
    fein_step2_title: 'Binding Offer',
    fein_step2_body: 'The bank issues the FEIN and the draft contract.',
    fein_step3_title: 'App Confirmation',
    fein_step3_body: 'You confirm that you have the necessary documentation.',
    fein_step4_title: 'Prior Act',
    fein_step4_body: 'Visit to the notary to resolve queries.',
    fein_step5_title: 'Sign Deed',
    fein_step5_body: 'Final signature and key handover.',
    fein_form_title: 'Confirm Receipt',
    fein_check1: 'I have received the FEIN and FIPER from my bank.',
    fein_check2: 'I have read and understood the loan conditions.',
    fein_form_warn: 'This confirmation indicates that you are ready to move on to the notary phase. It is not a legal contract, but it advances the process in InmuFácil.',
    fein_seller_wait_title: 'Waiting for Formalization',
    fein_seller_wait_body: 'The buyer must confirm that they have the FEIN. We will notify you when this happens.',
    fein_success_title: 'Formalization Confirmed!',
    fein_success_buyer: 'You have confirmed receipt of the FEIN. We can now proceed to choose a notary.',
    fein_success_seller: 'The buyer has confirmed bank formalization. We are ready to coordinate the notary.',
    fein_success_warn: 'Remember that at least 10 days must pass between the issuance of the FEIN and the signing.',
    fein_goto_notary: 'Go to Notary',
    fein_back_timeline: 'Back to timeline',
    keys_confirm_wait_snack: 'Confirmation registered. Waiting for the other party\'s confirmation.',
    keys_confirm_error: 'Error confirming key handover.',
    keys_completed_title: 'Transaction Completed!',
    keys_completed_desc: 'Both parties have confirmed the key handover. The purchase transaction in InmuFácil has been completed successfully.',
    keys_accept: 'Got it',
    keys_delivered_title: 'Key Handover',
    keys_pending_title: 'Handover Pending',
    keys_delivered_desc: 'Possession of the property has been formally transferred.',
    keys_pending_desc: 'Both parties must confirm the key handover after signing at the notary.',
    keys_seller: 'Seller',
    keys_buyer: 'Buyer',
    keys_confirmed: 'Handover confirmed',
    keys_confirm_prompt: 'Please confirm that you have completed the handover.',
    keys_waiting_confirm: 'Waiting for confirmation',
    keys_confirm_btn: 'Confirm Handover',
    keys_doc1: 'Complete set of keys (property, mailbox, storage room)',
    keys_doc2: 'Energy Performance Certificate (original)',
    keys_doc3: 'Certificate of Habitability (if applicable)',
    keys_doc4: 'Latest IBI and utility bills paid',
    keys_doc5: 'Certificate of being up to date with community fees',
    keys_doc6: 'Appliance manuals and warranties',
    keys_tips_title: 'Final tips',
    keys_tip1: 'Take photos of the meter readings (electricity, water, gas).',
    keys_tip2: 'Change the utility account holders as soon as possible.',
    keys_tip3: 'Change the main lock cylinder for security.',
    keys_tip4: 'Notify your bank and home insurance of the sale.',
    notary_close_title: 'Notary Closing',
    notary_buyer_desc: 'Confirm that the public purchase deed has been signed and the keys have been received.',
    notary_seller_desc: 'Confirm that the deed has been signed and the keys have been handed over to the new owner.',
    notary_status_title: 'Confirmation Status',
    notary_your_confirm_buyer: 'Your confirmation (Buyer)',
    notary_your_confirm_seller: 'Your confirmation (Seller)',
    notary_other_confirm_seller: 'Seller\'s confirmation',
    notary_other_confirm_buyer: 'Buyer\'s confirmation',
    notary_declare_title: 'Sworn Declaration',
    notary_declare_signed: 'I declare that the notary signing has been completed correctly.',
    notary_declare_keys_buyer: 'I have received all the keys to the property.',
    notary_declare_keys_seller: 'I have handed over all the keys to the buyer.',
    notary_declare_warning: 'This action is irreversible and marks the end of the purchase phase in InmuFácil.',
    notary_confirm_btn: 'Confirm Signing and Handover',
    notary_success_title: 'Congratulations!',
    notary_success_buyer: 'The purchase has been officially completed. You can now access post-sale management.',
    notary_success_seller: 'The sale has been officially completed. Thank you for trusting InmuFácil.',
    notary_go_post_venta: 'Go to Post-Sale',
    notary_pending: 'Pending',
    notary_confirmed: 'Confirmed',
    notaria_subtitle: 'Milestone 8 of 9 — Notary appointment and key handover',
    tasacion_app_bar_title: 'Property Appraisal',
    tasacion_appointment_format: '{day}/{month}/{year}  ·  {time}',
    fein_notes_confirm: 'FEIN confirmation from the app.',
    keys_docs_delivery: 'Documentation to hand over',
    pv_not_applicable_label: 'Not applicable',
  },
  'fr-FR': {
    fein_title: 'Formalisation Bancaire (FEIN)',
    footer_legal: 'Mentions légales',
    tasacion_info_title: 'Processus d\'Expertise',
    tasacion_info_body: 'L\'expertise est une étape critique pour que la banque approuve le prêt hypothécaire de l\'acheteur. Elle doit être réalisée par un organisme agréé par la Banque d\'Espagne.',
    tasacion_checklist_seller: 'Préparation du Vendeur',
    tasacion_checklist_buyer: 'Préparation de l\'Acheteur',
    tasacion_checklist_1: 'Assurez-vous d\'avoir les clés disponibles',
    tasacion_checklist_2: 'Le logement doit être accessible',
    tasacion_checklist_3: 'Ayez l\'acte ou l\'extrait du registre foncier à portée de main',
    tasacion_checklist_4: 'Le processus dure généralement entre 30 et 60 minutes',
    tasacion_schedule_title: 'Planifier un Rendez-vous',
    tasacion_schedule_subtitle: 'Proposez une date et une heure pour que l\'expert visite le bien',
    tasacion_date_label: 'Date de visite',
    tasacion_time_label: 'Heure approximative',
    tasacion_select: 'Sélectionner',
    tasacion_notes_label: 'Notes supplémentaires (entrée, interphone...)',
    tasacion_send_proposal: 'Envoyer la proposition de rendez-vous',
    tasacion_snack_proposed: 'Proposition envoyée au vendeur',
    tasacion_snack_accepted: 'Rendez-vous confirmé avec succès',
    tasacion_snack_rejected: 'Contre-proposition envoyée à l\'acheteur',
    tasacion_snack_counter_accepted: 'Nouvelle date acceptée avec succès',
    tasacion_waiting_title: 'En attente de l\'acheteur',
    tasacion_waiting_body: 'L\'acheteur doit proposer une date pour la visite de l\'expert. Nous vous notifierons dès qu\'il le fera.',
    tasacion_proposed_badge: 'Rendez-vous Proposé',
    tasacion_your_proposal: 'Votre proposition',
    tasacion_proposed_hint: 'En attente que le vendeur confirme ou propose un autre horaire.',
    tasacion_buyer_proposes: 'L\'acheteur propose un rendez-vous',
    tasacion_proposed_date: 'Date proposée',
    tasacion_accept_date: 'Accepter la date et l\'heure',
    tasacion_cancel_label: 'Annuler',
    tasacion_reject_propose: 'Refuser et proposer une autre',
    tasacion_alt_title: 'Votre contre-proposition',
    tasacion_alt_date: 'Nouvelle date suggérée',
    tasacion_alt_time: 'Nouvel horaire suggéré',
    tasacion_alt_notes: 'Motif du changement / notes',
    tasacion_send_counter: 'Envoyer la contre-proposition',
    tasacion_seller_counter_title: 'Le vendeur propose une autre date',
    tasacion_seller_counter_body: 'Le vendeur n\'est pas disponible à la date demandée et suggère le créneau suivant :',
    tasacion_seller_proposal: 'Proposition du vendeur',
    tasacion_propose_other: 'Proposer une autre date',
    tasacion_waiting_new_title: 'En attente de réponse',
    tasacion_waiting_new_body: 'Vous avez envoyé une contre-proposition. L\'acheteur doit l\'accepter ou en proposer une nouvelle.',
    tasacion_confirmed: 'Rendez-vous Confirmé !',
    tasacion_confirmed_at: 'La visite aura lieu le {date} à {time}',
    tasacion_seller_confirm_hint: 'Veuillez vous assurer d\'être présent ou de faciliter l\'accès.',
    tasacion_buyer_confirm_hint: 'L\'expert se rendra sur place à la date convenue.',
    tasacion_confirm_visit_title: 'Confirmer la Réalisation',
    tasacion_confirm_visit_body: 'Une fois que l\'expert a visité le bien, veuillez le confirmer pour passer à l\'étape suivante (FEIN).',
    tasacion_visit_done: 'Confirmer que la visite a eu lieu',
    tasacion_completed: 'Expertise Réalisée',
    tasacion_completed_seller: 'La visite de l\'expert s\'est déroulée avec succès.',
    tasacion_completed_buyer: 'La visite est terminée. La prochaine étape est l\'émission de la FEIN par la banque.',
    tasacion_goto_fein: 'Aller à l\'étape FEIN',
    pv_seller_banner: 'Téléversez les dernières factures et justificatifs pour faciliter le transfert de propriété à l\'acheteur.',
    pv_buyer_banner: 'Vous pouvez télécharger ici les documents fournis par le vendeur pour traiter les changements de titulaire.',
    pv_all_done: 'Vous avez terminé la remise de toute la documentation.',
    pv_snack_uploaded: 'Document téléversé avec succès.',
    pv_error_upload: 'Erreur lors du téléversement du document.',
    pv_error_save: 'Erreur lors de la sauvegarde du statut du document.',
    pv_snack_downloaded: 'Document téléchargé avec succès.',
    pv_error_download: 'Erreur lors du téléchargement du document.',
    pv_uploading: 'Téléversement...',
    pv_file_uploaded: 'Fichier téléversé',
    pv_in_person: 'Remis en personne',
    pv_upload_btn: 'Téléverser un fichier',
    pv_in_person_btn: 'Remettre en main propre',
    pv_not_applicable_btn: 'Non applicable',
    pv_download_btn: 'Télécharger le document',
    pv_doc_available: 'Document disponible',
    pv_in_person_badge: 'En main propre / Notaire',
    pv_not_applicable_badge: 'Non applicable',
    pv_pending_seller: 'En attente du vendeur',
    pv_elec_label: 'Électricité',
    pv_elec_sub: 'Dernière facture et code CUPS',
    pv_elec_na: 'Pas de contrat d\'électricité',
    pv_water_label: 'Eau',
    pv_water_sub: 'Dernière facture ou reçu',
    pv_water_na: 'Pas de contrat d\'eau',
    pv_gas_label: 'Gaz',
    pv_gas_sub: 'Dernière facture (si applicable)',
    pv_gas_na: 'Pas de contrat de gaz',
    pv_ibi_label: 'IBI (Taxe Foncière)',
    pv_ibi_sub: 'Justificatif de paiement de l\'année en cours',
    pv_ibi_na: 'Exonéré d\'IBI',
    pv_comm_label: 'Charges de Copropriété',
    pv_comm_sub: 'Certificat de paiement à jour',
    pv_comm_na: 'Pas de charges de copropriété',
    pv_buyer_elec: 'Alimentation Électrique',
    pv_buyer_elec_sub: 'Étapes pour changer le titulaire du contrat',
    pv_buyer_elec_1: 'Localisez le code CUPS sur la facture.',
    pv_buyer_elec_2: 'Appelez le fournisseur d\'électricité choisi.',
    pv_buyer_elec_3: 'Ayez l\'acte de vente à portée de main.',
    pv_buyer_elec_4: 'Indiquez votre compte bancaire pour les prélèvements.',
    pv_buyer_water: 'Alimentation en Eau',
    pv_buyer_water_sub: 'Étapes pour l\'inscription / changement de titulaire',
    pv_buyer_water_1: 'Identifiez la société d\'eau municipale.',
    pv_buyer_water_2: 'Fournissez le bulletin si c\'est un nouveau branchement.',
    pv_buyer_water_3: 'Présentez votre pièce d\'identité et l\'acte.',
    pv_buyer_water_4: 'Le processus peut prendre quelques jours.',
    pv_buyer_gas: 'Alimentation en Gaz',
    pv_buyer_gas_sub: 'Démarches nécessaires',
    pv_buyer_gas_1: 'Vérifiez s\'il existe un contrat actif.',
    pv_buyer_gas_2: 'Vous aurez besoin du certificat d\'installation.',
    pv_buyer_gas_3: 'Contactez le distributeur de la zone.',
    pv_buyer_gas_4: 'Demandez une inspection de sécurité.',
    pv_buyer_ibi: 'IBI et Taxes Locales',
    pv_buyer_ibi_sub: 'Administration municipale',
    pv_buyer_ibi_1: 'Rendez-vous à la mairie avec l\'acte de vente.',
    pv_buyer_ibi_2: 'Inscrivez le bien au registre cadastral.',
    pv_buyer_ibi_3: 'Domiciliez le prochain paiement.',
    pv_buyer_ibi_4: 'Vérifiez les éventuelles dettes antérieures.',
    pv_buyer_comm: 'Copropriété',
    pv_buyer_comm_sub: 'Enregistrement en tant que propriétaire',
    pv_buyer_comm_1: 'Contactez le syndic.',
    pv_buyer_comm_2: 'Fournissez vos coordonnées.',
    pv_buyer_comm_3: 'Communiquez votre compte bancaire pour les charges.',
    pv_buyer_comm_4: 'Demandez les statuts de la copropriété.',
    fein_buyer_banner: 'Confirmez que vous avez reçu la FEIN (Fiche Européenne d\'Information Normalisée) de votre banque.',
    fein_seller_banner: 'L\'acheteur est en train de gérer la formalisation bancaire. Ce processus est obligatoire avant de se rendre chez le notaire.',
    fein_what_is: 'Qu\'est-ce que la FEIN ?',
    fein_faq1_title: 'Obligatoire',
    fein_faq1_body: 'C\'est le document qui détaille les conditions définitives de votre prêt hypothécaire.',
    fein_faq2_title: 'Délai',
    fein_faq2_body: 'Vous devez l\'avoir au moins 10 jours avant la signature chez le notaire.',
    fein_faq3_title: 'Étape suivante',
    fein_faq3_body: 'Après confirmation, nous coordonnerons le rendez-vous chez le notaire.',
    fein_process_title: 'Étapes jusqu\'au Notaire',
    fein_step1_title: 'Expertise Terminée',
    fein_step1_body: 'Le bien a déjà été évalué par la banque.',
    fein_step2_title: 'Offre Contraignante',
    fein_step2_body: 'La banque émet la FEIN et le projet de contrat.',
    fein_step3_title: 'Confirmation sur l\'App',
    fein_step3_body: 'Vous indiquez que vous disposez des documents nécessaires.',
    fein_step4_title: 'Acte Préalable',
    fein_step4_body: 'Visite chez le notaire pour résoudre les questions.',
    fein_step5_title: 'Signature de l\'Acte',
    fein_step5_body: 'Signature finale et remise des clés.',
    fein_form_title: 'Confirmer la Réception',
    fein_check1: 'J\'ai reçu la FEIN et la FIPER de ma banque.',
    fein_check2: 'J\'ai lu et compris les conditions du prêt.',
    fein_form_warn: 'Cette confirmation indique que vous êtes prêt à passer à la phase notariale. Ce n\'est pas un contrat légal, mais cela fait avancer le processus dans InmuFácil.',
    fein_seller_wait_title: 'En Attente de Formalisation',
    fein_seller_wait_body: 'L\'acheteur doit confirmer qu\'il dispose de la FEIN. Nous vous informerons lorsque cela se produit.',
    fein_success_title: 'Formalisation Confirmée !',
    fein_success_buyer: 'Vous avez confirmé la réception de la FEIN. Nous pouvons maintenant procéder au choix du notaire.',
    fein_success_seller: 'L\'acheteur a confirmé la formalisation bancaire. Nous sommes prêts à coordonner le notaire.',
    fein_success_warn: 'Rappel : au moins 10 jours doivent s\'écouler entre l\'émission de la FEIN et la signature.',
    fein_goto_notary: 'Aller au Notaire',
    fein_back_timeline: 'Retour à la chronologie',
    keys_confirm_wait_snack: 'Confirmation enregistrée. En attente de confirmation de l\'autre partie.',
    keys_confirm_error: 'Erreur lors de la confirmation de remise des clés.',
    keys_completed_title: 'Transaction Finalisée !',
    keys_completed_desc: 'Les deux parties ont confirmé la remise des clés. La transaction d\'achat dans InmuFácil a été complétée avec succès.',
    keys_accept: 'Compris',
    keys_delivered_title: 'Remise des Clés',
    keys_pending_title: 'Remise en Attente',
    keys_delivered_desc: 'La possession du bien a été formellement transférée.',
    keys_pending_desc: 'Les deux parties doivent confirmer la remise des clés après la signature chez le notaire.',
    keys_seller: 'Vendeur',
    keys_buyer: 'Acheteur',
    keys_confirmed: 'Remise confirmée',
    keys_confirm_prompt: 'Veuillez confirmer que vous avez effectué la remise.',
    keys_waiting_confirm: 'En attente de confirmation',
    keys_confirm_btn: 'Confirmer la Remise',
    keys_doc1: 'Jeu complet de clés (logement, boîte aux lettres, débarras)',
    keys_doc2: 'Certificat de Performance Énergétique (original)',
    keys_doc3: 'Certificat d\'Habitabilité (si applicable)',
    keys_doc4: 'Dernières factures d\'IBI et de fournitures payées',
    keys_doc5: 'Certificat de régularité des charges de copropriété',
    keys_doc6: 'Manuels et garanties des appareils électroménagers',
    keys_tips_title: 'Conseils finaux',
    keys_tip1: 'Prenez des photos des relevés de compteurs (électricité, eau, gaz).',
    keys_tip2: 'Effectuez le changement de titulaire des fournitures dès que possible.',
    keys_tip3: 'Changez le cylindre de la serrure principale pour votre sécurité.',
    keys_tip4: 'Informez votre banque et votre assurance habitation de la vente.',
    notary_close_title: 'Clôture Notariale',
    notary_buyer_desc: 'Confirmez que l\'acte de vente public a été signé et que les clés ont été reçues.',
    notary_seller_desc: 'Confirmez que l\'acte a été signé et que les clés ont été remises au nouveau propriétaire.',
    notary_status_title: 'État des Confirmations',
    notary_your_confirm_buyer: 'Votre confirmation (Acheteur)',
    notary_your_confirm_seller: 'Votre confirmation (Vendeur)',
    notary_other_confirm_seller: 'Confirmation du Vendeur',
    notary_other_confirm_buyer: 'Confirmation de l\'Acheteur',
    notary_declare_title: 'Déclaration Sous Serment',
    notary_declare_signed: 'Je déclare que la signature chez le notaire s\'est déroulée correctement.',
    notary_declare_keys_buyer: 'J\'ai reçu toutes les clés du logement.',
    notary_declare_keys_seller: 'J\'ai remis toutes les clés à l\'acheteur.',
    notary_declare_warning: 'Cette action est irréversible et marque la fin de la phase d\'achat dans InmuFácil.',
    notary_confirm_btn: 'Confirmer la Signature et la Remise',
    notary_success_title: 'Félicitations !',
    notary_success_buyer: 'L\'achat a été officiellement complété. Vous pouvez maintenant accéder à la gestion post-vente.',
    notary_success_seller: 'La vente a été officiellement complétée. Merci de faire confiance à InmuFácil.',
    notary_go_post_venta: 'Aller à l\'Après-Vente',
    notary_pending: 'En attente',
    notary_confirmed: 'Confirmé',
    notaria_subtitle: 'Étape 8 sur 9 — Rendez-vous notarial et remise des clés',
    tasacion_app_bar_title: 'Expertise Immobilière',
    tasacion_appointment_format: '{day}/{month}/{year}  ·  {time}',
    fein_notes_confirm: 'Confirmation FEIN depuis l\'application.',
    keys_docs_delivery: 'Documentation à remettre',
    pv_not_applicable_label: 'Non applicable',
  },
  'ca-ES': {
    fein_title: 'Formalització Bancària (FEIN)',
    footer_legal: 'Legal',
    tasacion_info_title: 'Procés de Taxació',
    tasacion_info_body: 'La taxació és un pas crític perquè el banc aprovi la hipoteca del comprador. Ha de ser realitzada per una entitat homologada pel Banc d\'Espanya.',
    tasacion_checklist_seller: 'Preparació per al Venedor',
    tasacion_checklist_buyer: 'Preparació per al Comprador',
    tasacion_checklist_1: 'Assegura\'t de tenir les claus disponibles',
    tasacion_checklist_2: 'El habitatge ha d\'estar accessible',
    tasacion_checklist_3: 'Tingues a mà l\'escriptura o nota simple',
    tasacion_checklist_4: 'El procés sol durar entre 30 i 60 minuts',
    tasacion_schedule_title: 'Concertar Cita',
    tasacion_schedule_subtitle: 'Proposa una data i hora perquè el taxador visiti l\'habitatge',
    tasacion_date_label: 'Data de la visita',
    tasacion_time_label: 'Hora aproximada',
    tasacion_select: 'Seleccionar',
    tasacion_notes_label: 'Notes addicionals (portal, timbre...)',
    tasacion_send_proposal: 'Enviar proposta de cita',
    tasacion_snack_proposed: 'Proposta enviada al venedor',
    tasacion_snack_accepted: 'Cita confirmada correctament',
    tasacion_snack_rejected: 'Contraoferta enviada al comprador',
    tasacion_snack_counter_accepted: 'Nova data acceptada correctament',
    tasacion_waiting_title: 'Esperant el comprador',
    tasacion_waiting_body: 'El comprador ha de proposar una data per a la visita del taxador. T\'avisarem quan ho faci.',
    tasacion_proposed_badge: 'Cita Proposada',
    tasacion_your_proposal: 'La teva proposta',
    tasacion_proposed_hint: 'Esperant que el venedor confirmi o proposi una altra hora.',
    tasacion_buyer_proposes: 'El comprador proposa una cita',
    tasacion_proposed_date: 'Data proposada',
    tasacion_accept_date: 'Acceptar data i hora',
    tasacion_cancel_label: 'Cancel·lar',
    tasacion_reject_propose: 'Rebutjar i proposar una altra',
    tasacion_alt_title: 'La teva contraproposta',
    tasacion_alt_date: 'Nova data suggerida',
    tasacion_alt_time: 'Nova hora suggerida',
    tasacion_alt_notes: 'Motiu del canvi / notes',
    tasacion_send_counter: 'Enviar contraproposta',
    tasacion_seller_counter_title: 'El venedor proposa una altra data',
    tasacion_seller_counter_body: 'El venedor no pot en la data sol·licitada i suggereix el següent horari:',
    tasacion_seller_proposal: 'Proposta del venedor',
    tasacion_propose_other: 'Proposar una altra data',
    tasacion_waiting_new_title: 'Esperant resposta',
    tasacion_waiting_new_body: 'Has enviat una contraproposta. El comprador l\'ha d\'acceptar o proposar-ne una de nova.',
    tasacion_confirmed: 'Cita Confirmada!',
    tasacion_confirmed_at: 'La visita serà el {date} a les {time}',
    tasacion_seller_confirm_hint: 'Si us plau, assegura\'t d\'estar present o facilitar l\'accés.',
    tasacion_buyer_confirm_hint: 'El taxador acudirà a la data acordada.',
    tasacion_confirm_visit_title: 'Confirmar Realització',
    tasacion_confirm_visit_body: 'Un cop el taxador hagi visitat l\'habitatge, si us plau confirma-ho per avançar al pas següent (FEIN).',
    tasacion_visit_done: 'Confirmar que la visita s\'ha realitzat',
    tasacion_completed: 'Taxació Realitzada',
    tasacion_completed_seller: 'La visita del taxador s\'ha completat correctament.',
    tasacion_completed_buyer: 'La visita s\'ha completat. El pas següent és l\'emissió del FEIN per part del banc.',
    tasacion_goto_fein: 'Anar al pas del FEIN',
    pv_seller_banner: 'Puja les últimes factures i justificants per facilitar el canvi de titularitat al comprador.',
    pv_buyer_banner: 'Aquí pots descarregar la documentació facilitada pel venedor per tramitar els canvis de nom.',
    pv_all_done: 'Has completat el lliurament de tota la documentació.',
    pv_snack_uploaded: 'Document pujat correctament.',
    pv_error_upload: 'Error en pujar el document.',
    pv_error_save: 'Error en desar l\'estat del document.',
    pv_snack_downloaded: 'Document descarregat amb èxit.',
    pv_error_download: 'Error en descarregar el document.',
    pv_uploading: 'Pujant...',
    pv_file_uploaded: 'Arxiu pujat',
    pv_in_person: 'Lliurat en persona',
    pv_upload_btn: 'Pujar Arxiu',
    pv_in_person_btn: 'Lliurar en mà',
    pv_not_applicable_btn: 'No aplica',
    pv_download_btn: 'Descarregar document',
    pv_doc_available: 'Document disponible',
    pv_in_person_badge: 'En mà / Notaria',
    pv_not_applicable_badge: 'No aplica',
    pv_pending_seller: 'Pendent del venedor',
    pv_elec_label: 'Electricitat',
    pv_elec_sub: 'Última factura i codi CUPS',
    pv_elec_na: 'No hi ha contracte de llum',
    pv_water_label: 'Aigua',
    pv_water_sub: 'Última factura o rebut',
    pv_water_na: 'No hi ha contracte d\'aigua',
    pv_gas_label: 'Gas',
    pv_gas_sub: 'Última factura (si aplica)',
    pv_gas_na: 'No hi ha contracte de gas',
    pv_ibi_label: 'IBI',
    pv_ibi_sub: 'Justificant de pagament de l\'any en curs',
    pv_ibi_na: 'Exempt d\'IBI',
    pv_comm_label: 'Comunitat',
    pv_comm_sub: 'Certificat de pagament al corrent',
    pv_comm_na: 'No hi ha comunitat',
    pv_buyer_elec: 'Subministrament Elèctric',
    pv_buyer_elec_sub: 'Passos per al canvi de titular',
    pv_buyer_elec_1: 'Localitza el codi CUPS a la factura.',
    pv_buyer_elec_2: 'Truca a la comercialitzadora triada.',
    pv_buyer_elec_3: 'Tingues a mà l\'escriptura de compravenda.',
    pv_buyer_elec_4: 'Indica el teu compte bancari per als rebuts.',
    pv_buyer_water: 'Subministrament d\'Aigua',
    pv_buyer_water_sub: 'Passos per a l\'alta/canvi',
    pv_buyer_water_1: 'Identifica l\'empresa municipal d\'aigua.',
    pv_buyer_water_2: 'Aporta el butlletí si l\'alta és nova.',
    pv_buyer_water_3: 'Presenta el DNI i l\'escriptura.',
    pv_buyer_water_4: 'El procés pot trigar uns dies.',
    pv_buyer_gas: 'Subministrament de Gas',
    pv_buyer_gas_sub: 'Tràmits necessaris',
    pv_buyer_gas_1: 'Verifica si hi ha contracte actiu.',
    pv_buyer_gas_2: 'Necessitaràs el certificat d\'instal·lació.',
    pv_buyer_gas_3: 'Contacta amb la distribuïdora de la zona.',
    pv_buyer_gas_4: 'Sol·licita una revisió de seguretat.',
    pv_buyer_ibi: 'IBI i Taxes',
    pv_buyer_ibi_sub: 'Gestió municipal',
    pv_buyer_ibi_1: 'Acudeix a l\'ajuntament amb l\'escriptura.',
    pv_buyer_ibi_2: 'Inscriu la propietat al cadastre.',
    pv_buyer_ibi_3: 'Domicilia el proper rebut.',
    pv_buyer_ibi_4: 'Comprova els possibles deutes anteriors.',
    pv_buyer_comm: 'Comunitat de Propietaris',
    pv_buyer_comm_sub: 'Alta com a propietari',
    pv_buyer_comm_1: 'Contacta amb l\'administrador.',
    pv_buyer_comm_2: 'Facilita les teves dades de contacte.',
    pv_buyer_comm_3: 'Informa el teu compte per a les quotes.',
    pv_buyer_comm_4: 'Sol·licita els estatuts de la finca.',
    fein_buyer_banner: 'Confirma que has rebut la FEIN (Fitxa Europea d\'Informació Normalitzada) de la teva entitat bancària.',
    fein_seller_banner: 'El comprador està gestionant la formalització bancària. Aquest procés és obligatori abans d\'acudir a notaria.',
    fein_what_is: 'Què és la FEIN?',
    fein_faq1_title: 'Obligatori',
    fein_faq1_body: 'És el document que detalla les condicions definitives de la teva hipoteca.',
    fein_faq2_title: 'Termini',
    fein_faq2_body: 'L\'has de tenir almenys 10 dies abans de la signatura a notaria.',
    fein_faq3_title: 'Següent pas',
    fein_faq3_body: 'Després de confirmar-la, coordinarem la cita amb el notari.',
    fein_process_title: 'Passos fins a la Notaria',
    fein_step1_title: 'Taxació Completada',
    fein_step1_body: 'L\'habitatge ja ha estat valorat pel banc.',
    fein_step2_title: 'Oferta Vinculant',
    fein_step2_body: 'El banc emet la FEIN i l\'esborrany del contracte.',
    fein_step3_title: 'Confirmació a l\'App',
    fein_step3_body: 'Indiques que tens la documentació necessària.',
    fein_step4_title: 'Acta Prèvia',
    fein_step4_body: 'Visita al notari per resoldre dubtes.',
    fein_step5_title: 'Signatura d\'Escriptura',
    fein_step5_body: 'Signatura final i lliurament de claus.',
    fein_form_title: 'Confirmar Recepció',
    fein_check1: 'He rebut la FEIN i el FIPER del meu banc.',
    fein_check2: 'He llegit i comprès les condicions del préstec.',
    fein_form_warn: 'Aquesta confirmació indica que estàs llest per passar a la fase de notaria. No és un contracte legal, però avança el procés a InmuFácil.',
    fein_seller_wait_title: 'Esperant Formalització',
    fein_seller_wait_body: 'El comprador ha de confirmar que ja disposa de la FEIN. T\'avisarem quan passi.',
    fein_success_title: 'Formalització Confirmada!',
    fein_success_buyer: 'Has confirmat la recepció de la FEIN. Ara podem procedir a l\'elecció de notaria.',
    fein_success_seller: 'El comprador ha confirmat la formalització bancària. Estem a punt per coordinar la notaria.',
    fein_success_warn: 'Recorda que han de passar almenys 10 dies des de l\'emissió de la FEIN fins a la signatura.',
    fein_goto_notary: 'Anar a Notaria',
    fein_back_timeline: 'Tornar a la línia de temps',
    keys_confirm_wait_snack: 'Confirmació registrada. Esperant la confirmació de l\'altra part.',
    keys_confirm_error: 'Error en confirmar el lliurament de claus.',
    keys_completed_title: 'Transacció Finalitzada!',
    keys_completed_desc: 'Ambdues parts han confirmat el lliurament de claus. La compravenda a InmuFácil s\'ha completat amb èxit.',
    keys_accept: 'Entès',
    keys_delivered_title: 'Lliurament de Claus',
    keys_pending_title: 'Lliurament Pendent',
    keys_delivered_desc: 'La possessió de l\'habitatge ha estat transferida formalment.',
    keys_pending_desc: 'Ambdues parts han de confirmar el lliurament de claus després de la signatura a notaria.',
    keys_seller: 'Venedor',
    keys_buyer: 'Comprador',
    keys_confirmed: 'Lliurament confirmat',
    keys_confirm_prompt: 'Si us plau, confirma que has realitzat el lliurament.',
    keys_waiting_confirm: 'Esperant confirmació',
    keys_confirm_btn: 'Confirmar Lliurament',
    keys_doc1: 'Joc complet de claus (habitatge, bústia, traster)',
    keys_doc2: 'Certificat d\'Eficiència Energètica (original)',
    keys_doc3: 'Cèdula d\'Habitabilitat (si aplica)',
    keys_doc4: 'Últims rebuts d\'IBI i subministraments pagats',
    keys_doc5: 'Certificat d\'estar al corrent amb la comunitat',
    keys_doc6: 'Manuals i garanties d\'electrodomèstics',
    keys_tips_title: 'Consells finals',
    keys_tip1: 'Fes fotos de l\'estat dels comptadors (llum, aigua, gas).',
    keys_tip2: 'Realitza el canvi de titularitat dels subministraments com més aviat millor.',
    keys_tip3: 'Canvia el bombí del pany principal per seguretat.',
    keys_tip4: 'Comunica la venda a la teva entitat bancària i assegurança de la llar.',
    notary_close_title: 'Tancament a Notaria',
    notary_buyer_desc: 'Confirma que s\'ha signat l\'escriptura pública de compravenda i s\'han rebut les claus.',
    notary_seller_desc: 'Confirma que s\'ha signat l\'escriptura i s\'han lliurat les claus al nou propietari.',
    notary_status_title: 'Estat de les Confirmacions',
    notary_your_confirm_buyer: 'La teva confirmació (Comprador)',
    notary_your_confirm_seller: 'La teva confirmació (Venedor)',
    notary_other_confirm_seller: 'Confirmació del Venedor',
    notary_other_confirm_buyer: 'Confirmació del Comprador',
    notary_declare_title: 'Declaració Jurada',
    notary_declare_signed: 'Declaro que la signatura davant de notari s\'ha realitzat correctament.',
    notary_declare_keys_buyer: 'He rebut totes les claus de l\'habitatge.',
    notary_declare_keys_seller: 'He lliurat totes les claus al comprador.',
    notary_declare_warning: 'Aquesta acció és irreversible i marca el final de la fase de compravenda a InmuFácil.',
    notary_confirm_btn: 'Confirmar Signatura i Lliurament',
    notary_success_title: 'Enhorabona!',
    notary_success_buyer: 'La compra s\'ha completat oficialment. Ja pots accedir a la gestió post-venda.',
    notary_success_seller: 'La venda s\'ha completat oficialment. Gràcies per confiar en InmuFácil.',
    notary_go_post_venta: 'Anar a Post-Venda',
    notary_pending: 'Pendent',
    notary_confirmed: 'Confirmat',
    notaria_subtitle: 'Fita 8 de 9 — Cita notarial i lliurament de claus',
    tasacion_app_bar_title: 'Taxació de l\'Habitatge',
    tasacion_appointment_format: '{day}/{month}/{year}  ·  {time}',
    fein_notes_confirm: 'Confirmació de FEIN des de l\'app.',
    keys_docs_delivery: 'Documentació a lliurar',
    pv_not_applicable_label: 'No aplica',
  },
  'gl-ES': {
    fein_title: 'Formalización Bancaria (FEIN)',
    footer_legal: 'Legal',
    tasacion_info_title: 'Proceso de Taxación',
    tasacion_info_body: 'A taxación é un paso crítico para que o banco aprobe a hipoteca do comprador. Debe ser realizada por unha entidade homologada polo Banco de España.',
    tasacion_checklist_seller: 'Preparación para o Vendedor',
    tasacion_checklist_buyer: 'Preparación para o Comprador',
    tasacion_checklist_1: 'Asegúrate de ter as chaves dispoñibles',
    tasacion_checklist_2: 'A vivenda debe estar accesible',
    tasacion_checklist_3: 'Ten á man a escritura ou nota simple',
    tasacion_checklist_4: 'O proceso adoita durar entre 30 e 60 minutos',
    tasacion_schedule_title: 'Concertar Cita',
    tasacion_schedule_subtitle: 'Propón unha data e hora para que o taxador visite a vivenda',
    tasacion_date_label: 'Data da visita',
    tasacion_time_label: 'Hora aproximada',
    tasacion_select: 'Seleccionar',
    tasacion_notes_label: 'Notas adicionais (portal, timbre...)',
    tasacion_send_proposal: 'Enviar proposta de cita',
    tasacion_snack_proposed: 'Proposta enviada ao vendedor',
    tasacion_snack_accepted: 'Cita confirmada correctamente',
    tasacion_snack_rejected: 'Contraoferta enviada ao comprador',
    tasacion_snack_counter_accepted: 'Nova data aceptada correctamente',
    tasacion_waiting_title: 'Agardando o comprador',
    tasacion_waiting_body: 'O comprador debe propoñer unha data para a visita do taxador. Avisareímoste cando o faga.',
    tasacion_proposed_badge: 'Cita Proposta',
    tasacion_your_proposal: 'A túa proposta',
    tasacion_proposed_hint: 'Agardando que o vendedor confirme ou propoña outra hora.',
    tasacion_buyer_proposes: 'O comprador propón unha cita',
    tasacion_proposed_date: 'Data proposta',
    tasacion_accept_date: 'Aceptar data e hora',
    tasacion_cancel_label: 'Cancelar',
    tasacion_reject_propose: 'Rexeitar e propoñer outra',
    tasacion_alt_title: 'A túa contraproposta',
    tasacion_alt_date: 'Nova data suxerida',
    tasacion_alt_time: 'Nova hora suxerida',
    tasacion_alt_notes: 'Motivo do cambio / notas',
    tasacion_send_counter: 'Enviar contraproposta',
    tasacion_seller_counter_title: 'O vendedor propón outra data',
    tasacion_seller_counter_body: 'O vendedor non pode na data solicitada e suxire o seguinte horario:',
    tasacion_seller_proposal: 'Proposta do vendedor',
    tasacion_propose_other: 'Propoñer outra data distinta',
    tasacion_waiting_new_title: 'Agardando resposta',
    tasacion_waiting_new_body: 'Enviaches unha contraproposta. O comprador debe aceptala ou propoñer unha nova.',
    tasacion_confirmed: 'Cita Confirmada!',
    tasacion_confirmed_at: 'A visita será o {date} ás {time}',
    tasacion_seller_confirm_hint: 'Por favor, asegúrate de estar presente ou facilitar o acceso.',
    tasacion_buyer_confirm_hint: 'O taxador acudirá na data acordada.',
    tasacion_confirm_visit_title: 'Confirmar Realización',
    tasacion_confirm_visit_body: 'Unha vez que o taxador visitase a vivenda, por favor confírmao para avanzar ao seguinte paso (FEIN).',
    tasacion_visit_done: 'Confirmar que a visita se realizou',
    tasacion_completed: 'Taxación Realizada',
    tasacion_completed_seller: 'A visita do taxador completouse correctamente.',
    tasacion_completed_buyer: 'A visita completouse. O seguinte paso é a emisión do FEIN por parte do banco.',
    tasacion_goto_fein: 'Ir ao paso do FEIN',
    pv_seller_banner: 'Sube as últimas facturas e xustificantes para facilitar o cambio de titularidade ao comprador.',
    pv_buyer_banner: 'Aquí podes descargar a documentación facilitada polo vendedor para tramitar os cambios de nome.',
    pv_all_done: 'Completaches a entrega de toda a documentación.',
    pv_snack_uploaded: 'Documento subido correctamente.',
    pv_error_upload: 'Erro ao subir o documento.',
    pv_error_save: 'Erro ao gardar o estado do documento.',
    pv_snack_downloaded: 'Documento descargado con éxito.',
    pv_error_download: 'Erro ao descargar o documento.',
    pv_uploading: 'Subindo...',
    pv_file_uploaded: 'Arquivo subido',
    pv_in_person: 'Entregado en persoa',
    pv_upload_btn: 'Subir Arquivo',
    pv_in_person_btn: 'Entregar en man',
    pv_not_applicable_btn: 'Non aplica',
    pv_download_btn: 'Descargar documento',
    pv_doc_available: 'Documento dispoñible',
    pv_in_person_badge: 'En man / Notaría',
    pv_not_applicable_badge: 'Non aplica',
    pv_pending_seller: 'Pendente do vendedor',
    pv_elec_label: 'Electricidade',
    pv_elec_sub: 'Última factura e código CUPS',
    pv_elec_na: 'Non hai contrato de luz',
    pv_water_label: 'Auga',
    pv_water_sub: 'Última factura ou recibo',
    pv_water_na: 'Non hai contrato de auga',
    pv_gas_label: 'Gas',
    pv_gas_sub: 'Última factura (se aplica)',
    pv_gas_na: 'Non hai contrato de gas',
    pv_ibi_label: 'IBI',
    pv_ibi_sub: 'Xustificante de pagamento do ano en curso',
    pv_ibi_na: 'Exento de IBI',
    pv_comm_label: 'Comunidade',
    pv_comm_sub: 'Certificado de pagamento ao corrente',
    pv_comm_na: 'Non hai comunidade',
    pv_buyer_elec: 'Subministración Eléctrica',
    pv_buyer_elec_sub: 'Pasos para o cambio de titular',
    pv_buyer_elec_1: 'Localiza o código CUPS na factura.',
    pv_buyer_elec_2: 'Chama á comercializadora elixida.',
    pv_buyer_elec_3: 'Ten á man a escritura de compravenda.',
    pv_buyer_elec_4: 'Indica a túa conta bancaria para os recibos.',
    pv_buyer_water: 'Subministración de Auga',
    pv_buyer_water_sub: 'Pasos para a alta/cambio',
    pv_buyer_water_1: 'Identifica a empresa municipal de auga.',
    pv_buyer_water_2: 'Achega o boletín se a alta é nova.',
    pv_buyer_water_3: 'Presenta o DNI e a escritura.',
    pv_buyer_water_4: 'O proceso pode tardar uns días.',
    pv_buyer_gas: 'Subministración de Gas',
    pv_buyer_gas_sub: 'Trámites necesarios',
    pv_buyer_gas_1: 'Verifica se hai contrato activo.',
    pv_buyer_gas_2: 'Necesitarás o certificado de instalación.',
    pv_buyer_gas_3: 'Contacta coa distribuidora da zona.',
    pv_buyer_gas_4: 'Solicita unha revisión de seguridade.',
    pv_buyer_ibi: 'IBI e Taxas',
    pv_buyer_ibi_sub: 'Xestión municipal',
    pv_buyer_ibi_1: 'Acude ao concello coa escritura.',
    pv_buyer_ibi_2: 'Inscribe a propiedade no catastro.',
    pv_buyer_ibi_3: 'Domicilia o próximo recibo.',
    pv_buyer_ibi_4: 'Comproba posibles débedas anteriores.',
    pv_buyer_comm: 'Comunidade de Propietarios',
    pv_buyer_comm_sub: 'Alta como propietario',
    pv_buyer_comm_1: 'Contacta co administrador.',
    pv_buyer_comm_2: 'Facilita os teus datos de contacto.',
    pv_buyer_comm_3: 'Informa da túa conta para as cotas.',
    pv_buyer_comm_4: 'Solicita os estatutos da finca.',
    fein_buyer_banner: 'Confirma que recibiches a FEIN (Ficha Europea de Información Normalizada) da túa entidade bancaria.',
    fein_seller_banner: 'O comprador está a xestionar a formalización bancaria. Este proceso é obrigatorio antes de acudir á notaría.',
    fein_what_is: 'Que é a FEIN?',
    fein_faq1_title: 'Obrigatorio',
    fein_faq1_body: 'É o documento que detalla as condicións definitivas da túa hipoteca.',
    fein_faq2_title: 'Prazo',
    fein_faq2_body: 'Debes tela polo menos 10 días antes da sinatura na notaría.',
    fein_faq3_title: 'Seguinte',
    fein_faq3_body: 'Tras confirmala, coordinaremos a cita co notario.',
    fein_process_title: 'Pasos ata a Notaría',
    fein_step1_title: 'Taxación Completada',
    fein_step1_body: 'A vivenda xa foi valorada polo banco.',
    fein_step2_title: 'Oferta Vinculante',
    fein_step2_body: 'O banco emite a FEIN e o borrador do contrato.',
    fein_step3_title: 'Confirmación na App',
    fein_step3_body: 'Indicas que tes a documentación necesaria.',
    fein_step4_title: 'Acta Previa',
    fein_step4_body: 'Visita ao notario para resolver dúbidas.',
    fein_step5_title: 'Sinatura de Escritura',
    fein_step5_body: 'Sinatura final e entrega de chaves.',
    fein_form_title: 'Confirmar Recepción',
    fein_check1: 'Recibín a FEIN e o FIPER do meu banco.',
    fein_check2: 'Lin e comprendín as condicións do préstamo.',
    fein_form_warn: 'Esta confirmación indica que estás listo para pasar á fase de notaría. Non é un contrato legal, pero avanza o proceso en InmuFácil.',
    fein_seller_wait_title: 'Agardando Formalización',
    fein_seller_wait_body: 'O comprador debe confirmar que xa dispón da FEIN. Avisareímoste cando ocorra.',
    fein_success_title: 'Formalización Confirmada!',
    fein_success_buyer: 'Confirmaches a recepción da FEIN. Agora podemos proceder á elección de notaría.',
    fein_success_seller: 'O comprador confirmou a formalización bancaria. Estamos listos para coordinar a notaría.',
    fein_success_warn: 'Lembra que deben pasar polo menos 10 días desde a emisión da FEIN ata a sinatura.',
    fein_goto_notary: 'Ir á Notaría',
    fein_back_timeline: 'Volver á liña de tempo',
    keys_confirm_wait_snack: 'Confirmación rexistrada. Agardando a confirmación da outra parte.',
    keys_confirm_error: 'Erro ao confirmar a entrega de chaves.',
    keys_completed_title: 'Transacción Finalizada!',
    keys_completed_desc: 'Ambas as partes confirmaron a entrega de chaves. A compravenda en InmuFácil completouse con éxito.',
    keys_accept: 'Entendido',
    keys_delivered_title: 'Entrega de Chaves',
    keys_pending_title: 'Entrega Pendente',
    keys_delivered_desc: 'A posesión da vivenda foi transferida formalmente.',
    keys_pending_desc: 'Ambas as partes deben confirmar a entrega de chaves tras a sinatura na notaría.',
    keys_seller: 'Vendedor',
    keys_buyer: 'Comprador',
    keys_confirmed: 'Entrega confirmada',
    keys_confirm_prompt: 'Por favor, confirma que realizaches a entrega.',
    keys_waiting_confirm: 'Agardando confirmación',
    keys_confirm_btn: 'Confirmar Entrega',
    keys_doc1: 'Conxunto completo de chaves (vivenda, buzón, trasteiro)',
    keys_doc2: 'Certificado de Eficiencia Enerxética (orixinal)',
    keys_doc3: 'Cédula de Habitabilidade (se aplica)',
    keys_doc4: 'Últimos recibos de IBI e subministracións pagados',
    keys_doc5: 'Certificado de estar ao corrente coa comunidade',
    keys_doc6: 'Manuais e garantías de electrodomésticos',
    keys_tips_title: 'Consellos finais',
    keys_tip1: 'Fai fotos do estado dos contadores (luz, auga, gas).',
    keys_tip2: 'Realiza o cambio de titularidade das subministracións canto antes.',
    keys_tip3: 'Cambia o bombín da pechadura principal por seguridade.',
    keys_tip4: 'Comunica a venda á túa entidade bancaria e seguro de fogar.',
    notary_close_title: 'Peche na Notaría',
    notary_buyer_desc: 'Confirma que se asinou a escritura pública de compravenda e se recibiron as chaves.',
    notary_seller_desc: 'Confirma que se asinou a escritura e se entregaron as chaves ao novo propietario.',
    notary_status_title: 'Estado das Confirmacións',
    notary_your_confirm_buyer: 'A túa confirmación (Comprador)',
    notary_your_confirm_seller: 'A túa confirmación (Vendedor)',
    notary_other_confirm_seller: 'Confirmación do Vendedor',
    notary_other_confirm_buyer: 'Confirmación do Comprador',
    notary_declare_title: 'Declaración Xurada',
    notary_declare_signed: 'Declaro que a sinatura ante notario se realizou correctamente.',
    notary_declare_keys_buyer: 'Recibín todas as chaves da vivenda.',
    notary_declare_keys_seller: 'Entreguei todas as chaves ao comprador.',
    notary_declare_warning: 'Esta acción é irreversible e marca o fin da fase de compravenda en InmuFácil.',
    notary_confirm_btn: 'Confirmar Sinatura e Entrega',
    notary_success_title: 'Parabéns!',
    notary_success_buyer: 'A compra completouse oficialmente. Xa podes acceder á xestión post-venda.',
    notary_success_seller: 'A venda completouse oficialmente. Grazas por confiar en InmuFácil.',
    notary_go_post_venta: 'Ir a Post-Venda',
    notary_pending: 'Pendente',
    notary_confirmed: 'Confirmado',
    notaria_subtitle: 'Fito 8 de 9 — Cita notarial e entrega de chaves',
    tasacion_app_bar_title: 'Taxación da Vivenda',
    tasacion_appointment_format: '{day}/{month}/{year}  ·  {time}',
    fein_notes_confirm: 'Confirmación de FEIN desde a app.',
    keys_docs_delivery: 'Documentación a entregar',
    pv_not_applicable_label: 'Non aplica',
  },
  'eu-ES': {
    fein_title: 'Banku Formalizazioa (FEIN)',
    footer_legal: 'Legala',
    tasacion_info_title: 'Balorazioen Prozesua',
    tasacion_info_body: 'Balorazioa ezinbesteko urratsa da bankuak eroslearen hipoteka onesteko. Espainiako Bankuak homologatutako erakunde batek egin behar du.',
    tasacion_checklist_seller: 'Saltzailearentzako Prestaketa',
    tasacion_checklist_buyer: 'Eroslearentzako Prestaketa',
    tasacion_checklist_1: 'Ziurtatu gakoak eskuragarri dituzula',
    tasacion_checklist_2: 'Etxebizitza irisgarria izan behar da',
    tasacion_checklist_3: 'Eskritura edo nota sinplea eskura eduki',
    tasacion_checklist_4: 'Prozesuak 30 eta 60 minuto artean irauten du normalean',
    tasacion_schedule_title: 'Hitzordua Hartu',
    tasacion_schedule_subtitle: 'Proposatu data eta ordua baloratzaileak etxebizitza bisita dezan',
    tasacion_date_label: 'Bisitaren data',
    tasacion_time_label: 'Gutxi gorabeherako ordua',
    tasacion_select: 'Hautatu',
    tasacion_notes_label: 'Ohar gehigarriak (portala, timbre...)',
    tasacion_send_proposal: 'Hitzordu proposamena bidali',
    tasacion_snack_proposed: 'Proposamena saltzaileari bidali zaio',
    tasacion_snack_accepted: 'Hitzordua behar bezala baieztatuta',
    tasacion_snack_rejected: 'Kontraeskaintza erosleari bidali zaio',
    tasacion_snack_counter_accepted: 'Data berria behar bezala onartuta',
    tasacion_waiting_title: 'Eroslea zain',
    tasacion_waiting_body: 'Erosleak baloratzailearen bisitarako data proposatu behar du. Egiten duenean jakinaraziko dizugu.',
    tasacion_proposed_badge: 'Hitzordua Proposatuta',
    tasacion_your_proposal: 'Zure proposamena',
    tasacion_proposed_hint: 'Saltzaileak baieztatu edo beste ordu bat proposatzen duen zain.',
    tasacion_buyer_proposes: 'Erosleak hitzordu bat proposatzen du',
    tasacion_proposed_date: 'Proposatutako data',
    tasacion_accept_date: 'Data eta ordua onartu',
    tasacion_cancel_label: 'Utzi',
    tasacion_reject_propose: 'Ukatu eta beste bat proposatu',
    tasacion_alt_title: 'Zure kontraproposamena',
    tasacion_alt_date: 'Data berria iradoki',
    tasacion_alt_time: 'Ordu berria iradoki',
    tasacion_alt_notes: 'Aldaketaren arrazoia / oharrak',
    tasacion_send_counter: 'Kontraproposamena bidali',
    tasacion_seller_counter_title: 'Saltzaileak beste data bat proposatzen du',
    tasacion_seller_counter_body: 'Saltzaileak ezin du eskatutako datan eta ordu hau iradokitzen du:',
    tasacion_seller_proposal: 'Saltzailearen proposamena',
    tasacion_propose_other: 'Beste data bat proposatu',
    tasacion_waiting_new_title: 'Erantzunaren zain',
    tasacion_waiting_new_body: 'Kontraproposamena bidali duzu. Erosleak onartu edo berri bat proposatu behar du.',
    tasacion_confirmed: 'Hitzordua Baieztatuta!',
    tasacion_confirmed_at: 'Bisita {date} egunean {time}etan izango da',
    tasacion_seller_confirm_hint: 'Mesedez, ziurtatu presente zaudela edo sarbidea errazten duzula.',
    tasacion_buyer_confirm_hint: 'Baloratzaileak adostutako datan etorriko da.',
    tasacion_confirm_visit_title: 'Burutzea Baieztatu',
    tasacion_confirm_visit_body: 'Baloratzaileak etxebizitza bisitatu ondoren, mesedez baiezta ezazu hurrengo urratsera (FEIN) aurreratzeko.',
    tasacion_visit_done: 'Bisita egin dela baieztatu',
    tasacion_completed: 'Balorazioa Eginda',
    tasacion_completed_seller: 'Baloratzailearen bisita behar bezala osatu da.',
    tasacion_completed_buyer: 'Bisita osatu da. Hurrengo urratsa bankuak FEIN igortzea da.',
    tasacion_goto_fein: 'FEINren urratsera joan',
    pv_seller_banner: 'Igo azken fakturak eta agiriak jabetza-aldaketa erosleari errazteko.',
    pv_buyer_banner: 'Hemen deskarga ditzakezu saltzaileak emandako agiriak izen-aldaketak tramitatzeko.',
    pv_all_done: 'Dokumentazio guztia eman duzu.',
    pv_snack_uploaded: 'Dokumentua behar bezala igota.',
    pv_error_upload: 'Errorea dokumentua igotzean.',
    pv_error_save: 'Errorea dokumentuaren egoera gordetzean.',
    pv_snack_downloaded: 'Dokumentua arrakastaz deskargatu da.',
    pv_error_download: 'Errorea dokumentua deskargatzen.',
    pv_uploading: 'Igotzen...',
    pv_file_uploaded: 'Fitxategia igota',
    pv_in_person: 'Pertsonalki emanda',
    pv_upload_btn: 'Fitxategia Igo',
    pv_in_person_btn: 'Eskuz eman',
    pv_not_applicable_btn: 'Ez da aplikatzen',
    pv_download_btn: 'Dokumentua deskargatu',
    pv_doc_available: 'Dokumentua erabilgarri',
    pv_in_person_badge: 'Eskuz / Notarioa',
    pv_not_applicable_badge: 'Ez da aplikatzen',
    pv_pending_seller: 'Saltzailearen zain',
    pv_elec_label: 'Elektrizitatea',
    pv_elec_sub: 'Azken faktura eta CUPS kodea',
    pv_elec_na: 'Ez dago argindar kontraturik',
    pv_water_label: 'Ura',
    pv_water_sub: 'Azken faktura edo ordainagiri',
    pv_water_na: 'Ez dago ur kontraturik',
    pv_gas_label: 'Gasa',
    pv_gas_sub: 'Azken faktura (aplikatzen bada)',
    pv_gas_na: 'Ez dago gas kontraturik',
    pv_ibi_label: 'IBI',
    pv_ibi_sub: 'Urteko ordainketa-frogagiria',
    pv_ibi_na: 'IBItik salbuetsita',
    pv_comm_label: 'Komunitatea',
    pv_comm_sub: 'Ordainketaz egunean dagoen ziurtagiria',
    pv_comm_na: 'Ez dago komunitaterik',
    pv_buyer_elec: 'Elektrizitate Hornidura',
    pv_buyer_elec_sub: 'Titularra aldatzeko urratsak',
    pv_buyer_elec_1: 'Bilatu CUPS kodea fakturan.',
    pv_buyer_elec_2: 'Deitu hautatutako hornitzaileari.',
    pv_buyer_elec_3: 'Eduki eskritura eskura.',
    pv_buyer_elec_4: 'Adierazi zure banku-kontua ordainagirietarako.',
    pv_buyer_water: 'Ur Hornidura',
    pv_buyer_water_sub: 'Alta/aldaketa egiteko urratsak',
    pv_buyer_water_1: 'Identifikatu udal ur enpresa.',
    pv_buyer_water_2: 'Alta berria bada, boletina aurkeztu.',
    pv_buyer_water_3: 'Aurkeztu NAA eta eskritura.',
    pv_buyer_water_4: 'Prozesuak egun batzuk har ditzake.',
    pv_buyer_gas: 'Gas Hornidura',
    pv_buyer_gas_sub: 'Beharrezko tramiteak',
    pv_buyer_gas_1: 'Egiaztatu kontratu aktiborik badagoen.',
    pv_buyer_gas_2: 'Instalazio-ziurtagiria beharko duzu.',
    pv_buyer_gas_3: 'Jarri harremanetan zonako banatzailearekin.',
    pv_buyer_gas_4: 'Eskatu segurtasun-ikuskapen bat.',
    pv_buyer_ibi: 'IBI eta Tasak',
    pv_buyer_ibi_sub: 'Udal kudeaketa',
    pv_buyer_ibi_1: 'Joan udaletxera eskriturarekin.',
    pv_buyer_ibi_2: 'Inskribatu jabetza katastroan.',
    pv_buyer_ibi_3: 'Domiziliatu hurrengo ordainagiria.',
    pv_buyer_ibi_4: 'Egiaztatu aurreko zor posibleak.',
    pv_buyer_comm: 'Jabeen Komunitatea',
    pv_buyer_comm_sub: 'Alta jabea gisa',
    pv_buyer_comm_1: 'Jarri harremanetan administratzailearekin.',
    pv_buyer_comm_2: 'Eman zure harremanetarako datuak.',
    pv_buyer_comm_3: 'Eman zure kontua kuoten ordainketarako.',
    pv_buyer_comm_4: 'Eskatu finkaren estatutuak.',
    fein_buyer_banner: 'Baiezta ezazu zure bankuaren FEIN (Europako Informazio Normalizatutako Fitxa) jaso duzula.',
    fein_seller_banner: 'Eroslea banku-formalizazioa kudeatzen ari da. Prozesu hau derrigorrezkoa da notariorengana joan aurretik.',
    fein_what_is: 'Zer da FEIN?',
    fein_faq1_title: 'Derrigorrezkoa',
    fein_faq1_body: 'Zure hipotekaren behin betiko baldintzak zehazteko dokumentua da.',
    fein_faq2_title: 'Epea',
    fein_faq2_body: 'Notarioan sinatu baino gutxienez 10 egun lehenago eduki behar duzu.',
    fein_faq3_title: 'Hurrengoa',
    fein_faq3_body: 'Baieztatutakoan, notarioarekin hitzordua koordinatuko dugu.',
    fein_process_title: 'Notariorako Urratsak',
    fein_step1_title: 'Balorazioa Eginda',
    fein_step1_body: 'Etxebizitza bankuak jada balioetsi du.',
    fein_step2_title: 'Eskaintza Loteslea',
    fein_step2_body: 'Bankuak FEIN eta kontratu-zirriborroa igortzen du.',
    fein_step3_title: 'Appeko Baieztapena',
    fein_step3_body: 'Adierazten duzu beharrezko dokumentazioa duzula.',
    fein_step4_title: 'Aldez Aurreko Akta',
    fein_step4_body: 'Notariora bisita zalantzak argitzeko.',
    fein_step5_title: 'Eskrituren Sinadura',
    fein_step5_body: 'Azken sinadura eta gakoen entrega.',
    fein_form_title: 'Jasotzea Baieztatu',
    fein_check1: 'Nire bankuaren FEIN eta FIPER jaso ditut.',
    fein_check2: 'Maileguaren baldintzak irakurri eta ulertu ditut.',
    fein_form_warn: 'Baieztapen honek notario-fasera pasatzeko prest zaudela adierazten du. Ez da kontratu legal bat, baina InmuFácil-eko prozesua aurreratzen du.',
    fein_seller_wait_title: 'Formalizazioaren Zain',
    fein_seller_wait_body: 'Erosleak FEIN duela baieztatu behar du. Gertatzean jakinaraziko dizugu.',
    fein_success_title: 'Formalizazioa Baieztatuta!',
    fein_success_buyer: 'FEINren jasotzea baieztatu duzu. Orain notarioa aukeratzeko prozesua has dezakegu.',
    fein_success_seller: 'Erosleak banku-formalizazioa baieztatuta du. Notarioa koordinatzeko prest gaude.',
    fein_success_warn: 'Gogoratu FEINren igorpenetik sinadura arte gutxienez 10 egun igaro behar direla.',
    fein_goto_notary: 'Notariorengana Joan',
    fein_back_timeline: 'Denbora-lerrora itzuli',
    keys_confirm_wait_snack: 'Baieztapena erregistratuta. Beste aldearen baieztapenaren zain.',
    keys_confirm_error: 'Errorea gakoen entrega baieztatzean.',
    keys_completed_title: 'Transakzioa Amaituta!',
    keys_completed_desc: 'Bi aldeak gakoen entrega baieztatu dute. InmuFácil-eko erosketa-transakzioa arrakastaz osatu da.',
    keys_accept: 'Ulertuta',
    keys_delivered_title: 'Gakoen Entrega',
    keys_pending_title: 'Entrega Zain',
    keys_delivered_desc: 'Etxebizitzaren jabetza formalki transferitu da.',
    keys_pending_desc: 'Bi aldeak notarian sinatu ondoren gakoen entrega baieztatu behar dute.',
    keys_seller: 'Saltzailea',
    keys_buyer: 'Eroslea',
    keys_confirmed: 'Entrega baieztatuta',
    keys_confirm_prompt: 'Mesedez, baiezta ezazu entrega egin duzula.',
    keys_waiting_confirm: 'Baieztapenaren zain',
    keys_confirm_btn: 'Entrega Baieztatu',
    keys_doc1: 'Gako multzo osoa (etxebizitza, posta-kutxa, trastelekua)',
    keys_doc2: 'Energia Efizientziaren Ziurtagiria (originala)',
    keys_doc3: 'Bizitarritasun Ziurtagiria (aplikatzen bada)',
    keys_doc4: 'IBIren eta horniduren azken ordainagiriak ordainduta',
    keys_doc5: 'Komunitatearekin egunean dagoen ziurtagiria',
    keys_doc6: 'Etxetresna elektrikoen eskuliburuak eta bermeak',
    keys_tips_title: 'Azken aholkuak',
    keys_tip1: 'Argazkiak atera kontadoreen egoeraren (argia, ura, gasa).',
    keys_tip2: 'Ahalik eta lasterren egin horniduren titularra aldatzea.',
    keys_tip3: 'Aldatu ate nagusiaren zilindroa segurtasunerako.',
    keys_tip4: 'Jakinarazi saltzen banku-erakundea eta etxeko aseguruari.',
    notary_close_title: 'Notarioan Itxiera',
    notary_buyer_desc: 'Baiezta ezazu erosketa-eskritura publikoa sinatu dela eta gakoak jaso dituzula.',
    notary_seller_desc: 'Baiezta ezazu eskritura sinatu dela eta gakoak jabari berriari eman zaizkiola.',
    notary_status_title: 'Baieztapenen Egoera',
    notary_your_confirm_buyer: 'Zure baieztapena (Eroslea)',
    notary_your_confirm_seller: 'Zure baieztapena (Saltzailea)',
    notary_other_confirm_seller: 'Saltzailearen baieztapena',
    notary_other_confirm_buyer: 'Eroslearen baieztapena',
    notary_declare_title: 'Zin Adierazpena',
    notary_declare_signed: 'Adierazten dut notarioan egindako sinadura behar bezala egin dela.',
    notary_declare_keys_buyer: 'Etxebizitzaren gako guztiak jaso ditut.',
    notary_declare_keys_seller: 'Gako guztiak erosleari eman dizkiot.',
    notary_declare_warning: 'Ekintza hau itzulezina da eta InmuFácil-eko erosketa-fasearen amaiera markatzen du.',
    notary_confirm_btn: 'Sinadura eta Entrega Baieztatu',
    notary_success_title: 'Zorionak!',
    notary_success_buyer: 'Erosketa ofizialki osatu da. Orain saltze osteko kudeaketara sar zaitezke.',
    notary_success_seller: 'Salmenta ofizialki osatu da. Eskerrik asko InmuFácil-en fidatzeagatik.',
    notary_go_post_venta: 'Saltze Ostekora Joan',
    notary_pending: 'Zain',
    notary_confirmed: 'Baieztatuta',
    notaria_subtitle: '9tik 8. helbidea — Notario-hitzordua eta gakoen entrega',
    tasacion_app_bar_title: 'Etxebizitzaren Balorazioa',
    tasacion_appointment_format: '{day}/{month}/{year}  ·  {time}',
    fein_notes_confirm: 'FEINren baieztapena apptik.',
    keys_docs_delivery: 'Entregatzeko dokumentazioa',
    pv_not_applicable_label: 'Ez da aplikatzen',
  },
};

// va-ES copies ca-ES but with minor Valencian adjustments
tx['va-ES'] = {
  ...tx['ca-ES'],
  fein_title: 'Formalització Bancària (FEIN)',
  tasacion_info_title: 'Procés de Taxació',
  tasacion_checklist_seller: 'Preparació per al Venedor',
  tasacion_checklist_buyer: 'Preparació per al Comprador',
  tasacion_schedule_title: 'Concertar Cita',
  tasacion_cancel_label: 'Cancel·lar',
  keys_doc1: 'Joc complet de claus (habitatge, bústia, traster)',
  notary_success_buyer: 'La compra s\'ha completat oficialment. Ja pots accedir a la gestió post-venda.',
  notary_success_seller: 'La venda s\'ha completat oficialment. Gràcies per confiar en InmuFácil.',
};

// en-GB and en-CA copy en-US (already translated in Phase B partially, just fill gaps)
tx['en-GB'] = { ...tx['en-US'] };
tx['en-CA'] = { ...tx['en-US'] };

// fr-CA copies fr-FR
tx['fr-CA'] = { ...tx['fr-FR'] };

const langs = ['en-US','en-GB','en-CA','fr-FR','fr-CA','ca-ES','va-ES','eu-ES','gl-ES'];

langs.forEach(lang => {
  const fp = base + lang + '.json';
  const json = JSON.parse(fs.readFileSync(fp, 'utf8'));
  if (!json.transaction) json.transaction = {};
  const trans = tx[lang];
  Object.entries(trans).forEach(([k, v]) => {
    json.transaction[k] = v;
  });
  fs.writeFileSync(fp, JSON.stringify(json, null, 2), 'utf8');
  console.log(lang + ': transaction section updated');
});
