'use strict';
// Phase C Regional A: auth + property + property_listing + property_wizard
// Languages: ca-ES, va-ES (copy ca), eu-ES, gl-ES, fr-FR, fr-CA (copy fr), en-GB/en-CA (copy en-US)
const fs = require('fs');
const path = require('path');

const TRANS_DIR = path.join(__dirname, 'frontend', 'assets', 'translations');

function readJson(locale) {
  return JSON.parse(fs.readFileSync(path.join(TRANS_DIR, locale + '.json'), 'utf8'));
}
function writeJson(locale, data) {
  fs.writeFileSync(path.join(TRANS_DIR, locale + '.json'), JSON.stringify(data, null, 2) + '\n', 'utf8');
}
function setVal(obj, dotPath, value) {
  const parts = dotPath.split('.');
  let cur = obj;
  for (let i = 0; i < parts.length - 1; i++) {
    if (typeof cur[parts[i]] !== 'object' || cur[parts[i]] === null) cur[parts[i]] = {};
    cur = cur[parts[i]];
  }
  cur[parts[parts.length - 1]] = value;
}

// ============================================================
// AUTH translations
// ============================================================
const authCa = {
  'auth.login_button': 'Entra',
  'auth.copyright_secure': '© 2026 INMUFÁCIL SECURE-TECH',
  'auth.google_sign_in_button': 'Continua amb Google',
  'auth.or_separator': 'o',
  'auth.google_error_cancelled': "Inici de sessió amb Google cancel·lat",
  'auth.google_error_generic': 'Error en autenticar amb Google',
  'auth.no_intermediaries': 'Sense intermediaris.\n0% comissions.',
  'auth.buy_sell_no_fees': 'Compra i ven sense comissions.',
  'auth.search_to_notary': 'De la cerca a la notaria\nen passos segurs.',
  'auth.eliminate_uncertainty': "Elimina la incertesa.",
  'auth.tagline': 'Immoble fàcil entre particulars',
  'auth.access_secure_panel': "Accedeix al teu tauler segur d'InmuFácil.",
  'auth.guarantee_label': 'GARANTIA INMUFÁCIL',
  'auth.guarantee_title': 'La teva venda tranquil·la',
  'auth.p2p_verified_title': 'La teva compra segura',
  'auth.continue_without_account': 'Continua sense registrar-te →',
  'auth.register_link': "Registra't",
  'auth.account_created': 'Compte creat. Si us plau, inicia sessió.',
  'auth.no_fees': 'SENSE COMISSIONS',
  'auth.create_account': 'Crea el teu compte',
  'auth.join_p2p': "Uneix-te a la xarxa P2P més segura del sector immobiliari.",
  'auth.min_3_chars': 'Mínim 3 caràcters',
  'auth.email_label_short': 'Correu electrònic',
  'auth.password_label_short': 'Contrasenya',
  'auth.min_8_chars': 'Mínim 8 caràcters',
  'auth.generate_password': 'Genera contrasenya segura',
  'auth.confirm_password': 'Confirma la contrasenya',
  'auth.confirm_password_hint_register': 'Repeteix la contrasenya',
  'auth.accept_prefix': 'Accepto els ',
  'auth.terms_conditions': 'Termes i Condicions',
  'auth.privacy_policy': 'Política de Privacitat',
  'auth.already_have_account': 'Ja tens compte? ',
};

const authEu = {
  'auth.login_button': 'Sartu',
  'auth.copyright_secure': '© 2026 INMUFÁCIL SECURE-TECH',
  'auth.google_sign_in_button': 'Jarraitu Googlerekin',
  'auth.or_separator': 'edo',
  'auth.google_error_cancelled': 'Google-rekin saioa hastea bertan behera utzi da',
  'auth.google_error_generic': 'Errore bat gertatu da Google-rekin autentikatzerakoan',
  'auth.no_intermediaries': 'Bitartekaririk gabe.\n0% komisioak.',
  'auth.buy_sell_no_fees': 'Erosi eta saldu komisiorik gabe.',
  'auth.search_to_notary': 'Bilaketariek notariorainoko\npauso seguruak.',
  'auth.eliminate_uncertainty': 'Ezabatu ziurgabetasuna.',
  'auth.tagline': 'Jabetza erraza partikularren artean',
  'auth.access_secure_panel': "Sartu zure InmuFácil panel segurura.",
  'auth.guarantee_label': 'INMUFÁCIL BERMEA',
  'auth.guarantee_title': 'Zure salmenta lasaia',
  'auth.p2p_verified_title': 'Zure erosketa segurua',
  'auth.continue_without_account': 'Jarraitu erregistratu gabe →',
  'auth.register_link': 'Erregistratu',
  'auth.account_created': 'Kontua sortuta. Mesedez hasi saioa.',
  'auth.no_fees': 'KOMISIORIK GABE',
  'auth.create_account': 'Sortu zure kontua',
  'auth.join_p2p': 'Bat egin sektore inmobiliarioko P2P sare seguruenarekin.',
  'auth.min_3_chars': 'Gutxienez 3 karaktere',
  'auth.email_label_short': 'Helbide elektronikoa',
  'auth.password_label_short': 'Pasahitza',
  'auth.min_8_chars': 'Gutxienez 8 karaktere',
  'auth.generate_password': 'Pasahitz segurua sortu',
  'auth.confirm_password': 'Berretsi pasahitza',
  'auth.confirm_password_hint_register': 'Errepikatu pasahitza',
  'auth.accept_prefix': 'Onartzen ditut ',
  'auth.terms_conditions': 'Termino eta Baldintzak',
  'auth.privacy_policy': 'Pribatutasun Politika',
  'auth.already_have_account': 'Jada kontua duzu? ',
};

const authGl = {
  'auth.login_button': 'Entrar',
  'auth.copyright_secure': '© 2026 INMUFÁCIL SECURE-TECH',
  'auth.google_sign_in_button': 'Continuar con Google',
  'auth.or_separator': 'ou',
  'auth.google_error_cancelled': 'Inicio de sesión con Google cancelado',
  'auth.google_error_generic': 'Erro ao autenticar con Google',
  'auth.no_intermediaries': 'Sen intermediarios.\n0% comisións.',
  'auth.buy_sell_no_fees': 'Compra e vende sen comisións.',
  'auth.search_to_notary': 'Da busca á notaría\nen pasos seguros.',
  'auth.eliminate_uncertainty': 'Elimina a incerteza.',
  'auth.tagline': 'Inmoble doado entre particulares',
  'auth.access_secure_panel': 'Accede ao teu panel seguro de InmuFácil.',
  'auth.guarantee_label': 'GARANTÍA INMUFÁCIL',
  'auth.guarantee_title': 'A túa venda tranquila',
  'auth.p2p_verified_title': 'A túa compra segura',
  'auth.continue_without_account': 'Continuar sen rexistrarse →',
  'auth.register_link': 'Rexístrate',
  'auth.account_created': 'Conta creada. Por favor inicia sesión.',
  'auth.no_fees': 'SEN COMISIÓNS',
  'auth.create_account': 'Crea a túa conta',
  'auth.join_p2p': 'Únete á rede P2P máis segura do sector inmobiliario.',
  'auth.min_3_chars': 'Mínimo 3 caracteres',
  'auth.email_label_short': 'Correo electrónico',
  'auth.password_label_short': 'Contrasinal',
  'auth.min_8_chars': 'Mínimo 8 caracteres',
  'auth.generate_password': 'Xerar contrasinal seguro',
  'auth.confirm_password': 'Confirmar contrasinal',
  'auth.confirm_password_hint_register': 'Repite o contrasinal',
  'auth.accept_prefix': 'Acepto os ',
  'auth.terms_conditions': 'Termos e Condicións',
  'auth.privacy_policy': 'Política de Privacidade',
  'auth.already_have_account': '¿Xa tes conta? ',
};

const authFr = {
  'auth.login_button': 'Se connecter',
  'auth.copyright_secure': '© 2026 INMUFÁCIL SECURE-TECH',
  'auth.google_sign_in_button': 'Continuer avec Google',
  'auth.or_separator': 'ou',
  'auth.google_error_cancelled': 'Connexion Google annulée',
  'auth.google_error_generic': "Erreur d'authentification Google",
  'auth.no_intermediaries': 'Sans intermédiaires.\n0% de commissions.',
  'auth.buy_sell_no_fees': 'Achetez et vendez sans commissions.',
  'auth.search_to_notary': 'De la recherche au notaire\nen étapes sécurisées.',
  'auth.eliminate_uncertainty': "Éliminez l'incertitude.",
  'auth.tagline': 'Immobilier facile entre particuliers',
  'auth.access_secure_panel': 'Accédez à votre tableau de bord sécurisé InmuFácil.',
  'auth.guarantee_label': 'GARANTIE INMUFÁCIL',
  'auth.guarantee_title': 'Votre vente en toute tranquillité',
  'auth.p2p_verified_title': 'Votre achat en toute sécurité',
  'auth.continue_without_account': "Continuer sans s'inscrire →",
  'auth.register_link': "S'inscrire",
  'auth.account_created': 'Compte créé. Veuillez vous connecter.',
  'auth.no_fees': 'SANS COMMISSIONS',
  'auth.create_account': 'Créez votre compte',
  'auth.join_p2p': "Rejoignez le réseau P2P le plus sécurisé du secteur immobilier.",
  'auth.min_3_chars': 'Minimum 3 caractères',
  'auth.email_label_short': 'Adresse e-mail',
  'auth.password_label_short': 'Mot de passe',
  'auth.min_8_chars': 'Minimum 8 caractères',
  'auth.generate_password': 'Générer un mot de passe sécurisé',
  'auth.confirm_password': 'Confirmer le mot de passe',
  'auth.confirm_password_hint_register': 'Répétez votre mot de passe',
  'auth.accept_prefix': "J'accepte les ",
  'auth.terms_conditions': 'Conditions Générales',
  'auth.privacy_policy': 'Politique de Confidentialité',
  'auth.already_have_account': 'Vous avez déjà un compte ? ',
};

// ============================================================
// PROPERTY translations
// ============================================================
const propertyCa = {
  'property.publish_free': 'Publicar Gratuïtament',
  'property.previous': 'Anterior',
  'property.eur_per_month': 'EUR/mes',
  'property.obfuscated_address': 'Ubicació protegida',
  'property.bedrooms_count': '{count} Hab.',
  'property.bathrooms_count': '{count} Banys',
  'property.surface_count': '{count} m²',
  'property.floor_default': 'Baix',
  'property.exterior': 'Exterior',
  'property.elevator': 'Ascensor',
  'property.energy_cert_in_progress': 'En Tràmit',
  'property.energy_cert_rating': 'Qualificació Energètica {rating}',
  'property.owner_default_name': 'Propietari',
  'property.identity_verified': 'IDENTITAT VERIFICADA',
  'property.identity_pending': 'Identitat pendent de verificar',
  'property.ad_performance': "Rendiment de l'Anunci",
  'property.metric_views': 'Visites',
  'property.metric_favorites': 'Preferits',
  'property.metric_offers': 'Ofertes',
  'property.status_active': 'ACTIU',
  'property.status_draft': 'ESBORRANY',
  'property.status_reserved': 'RESERVAT',
  'property.status_sold': 'VENUT',
  'property.status_inactive': 'INACTIU',
  'property.mortgage_title': "ESTIMACIÓ D'HIPOTECA",
  'property.mortgage_per_month': '/mes',
  'property.mortgage_financing': 'Finançament 80%  ·  {amount} €',
  'property.mortgage_term': 'Termini 30 anys  ·  TAE 3,5%',
  'property.mortgage_disclaimer': 'Càlcul orientatiu. Sense vinculació bancària.',
  'property.allow_visits': 'Permetre visites',
  'property.visits_enabled': 'Els interessats poden sol·licitar visita',
  'property.visits_disabled': 'Visites desactivades',
  'property.visit_scheduled': 'Visita programada',
  'property.visit_pending': 'Visita pendent de confirmació',
  'property.visit_confirmed': 'Visita confirmada',
  'property.visit_date_time': '{day} a les {hour}',
  'property.view_visit': 'Veure visita',
  'property.contact_private': 'Contactar Particular',
  'property.offer_first_title': 'Fes una oferta primer',
  'property.offer_first_message': 'El xat privat amb el venedor s\'obre en fer una oferta. Ambdues parts poden xatejar des d\'aquell moment.',
  'property.understood': 'Entès',
  'property.image_counter': '{current} / {total}',
  'property.compare.add': 'Comparar',
  'property.compare.in_comparison': 'En comparació',
  'property.comparison.title': 'Comparar Immobles',
  'property.comparison.property_label': 'Propietat {label}',
  'property.comparison.row.price': 'Preu total',
  'property.comparison.row.price_m2': 'Preu/m²',
  'property.comparison.row.surface': 'Superfície',
  'property.comparison.row.year': 'Any de construcció',
  'property.comparison.row.floor': 'Planta',
  'property.comparison.row.elevator': 'Ascensor',
  'property.comparison.row.condition': 'Estat',
  'property.comparison.row.ici_silence': 'ICI: Silenci',
  'property.comparison.row.ici_security': 'ICI: Seguretat',
  'property.comparison.row.ici_air': 'ICI: Aire',
  'property.comparison.row.ici_activity': 'ICI: Activitat',
  'property.comparison.row.mortgage': 'Quota hipotecària est.',
  'property.comparison.row.escrituracion': 'Despeses escripturació est.',
  'property.comparison.ai_verdict.title': "Anàlisi d'InmuFácil",
  'property.comparison.ai_verdict.property_a': 'Propietat A',
  'property.comparison.ai_verdict.property_a_body': 'Millor relació preu/superfície a la zona. Menor quota hipotecària estimada.',
  'property.comparison.ai_verdict.property_b': 'Propietat B',
  'property.comparison.ai_verdict.property_b_body': 'Construcció més recent. Menor necessitat de reforma prevista.',
  'property.comparison.ai_verdict.recommendation': "Recomanació: Basada en el teu perfil d'estil de vida, valorem la Propietat A per la seva eficiència econòmica i la Propietat B per la seva modernitat. Ambdues són opcions sòlides segons les teves preferències declarades.",
  'property.comparison.ai_verdict.disclaimer': 'Anàlisi generada per IA. Consulta un professional abans de prendre decisions.',
  'property.comparison.needs_renovation': 'Reforma',
};

const propertyEu = {
  'property.publish_free': 'Doan Argitaratu',
  'property.previous': 'Aurrekoa',
  'property.eur_per_month': 'EUR/hil',
  'property.obfuscated_address': 'Kokapena babestuta',
  'property.bedrooms_count': '{count} Log.',
  'property.bathrooms_count': '{count} Bainug.',
  'property.surface_count': '{count} m²',
  'property.floor_default': 'Behea',
  'property.exterior': 'Kanpora begira',
  'property.elevator': 'Igogailua',
  'property.energy_cert_in_progress': 'Izapidetzen',
  'property.energy_cert_rating': 'Energia Kalifikazioa {rating}',
  'property.owner_default_name': 'Jabea',
  'property.identity_verified': 'IDENTITATEA EGIAZTATUTA',
  'property.identity_pending': 'Identitatea egiaztatze zain',
  'property.ad_performance': 'Iragarkiaren Errendimendua',
  'property.metric_views': 'Bisitaldiak',
  'property.metric_favorites': 'Gogokoak',
  'property.metric_offers': 'Eskaintzak',
  'property.status_active': 'AKTIBO',
  'property.status_draft': 'ZIRRIBORROA',
  'property.status_reserved': 'ERRESERBATUTA',
  'property.status_sold': 'SALDUTA',
  'property.status_inactive': 'INAKTIBO',
  'property.mortgage_title': 'HIPOTEKA ESTIMAZIOA',
  'property.mortgage_per_month': '/hil',
  'property.mortgage_financing': 'Finantzaketa 80%  ·  {amount} €',
  'property.mortgage_term': '30 urteko epea  ·  TAE %3,5',
  'property.mortgage_disclaimer': 'Kalkulu orientagarria. Banku-konpromiso gabe.',
  'property.allow_visits': 'Bisitaldiak baimendu',
  'property.visits_enabled': 'Interesdunek bisitaldia eskatu dezakete',
  'property.visits_disabled': 'Bisitaldiak desgaituta',
  'property.visit_scheduled': 'Bisitaldia programatuta',
  'property.visit_pending': 'Bisitaldia berrespena zain',
  'property.visit_confirmed': 'Bisitaldia berretsia',
  'property.visit_date_time': '{day} {hour}etan',
  'property.view_visit': 'Bisitaldia ikusi',
  'property.contact_private': 'Partikularrarekin harremanetan jarri',
  'property.offer_first_title': 'Eskaintza egin lehenik',
  'property.offer_first_message': 'Saltzailearekin txat pribatua eskaintza egitean irekitzen da. Bi aldeak une horretatik aurrera txatean hitz egin dezakete.',
  'property.understood': 'Ulertuta',
  'property.image_counter': '{current} / {total}',
  'property.compare.add': 'Konparatu',
  'property.compare.in_comparison': 'Konparaketan',
  'property.comparison.title': 'Higiezinak Konparatu',
  'property.comparison.property_label': '{label} Higiezina',
  'property.comparison.row.price': 'Prezio osoa',
  'property.comparison.row.price_m2': 'Prezioa/m²',
  'property.comparison.row.surface': 'Azalera',
  'property.comparison.row.year': 'Eraikuntza urtea',
  'property.comparison.row.floor': 'Solairua',
  'property.comparison.row.elevator': 'Igogailua',
  'property.comparison.row.condition': 'Egoera',
  'property.comparison.row.ici_silence': 'ICI: Isiltasuna',
  'property.comparison.row.ici_security': 'ICI: Segurtasuna',
  'property.comparison.row.ici_air': 'ICI: Airea',
  'property.comparison.row.ici_activity': 'ICI: Jarduera',
  'property.comparison.row.mortgage': 'Hipoteka kuota est.',
  'property.comparison.row.escrituracion': 'Escrituraketa gastuak est.',
  'property.comparison.ai_verdict.title': 'InmuFácil Analisia',
  'property.comparison.ai_verdict.property_a': 'A Higiezina',
  'property.comparison.ai_verdict.property_a_body': 'Prezio/azalera harreman onena aldean. Hipoteka kuota estimatu txikiena.',
  'property.comparison.ai_verdict.property_b': 'B Higiezina',
  'property.comparison.ai_verdict.property_b_body': 'Eraikuntza berriagoa. Erreforma behar gutxiago espero da.',
  'property.comparison.ai_verdict.recommendation': 'Gomendioa: Zure bizi-estilo profilean oinarrituta, A Higiezina efizientzia ekonomikoagatik eta B Higiezina modernismoagatik baloratzen ditugu. Biak aukera sendoak dira zure lehentasun adierazien arabera.',
  'property.comparison.ai_verdict.disclaimer': 'IEk sortutako analisia. Kontsultatu profesional batekin erabakiak hartu aurretik.',
  'property.comparison.needs_renovation': 'Erreforma',
};

const propertyGl = {
  'property.publish_free': 'Publicar Gratuitamente',
  'property.previous': 'Anterior',
  'property.eur_per_month': 'EUR/mes',
  'property.obfuscated_address': 'Ubicación protexida',
  'property.bedrooms_count': '{count} Hab.',
  'property.bathrooms_count': '{count} Baños',
  'property.surface_count': '{count} m²',
  'property.floor_default': 'Baixo',
  'property.exterior': 'Exterior',
  'property.elevator': 'Ascensor',
  'property.energy_cert_in_progress': 'En Trámite',
  'property.energy_cert_rating': 'Cualificación Enerxética {rating}',
  'property.owner_default_name': 'Propietario',
  'property.identity_verified': 'IDENTIDADE VERIFICADA',
  'property.identity_pending': 'Identidade pendente de verificar',
  'property.ad_performance': 'Rendemento do Anuncio',
  'property.metric_views': 'Visitas',
  'property.metric_favorites': 'Favoritos',
  'property.metric_offers': 'Ofertas',
  'property.status_active': 'ACTIVO',
  'property.status_draft': 'BORRADOR',
  'property.status_reserved': 'RESERVADO',
  'property.status_sold': 'VENDIDO',
  'property.status_inactive': 'INACTIVO',
  'property.mortgage_title': 'ESTIMACIÓN DE HIPOTECA',
  'property.mortgage_per_month': '/mes',
  'property.mortgage_financing': 'Financiamento 80%  ·  {amount} €',
  'property.mortgage_term': 'Prazo 30 anos  ·  TAE 3,5%',
  'property.mortgage_disclaimer': 'Cálculo orientativo. Sen vinculación bancaria.',
  'property.allow_visits': 'Permitir visitas',
  'property.visits_enabled': 'Os interesados poden solicitar visita',
  'property.visits_disabled': 'Visitas desactivadas',
  'property.visit_scheduled': 'Visita programada',
  'property.visit_pending': 'Visita pendente de confirmación',
  'property.visit_confirmed': 'Visita confirmada',
  'property.visit_date_time': '{day} ás {hour}',
  'property.view_visit': 'Ver visita',
  'property.contact_private': 'Contactar Particular',
  'property.offer_first_title': 'Fai unha oferta primeiro',
  'property.offer_first_message': 'O chat privado co vendedor ábrese ao facer unha oferta. Ambas as partes poden chatear desde ese momento.',
  'property.understood': 'Entendido',
  'property.image_counter': '{current} / {total}',
  'property.compare.add': 'Comparar',
  'property.compare.in_comparison': 'En comparación',
  'property.comparison.title': 'Comparar Inmobles',
  'property.comparison.property_label': 'Propiedade {label}',
  'property.comparison.row.price': 'Prezo total',
  'property.comparison.row.price_m2': 'Prezo/m²',
  'property.comparison.row.surface': 'Superficie',
  'property.comparison.row.year': 'Ano de construción',
  'property.comparison.row.floor': 'Planta',
  'property.comparison.row.elevator': 'Ascensor',
  'property.comparison.row.condition': 'Estado',
  'property.comparison.row.ici_silence': 'ICI: Silencio',
  'property.comparison.row.ici_security': 'ICI: Seguridade',
  'property.comparison.row.ici_air': 'ICI: Aire',
  'property.comparison.row.ici_activity': 'ICI: Actividade',
  'property.comparison.row.mortgage': 'Cota hipotecaria est.',
  'property.comparison.row.escrituracion': 'Gastos escrituración est.',
  'property.comparison.ai_verdict.title': 'Análise de InmuFácil',
  'property.comparison.ai_verdict.property_a': 'Propiedade A',
  'property.comparison.ai_verdict.property_a_body': 'Mellor relación prezo/superficie na zona. Menor cota hipotecaria estimada.',
  'property.comparison.ai_verdict.property_b': 'Propiedade B',
  'property.comparison.ai_verdict.property_b_body': 'Construción máis recente. Menor necesidade de reforma prevista.',
  'property.comparison.ai_verdict.recommendation': 'Recomendación: Baseada no teu perfil de estilo de vida, valoramos a Propiedade A pola súa eficiencia económica e a Propiedade B pola súa modernidade. Ambas son opcións sólidas segundo as túas preferencias declaradas.',
  'property.comparison.ai_verdict.disclaimer': 'Análise xerada por IA. Consulte un profesional antes de tomar decisións.',
  'property.comparison.needs_renovation': 'Reforma',
};

const propertyFr = {
  'property.publish_free': 'Publier Gratuitement',
  'property.previous': 'Précédent',
  'property.eur_per_month': 'EUR/mois',
  'property.obfuscated_address': 'Emplacement protégé',
  'property.bedrooms_count': '{count} Ch.',
  'property.bathrooms_count': '{count} SdB',
  'property.surface_count': '{count} m²',
  'property.floor_default': 'Rez-de-chaussée',
  'property.exterior': 'Extérieur',
  'property.elevator': 'Ascenseur',
  'property.energy_cert_in_progress': 'En cours',
  'property.energy_cert_rating': 'Diagnostic Énergétique {rating}',
  'property.owner_default_name': 'Propriétaire',
  'property.identity_verified': 'IDENTITÉ VÉRIFIÉE',
  'property.identity_pending': 'Identité en attente de vérification',
  'property.ad_performance': "Performance de l'Annonce",
  'property.metric_views': 'Visites',
  'property.metric_favorites': 'Favoris',
  'property.metric_offers': 'Offres',
  'property.status_active': 'ACTIF',
  'property.status_draft': 'BROUILLON',
  'property.status_reserved': 'RÉSERVÉ',
  'property.status_sold': 'VENDU',
  'property.status_inactive': 'INACTIF',
  'property.mortgage_title': "ESTIMATION DE CRÉDIT IMMOBILIER",
  'property.mortgage_per_month': '/mois',
  'property.mortgage_financing': 'Financement 80%  ·  {amount} €',
  'property.mortgage_term': 'Durée 30 ans  ·  TAEG 3,5%',
  'property.mortgage_disclaimer': 'Calcul indicatif. Sans engagement bancaire.',
  'property.allow_visits': 'Autoriser les visites',
  'property.visits_enabled': 'Les intéressés peuvent demander une visite',
  'property.visits_disabled': 'Visites désactivées',
  'property.visit_scheduled': 'Visite planifiée',
  'property.visit_pending': 'Visite en attente de confirmation',
  'property.visit_confirmed': 'Visite confirmée',
  'property.visit_date_time': '{day} à {hour}',
  'property.view_visit': 'Voir la visite',
  'property.contact_private': 'Contacter le Particulier',
  'property.offer_first_title': "Faites d'abord une offre",
  'property.offer_first_message': "Le chat privé avec le vendeur s'ouvre lors d'une offre. Les deux parties peuvent discuter dès ce moment.",
  'property.understood': 'Compris',
  'property.image_counter': '{current} / {total}',
  'property.compare.add': 'Comparer',
  'property.compare.in_comparison': 'En comparaison',
  'property.comparison.title': 'Comparer les Biens',
  'property.comparison.property_label': 'Bien {label}',
  'property.comparison.row.price': 'Prix total',
  'property.comparison.row.price_m2': 'Prix/m²',
  'property.comparison.row.surface': 'Surface',
  'property.comparison.row.year': 'Année de construction',
  'property.comparison.row.floor': 'Étage',
  'property.comparison.row.elevator': 'Ascenseur',
  'property.comparison.row.condition': 'État',
  'property.comparison.row.ici_silence': 'ICI: Silence',
  'property.comparison.row.ici_security': 'ICI: Sécurité',
  'property.comparison.row.ici_air': 'ICI: Air',
  'property.comparison.row.ici_activity': 'ICI: Activité',
  'property.comparison.row.mortgage': 'Mensualité crédit est.',
  'property.comparison.row.escrituracion': 'Frais de notaire est.',
  'property.comparison.ai_verdict.title': "Analyse d'InmuFácil",
  'property.comparison.ai_verdict.property_a': 'Bien A',
  'property.comparison.ai_verdict.property_a_body': 'Meilleur rapport prix/surface dans la zone. Mensualité crédit estimée la plus basse.',
  'property.comparison.ai_verdict.property_b': 'Bien B',
  'property.comparison.ai_verdict.property_b_body': 'Construction plus récente. Moindre besoin de rénovation prévu.',
  'property.comparison.ai_verdict.recommendation': "Recommandation : Sur la base de votre profil de style de vie, nous valorisons le Bien A pour son efficacité économique et le Bien B pour sa modernité. Les deux sont des options solides selon vos préférences déclarées.",
  'property.comparison.ai_verdict.disclaimer': "Analyse générée par l'IA. Consultez un professionnel avant de prendre des décisions.",
  'property.comparison.needs_renovation': 'À rénover',
};

// ============================================================
// PROPERTY_LISTING translations
// ============================================================
const propertyListingCa = {
  'property_listing.sqm_unit': 'm²',
  'property_listing.how_works': 'Com funciona',
  'property_listing.favorites': 'Preferits',
  'property_listing.filters': 'Filtres',
  'property_listing.publish_property': 'Publicar propietat',
  'property_listing.filters_and_search': 'Filtres i cerca',
  'property_listing.lifestyle_sorting_notice': "Resultats ordenats per compatibilitat amb el teu estil de vida",
  'property_listing.spain': 'Espanya',
  'property_listing.search': 'Cerca',
  'property_listing.all': 'Tot',
  'property_listing.all_properties': 'Totes les propietats',
  'property_listing.properties_in': 'Propietats a {}',
  'property_listing.results_count': '{} resultats',
  'property_listing.list_view': 'Llista',
  'property_listing.grid_view': 'Quadrícula',
  'property_listing.map_view': 'Mapa',
  'property_listing.no_properties_found': 'No hem trobat propietats en aquesta zona.',
  'property_listing.try_changing_filters': "Intenta canviar els filtres o cercar en una altra ubicació.",
  'property_listing.sort_by.newest': 'Més recents',
  'property_listing.sort_by.relevance': 'Rellevància',
  'property_listing.sort_by.price_low_high': 'Preu: menor a major',
  'property_listing.sort_by.price_high_low': 'Preu: major a menor',
  'property_listing.sort_by.label': 'Ordenar',
  'property_listing.copyright': '© 2026 InmuFácil. Tots els drets reservats.',
  'property_listing.location_hint': 'Ciutat, zona...',
  'property_listing.search_button': 'Cercar propietats',
  'property_listing.price_range': 'Rang de Preu',
  'property_listing.bedrooms': 'Habitacions',
  'property_listing.bedrooms_short': 'Hab.',
  'property_listing.property_type': "Tipus d'immoble",
  'property_listing.clear_filters': 'Netejar filtres',
  'property_listing.edit_lifestyle': "Edita el meu perfil d'estil de vida →",
  'property_listing.verified_badge': 'Verificat InmuFácil',
  'property_listing.extra_labels.pool': 'Piscina',
  'property_listing.extra_labels.lift': 'Ascensor',
  'property_listing.extra_labels.exterior': 'Exterior',
  'property_listing.promo.title': 'Ven directe.',
  'property_listing.promo.subtitle': 'Sense comissions, sense intermediaris. Tot legal, tot segur.',
  'property_listing.promo.learn_more': 'Saber més',
};

const propertyListingEu = {
  'property_listing.sqm_unit': 'm²',
  'property_listing.how_works': 'Nola funtzionatzen du',
  'property_listing.favorites': 'Gogokoak',
  'property_listing.filters': 'Iragazkiak',
  'property_listing.publish_property': 'Higiezina argitaratu',
  'property_listing.filters_and_search': 'Iragazkiak eta bilaketa',
  'property_listing.lifestyle_sorting_notice': 'Emaitzak zure bizi-estiloarekiko bateragarritasunaren arabera ordenatuta',
  'property_listing.spain': 'Espainia',
  'property_listing.search': 'Bilaketa',
  'property_listing.all': 'Guztiak',
  'property_listing.all_properties': 'Higiezin guztiak',
  'property_listing.properties_in': '{} higiezinak',
  'property_listing.results_count': '{} emaitza',
  'property_listing.list_view': 'Zerrenda',
  'property_listing.grid_view': 'Sareta',
  'property_listing.map_view': 'Mapa',
  'property_listing.no_properties_found': 'Ez dugu higiezinarik aurkitu eremu honetan.',
  'property_listing.try_changing_filters': 'Saiatu iragazkiak aldatzen edo beste kokapen batean bilatzen.',
  'property_listing.sort_by.newest': 'Berriagoak',
  'property_listing.sort_by.relevance': 'Garrantzia',
  'property_listing.sort_by.price_low_high': 'Prezioa: txikienetik handienera',
  'property_listing.sort_by.price_high_low': 'Prezioa: handienetan txikieneraino',
  'property_listing.sort_by.label': 'Ordenatu',
  'property_listing.copyright': '© 2026 InmuFácil. Eskubide guztiak erreserbatuta.',
  'property_listing.location_hint': 'Hiria, eremua...',
  'property_listing.search_button': 'Higiezinak bilatu',
  'property_listing.price_range': 'Prezio-tartea',
  'property_listing.bedrooms': 'Logelak',
  'property_listing.bedrooms_short': 'Log.',
  'property_listing.property_type': 'Higiezin mota',
  'property_listing.clear_filters': 'Iragazkiak garbitu',
  'property_listing.edit_lifestyle': 'Editatu nire bizi-estilo profila →',
  'property_listing.verified_badge': 'InmuFácil Egiaztatuta',
  'property_listing.extra_labels.pool': 'Igerilekua',
  'property_listing.extra_labels.lift': 'Igogailua',
  'property_listing.extra_labels.exterior': 'Kanpora begira',
  'property_listing.promo.title': 'Saldu zuzenean.',
  'property_listing.promo.subtitle': 'Komisiorik gabe, bitartekaririk gabe. Guztia legala, guztia segurua.',
  'property_listing.promo.learn_more': 'Gehiago jakin',
};

const propertyListingGl = {
  'property_listing.sqm_unit': 'm²',
  'property_listing.how_works': 'Como funciona',
  'property_listing.favorites': 'Favoritos',
  'property_listing.filters': 'Filtros',
  'property_listing.publish_property': 'Publicar propiedade',
  'property_listing.filters_and_search': 'Filtros e busca',
  'property_listing.lifestyle_sorting_notice': 'Resultados ordenados por compatibilidade co teu estilo de vida',
  'property_listing.spain': 'España',
  'property_listing.search': 'Busca',
  'property_listing.all': 'Todo',
  'property_listing.all_properties': 'Todas as propiedades',
  'property_listing.properties_in': 'Propiedades en {}',
  'property_listing.results_count': '{} resultados',
  'property_listing.list_view': 'Lista',
  'property_listing.grid_view': 'Cuadrícula',
  'property_listing.map_view': 'Mapa',
  'property_listing.no_properties_found': 'Non atopamos propiedades nesta zona.',
  'property_listing.try_changing_filters': 'Tenta cambiar os filtros ou buscar noutra localización.',
  'property_listing.sort_by.newest': 'Máis recentes',
  'property_listing.sort_by.relevance': 'Relevancia',
  'property_listing.sort_by.price_low_high': 'Prezo: menor a maior',
  'property_listing.sort_by.price_high_low': 'Prezo: maior a menor',
  'property_listing.sort_by.label': 'Ordenar',
  'property_listing.copyright': '© 2026 InmuFácil. Todos os dereitos reservados.',
  'property_listing.location_hint': 'Cidade, zona...',
  'property_listing.search_button': 'Buscar propiedades',
  'property_listing.price_range': 'Rango de Prezo',
  'property_listing.bedrooms': 'Habitacións',
  'property_listing.bedrooms_short': 'Hab.',
  'property_listing.property_type': 'Tipo de inmoble',
  'property_listing.clear_filters': 'Limpar filtros',
  'property_listing.edit_lifestyle': 'Editar o meu perfil de estilo de vida →',
  'property_listing.verified_badge': 'Verificado InmuFácil',
  'property_listing.extra_labels.pool': 'Piscina',
  'property_listing.extra_labels.lift': 'Ascensor',
  'property_listing.extra_labels.exterior': 'Exterior',
  'property_listing.promo.title': 'Vende directo.',
  'property_listing.promo.subtitle': 'Sen comisións, sen intermediarios. Todo legal, todo seguro.',
  'property_listing.promo.learn_more': 'Saber máis',
};

const propertyListingFr = {
  'property_listing.sqm_unit': 'm²',
  'property_listing.how_works': 'Comment ça marche',
  'property_listing.favorites': 'Favoris',
  'property_listing.filters': 'Filtres',
  'property_listing.publish_property': 'Publier un bien',
  'property_listing.filters_and_search': 'Filtres et recherche',
  'property_listing.lifestyle_sorting_notice': 'Résultats triés par compatibilité avec votre style de vie',
  'property_listing.spain': 'Espagne',
  'property_listing.search': 'Recherche',
  'property_listing.all': 'Tout',
  'property_listing.all_properties': 'Tous les biens',
  'property_listing.properties_in': 'Biens à {}',
  'property_listing.results_count': '{} résultats',
  'property_listing.list_view': 'Liste',
  'property_listing.grid_view': 'Grille',
  'property_listing.map_view': 'Carte',
  'property_listing.no_properties_found': "Nous n'avons trouvé aucun bien dans cette zone.",
  'property_listing.try_changing_filters': "Essayez de modifier les filtres ou de chercher dans une autre localisation.",
  'property_listing.sort_by.newest': 'Plus récents',
  'property_listing.sort_by.relevance': 'Pertinence',
  'property_listing.sort_by.price_low_high': 'Prix : croissant',
  'property_listing.sort_by.price_high_low': 'Prix : décroissant',
  'property_listing.sort_by.label': 'Trier',
  'property_listing.copyright': '© 2026 InmuFácil. Tous droits réservés.',
  'property_listing.location_hint': 'Ville, quartier...',
  'property_listing.search_button': 'Rechercher des biens',
  'property_listing.price_range': 'Fourchette de prix',
  'property_listing.bedrooms': 'Chambres',
  'property_listing.bedrooms_short': 'Ch.',
  'property_listing.property_type': 'Type de bien',
  'property_listing.clear_filters': 'Effacer les filtres',
  'property_listing.edit_lifestyle': 'Modifier mon profil de style de vie →',
  'property_listing.verified_badge': 'Vérifié InmuFácil',
  'property_listing.extra_labels.pool': 'Piscine',
  'property_listing.extra_labels.lift': 'Ascenseur',
  'property_listing.extra_labels.exterior': 'Extérieur',
  'property_listing.promo.title': 'Vendez directement.',
  'property_listing.promo.subtitle': 'Sans commissions, sans intermédiaires. Tout légal, tout sécurisé.',
  'property_listing.promo.learn_more': 'En savoir plus',
};

// ============================================================
// PROPERTY_WIZARD translations
// ============================================================
const propertyWizardCa = {
  'property_wizard.number_hint': 'Número',
  'property_wizard.postal_code_hint': 'CP',
  'property_wizard.photos_card': 'Fotos',
  'property_wizard.condition_title': "Estat de l'immoble",
  'property_wizard.condition_new': 'Obra Nova',
  'property_wizard.condition_new_sub': 'Immoble a estrenar',
  'property_wizard.condition_good': 'Bon Estat',
  'property_wizard.condition_good_sub': 'Llest per entrar a viure',
  'property_wizard.condition_reformed': 'Reformat',
  'property_wizard.condition_reformed_sub': 'Recentment actualitzat',
  'property_wizard.condition_to_reform': 'A Reformar',
  'property_wizard.condition_to_reform_sub': 'Necessita millores estructurals o estètiques',
  'property_wizard.condition_construction': 'En Construcció',
  'property_wizard.condition_construction_sub': 'Projecte en execució',
  'property_wizard.condition_demolish': 'Per Enderrocar',
  'property_wizard.condition_demolish_sub': 'Només valor de sòl/estructura',
  'property_wizard.step_photos': 'Fotos',
  'property_wizard.step_publish': 'Publicar',
  'property_wizard.preview_badge': 'Vista prèvia',
  'property_wizard.bedrooms_short': '{count} Hab.',
  'property_wizard.type_casa': 'Casa',
  'property_wizard.type_local': 'Local',
  'property_wizard.market_ref_detail': '({} EUR/m², {})',
};

const propertyWizardEu = {
  'property_wizard.number_hint': 'Zenbakia',
  'property_wizard.postal_code_hint': 'PK',
  'property_wizard.photos_card': 'Argazkiak',
  'property_wizard.condition_title': 'Higiezinaren egoera',
  'property_wizard.condition_new': 'Obra Berria',
  'property_wizard.condition_new_sub': 'Estreinatu gabeko higiezina',
  'property_wizard.condition_good': 'Egoera Onean',
  'property_wizard.condition_good_sub': 'Bizitzeko prest',
  'property_wizard.condition_reformed': 'Erreformatua',
  'property_wizard.condition_reformed_sub': 'Berriki eguneratua',
  'property_wizard.condition_to_reform': 'Erreformatzeko',
  'property_wizard.condition_to_reform_sub': 'Hobekuntza estrukturalak edo estetikoak behar ditu',
  'property_wizard.condition_construction': 'Eraikitzen',
  'property_wizard.condition_construction_sub': 'Exekuzioan dagoen proiektua',
  'property_wizard.condition_demolish': 'Botatzeko',
  'property_wizard.condition_demolish_sub': 'Lur/egitura balioa soilik',
  'property_wizard.step_photos': 'Argazkiak',
  'property_wizard.step_publish': 'Argitaratu',
  'property_wizard.preview_badge': 'Aurrebista',
  'property_wizard.bedrooms_short': '{count} Log.',
  'property_wizard.type_casa': 'Etxea',
  'property_wizard.type_local': 'Lokala',
  'property_wizard.market_ref_detail': '({} EUR/m², {})',
};

const propertyWizardGl = {
  'property_wizard.number_hint': 'Número',
  'property_wizard.postal_code_hint': 'CP',
  'property_wizard.photos_card': 'Fotos',
  'property_wizard.condition_title': 'Estado do inmoble',
  'property_wizard.condition_new': 'Obra Nova',
  'property_wizard.condition_new_sub': 'Inmoble a estrear',
  'property_wizard.condition_good': 'Bo Estado',
  'property_wizard.condition_good_sub': 'Listo para entrar a vivir',
  'property_wizard.condition_reformed': 'Reformado',
  'property_wizard.condition_reformed_sub': 'Recentemente actualizado',
  'property_wizard.condition_to_reform': 'Para Reformar',
  'property_wizard.condition_to_reform_sub': 'Necesita melloras estruturais ou estéticas',
  'property_wizard.condition_construction': 'En Construción',
  'property_wizard.condition_construction_sub': 'Proxecto en execución',
  'property_wizard.condition_demolish': 'Para Derruír',
  'property_wizard.condition_demolish_sub': 'Só valor de chan/estrutura',
  'property_wizard.step_photos': 'Fotos',
  'property_wizard.step_publish': 'Publicar',
  'property_wizard.preview_badge': 'Vista previa',
  'property_wizard.bedrooms_short': '{count} Hab.',
  'property_wizard.type_casa': 'Casa',
  'property_wizard.type_local': 'Local',
  'property_wizard.market_ref_detail': '({} EUR/m², {})',
};

const propertyWizardFr = {
  'property_wizard.number_hint': 'Numéro',
  'property_wizard.postal_code_hint': 'CP',
  'property_wizard.photos_card': 'Photos',
  'property_wizard.condition_title': 'État du bien',
  'property_wizard.condition_new': 'Neuf',
  'property_wizard.condition_new_sub': 'Bien jamais habité',
  'property_wizard.condition_good': 'Bon État',
  'property_wizard.condition_good_sub': 'Prêt à emménager',
  'property_wizard.condition_reformed': 'Rénové',
  'property_wizard.condition_reformed_sub': 'Récemment rénové',
  'property_wizard.condition_to_reform': 'À Rénover',
  'property_wizard.condition_to_reform_sub': 'Travaux structuraux ou esthétiques nécessaires',
  'property_wizard.condition_construction': 'En Construction',
  'property_wizard.condition_construction_sub': 'Projet en cours',
  'property_wizard.condition_demolish': 'À Démolir',
  'property_wizard.condition_demolish_sub': 'Valeur foncière uniquement',
  'property_wizard.step_photos': 'Photos',
  'property_wizard.step_publish': 'Publier',
  'property_wizard.preview_badge': 'Aperçu',
  'property_wizard.bedrooms_short': '{count} Ch.',
  'property_wizard.type_casa': 'Maison',
  'property_wizard.type_local': 'Local commercial',
  'property_wizard.market_ref_detail': '({} EUR/m², {})',
};

// ============================================================
// Apply all translations
// ============================================================
function applyDict(locale, dict) {
  const data = readJson(locale);
  for (const [key, val] of Object.entries(dict)) {
    setVal(data, key, val);
  }
  writeJson(locale, data);
  console.log('Updated', locale, '(' + Object.keys(dict).length + ' keys)');
}

// ca-ES: Catalan
const allCa = { ...authCa, ...propertyCa, ...propertyListingCa, ...propertyWizardCa };
applyDict('ca-ES', allCa);

// va-ES: Valencian = copy Catalan
applyDict('va-ES', allCa);

// eu-ES: Basque
const allEu = { ...authEu, ...propertyEu, ...propertyListingEu, ...propertyWizardEu };
applyDict('eu-ES', allEu);

// gl-ES: Galician
const allGl = { ...authGl, ...propertyGl, ...propertyListingGl, ...propertyWizardGl };
applyDict('gl-ES', allGl);

// fr-FR: French
const allFr = { ...authFr, ...propertyFr, ...propertyListingFr, ...propertyWizardFr };
applyDict('fr-FR', allFr);

// fr-CA: copy fr-FR
applyDict('fr-CA', allFr);

// en-GB, en-CA: sync en-US auth (those auth keys were already done in prev scripts, but wizard/property_listing may need sync)
// Read en-US and apply same keys to en-GB/en-CA
const enUs = readJson('en-US');
function flatten(obj, prefix) {
  prefix = prefix || '';
  return Object.entries(obj).reduce(function(acc, entry) {
    const k = entry[0], v = entry[1];
    const key = prefix ? prefix + '.' + k : k;
    if (typeof v === 'object' && v !== null && !Array.isArray(v)) {
      Object.assign(acc, flatten(v, key));
    } else {
      acc[key] = v;
    }
    return acc;
  }, {});
}
const enUsFlat = flatten(enUs);
const enSyncKeys = Object.keys(allFr); // same key set
const enGbData = readJson('en-GB');
const enCaData = readJson('en-CA');
for (const key of enSyncKeys) {
  if (enUsFlat[key] !== undefined) {
    setVal(enGbData, key, enUsFlat[key]);
    setVal(enCaData, key, enUsFlat[key]);
  }
}
writeJson('en-GB', enGbData);
writeJson('en-CA', enCaData);
console.log('Updated en-GB and en-CA (synced from en-US)');

console.log('Done: _phase_c_regional_a');
