const fs = require('fs');
const base = 'frontend/assets/translations/';

// All remaining transaction keys (not already translated by _phase_c_transaction.js)
const tx = {
  'en-US': {
    role_buyer: 'BUYER',
    step_offer: 'Offer Sent',
    footer_legal: 'Legal',
    fein_cta_review: 'Review FEIN',
    fein_cta_default: 'Manage FEIN',
    notary_cta_confirm: 'Confirm appointment',
    dialog_withdraw_title: 'Withdraw offer',
    dialog_withdraw_confirm: 'Withdraw offer',
    dialog_new_offer_confirm: 'Send offer',
    solvency_level_silver: 'Silver',
    solvency_none: 'Not verified',
    notaria_time_label: 'Time',
    notaria_select_time: 'Select time',
    notaria_scheduled: 'Appointment scheduled',
    notaria_buyer_label: 'Buyer',
    notaria_detail_notary: 'Notary',
    notaria_other_buyer: 'the buyer',
    notaria_doc_buyer_1: 'Valid DNI / NIE (original)',
    notaria_doc_seller_2: 'Valid DNI / NIE (original)',
    subtitle: 'Track your transaction progress in real time',
    home_btn: 'Home',
    buyer_header_label: 'BUYER',
    in_progress_badge: 'IN PROGRESS',
    offer_sent: 'Offer Sent',
    offer_accepted_step: 'Offer Accepted',
    offer_withdrawn_step: 'Offer Withdrawn',
    offer_rejected_step: 'Offer Rejected',
    seller_accepted_offer: 'Seller accepted the offer',
    seller_counter_offered: 'The seller has made a counter-offer',
    pending_seller_response: 'Pending seller\'s response',
    withdrawn_by_buyer: 'Offer withdrawn by the buyer',
    rejected_by_seller: 'Offer rejected by the seller',
    solvency_title: 'Solvency Verification',
    solvency_validated: 'Validated by InmuFácil Secure-Tech',
    solvency_verifying: 'Verifying buyer\'s solvency',
    solvency_pending_offer: 'Pending offer acceptance',
    complete_passport_btn: 'Complete passport',
    second_buyer_title: 'Identity Verification — 2nd Holder',
    second_buyer_pending_buyer: 'Your second buyer must complete their verification',
    second_buyer_pending_seller: 'Pending: the second buyer must verify their identity',
    second_buyer_confirmed: 'Second holder\'s identity confirmed',
    second_buyer_desc: 'To proceed to the Earnest Money Contract, the second buyer must submit their identity details. Use the button below to add them.',
    add_second_buyer_btn: 'Add 2nd buyer details',
    arras_title: 'Earnest Money Contract',
    arras_signed_both: 'Signed by both parties',
    arras_contract_ready: 'Contract ready — pending signature',
    arras_generating: 'Generating contract with AI...',
    arras_both_done: 'Both interviews complete — generating contract',
    arras_buyer_done_buyer: 'Your interview complete — waiting for seller',
    arras_buyer_done_seller: 'Buyer ready — complete your interview',
    arras_seller_done_seller: 'Your interview complete — waiting for buyer',
    arras_seller_done_buyer: 'Seller ready — complete your interview',
    arras_complete_yours: 'Complete your interview to continue',
    arras_pending_solvency: 'Pending solvency verification',
    arras_review_btn: 'Review contract',
    arras_view_status_btn: 'View status',
    arras_start_btn: 'Start interview',
    arras_complete_btn: 'Complete interview',
    arras_description: 'Both parties must complete their interview. AI will generate the contract when both confirm their answers.',
    appraisal_title: 'Property Appraisal',
    appraisal_done: 'Appraiser\'s report completed',
    appraisal_completed_sub: 'Appraisal completed — report issued',
    appraisal_accepted_buyer: 'Appointment agreed — pending appraiser\'s visit',
    appraisal_accepted_seller: 'Appointment agreed — confirm when the appraiser visits the property',
    appraisal_rejected_buyer: 'Seller proposed an alternative date — pending your response',
    appraisal_rejected_seller: 'Date rejected — pending new proposal from buyer',
    appraisal_proposed_buyer: 'Date proposed — pending seller\'s confirmation',
    appraisal_proposed_seller: 'Buyer proposed a date — pending your response',
    appraisal_pending_buyer: 'Schedule the appraiser\'s visit to continue',
    appraisal_pending_seller: 'Waiting for buyer to propose a date',
    appraisal_pending_arras: 'Pending earnest money signing',
    appraisal_see_confirmed_btn: 'View confirmed appointment',
    appraisal_confirm_visit_btn: 'Confirm appraiser\'s visit',
    appraisal_see_seller_btn: 'View seller\'s proposal',
    appraisal_waiting_buyer_btn: 'View status — waiting for buyer',
    appraisal_see_proposal_btn: 'View sent proposal',
    appraisal_accept_reject_btn: 'Accept or reject proposal',
    appraisal_schedule_btn: 'Schedule appraiser\'s visit',
    fein_confirmed_sub: 'FEIN confirmed — bank has approved the mortgage',
    fein_buyer_pending: 'Your bank must issue the FEIN — confirm when you receive it',
    fein_seller_pending: 'The buyer\'s bank is processing the FEIN',
    fein_pending_appraisal: 'Pending after appraisal — bank issues the FEIN',
    fein_locked: 'Pending earnest money signing',
    fein_confirm_btn: 'Confirm bank FEIN',
    notary_title: 'Notary Signing and Key Handover',
    notary_done: 'Deeds signed and keys handed over',
    notary_pending_fein: 'Pending bank formalization (FEIN)',
    notary_signing_done: 'Signing done — pending key handover',
    notary_scheduled: 'Appointment agreed — pending notary signing',
    notary_buyer_pending: 'Awaiting notary appointment — propose date and location',
    notary_seller_pending: 'Awaiting notary appointment — buyer will choose date',
    notary_view_status: 'View signing status',
    notary_confirm_signing_btn: 'Confirm signing and key handover',
    notary_propose_btn: 'Propose notary appointment',
    notary_view_status_btn: 'View status',
    post_sale_title: 'Post-Sale and Utilities',
    post_sale_subtitle: 'Manage the change of utility account holders',
    post_sale_locked: 'Accessible after notary signing',
    post_sale_btn: 'Manage utilities',
    visit_confirmed_step: 'Visit Confirmed',
    visit_requested_step: 'Visit Requested',
    visit_date_confirmed: 'Appointment agreed: {date}',
    visit_date_pending: 'Proposed: {date} — pending confirmation',
    visit_date_last: 'Last activity: {date}',
    visit_btn: 'View visit schedule',
    talk_to_advisor: 'Talk to a legal adviser',
    withdraw_dialog_title: 'Withdraw offer',
    withdraw_dialog_content: 'Are you sure you want to withdraw your offer? This action cannot be undone.',
    withdraw_btn: 'Withdraw',
    withdraw_ok: 'Offer withdrawn successfully',
    withdraw_error: 'Error withdrawing the offer. Please try again.',
    accept_counter_title: 'Accept counter-offer',
    accept_counter_content: 'Do you accept the counter-offer of {amount} €?',
    accept_counter_ok: 'Offer accepted',
    accept_counter_error: 'Error accepting the offer. Please try again.',
    new_offer_title_part1: 'Make a ',
    new_offer_title_part2: 'new offer',
    new_offer_amount_label: 'New amount',
    new_offer_amount_required: 'Enter an amount',
    new_offer_amount_invalid: 'Invalid amount',
    new_offer_ok: 'Your new offer has been sent',
    new_offer_error: 'Error sending the offer. Please try again.',
    reject_counter_title: 'Reject counter-offer',
    reject_counter_content: 'Do you reject the counter-offer? This action cannot be undone.',
    reject_counter_ok: 'Counter-offer rejected',
    reject_counter_error: 'Error rejecting the offer. Please try again.',
    reject_offer_dialog_title: 'Reject offer',
    reject_offer_dialog_content: 'The buyer will be notified that their offer has been rejected.',
    reject_offer_ok: 'Offer rejected',
    reject_offer_error: 'Error rejecting the offer',
    buyer_solvency_title: 'Buyer\'s solvency',
    buyer_no_passport: 'The buyer does not yet have a solvency passport.',
    buyer_passport_incomplete: 'The buyer has not yet completed the solvency passport.',
    solvency_joint_purchase: 'Joint purchase',
    solvency_knows_extra_costs: 'Aware of additional costs',
    solvency_initial_savings: 'Initial savings',
    solvency_pre_approval: 'Mortgage pre-approval',
    solvency_financing: 'Financing',
    accept_solvency_btn: 'Accept Solvency',
    accept_solvency_ok: 'Solvency accepted',
    accept_solvency_error: 'Error accepting solvency',
    withdraw_offer_btn: 'Withdraw Offer',
    new_offer_btn: 'New Offer',
    footer_help: 'Help',
  },
  'fr-FR': {
    role_buyer: 'ACHETEUR',
    step_offer: 'Offre Envoyée',
    footer_legal: 'Mentions légales',
    fein_cta_review: 'Examiner la FEIN',
    fein_cta_default: 'Gérer la FEIN',
    notary_cta_confirm: 'Confirmer le rendez-vous',
    dialog_withdraw_title: 'Retirer l\'offre',
    dialog_withdraw_confirm: 'Retirer l\'offre',
    dialog_new_offer_confirm: 'Envoyer l\'offre',
    solvency_level_silver: 'Argent',
    solvency_none: 'Non vérifiée',
    notaria_time_label: 'Heure',
    notaria_select_time: 'Sélectionner l\'heure',
    notaria_scheduled: 'Rendez-vous programmé',
    notaria_buyer_label: 'Acheteur',
    notaria_detail_notary: 'Notaire',
    notaria_other_buyer: 'l\'acheteur',
    notaria_doc_buyer_1: 'DNI / NIE en cours de validité (original)',
    notaria_doc_seller_2: 'DNI / NIE en cours de validité (original)',
    subtitle: 'Suivez l\'avancement de votre transaction en temps réel',
    home_btn: 'Accueil',
    buyer_header_label: 'ACHETEUR',
    in_progress_badge: 'EN COURS',
    offer_sent: 'Offre Envoyée',
    offer_accepted_step: 'Offre Acceptée',
    offer_withdrawn_step: 'Offre Retirée',
    offer_rejected_step: 'Offre Refusée',
    seller_accepted_offer: 'Le vendeur a accepté l\'offre',
    seller_counter_offered: 'Le vendeur a fait une contre-offre',
    pending_seller_response: 'En attente de la réponse du vendeur',
    withdrawn_by_buyer: 'Offre retirée par l\'acheteur',
    rejected_by_seller: 'Offre refusée par le vendeur',
    solvency_title: 'Vérification de Solvabilité',
    solvency_validated: 'Validé par InmuFácil Secure-Tech',
    solvency_verifying: 'Vérification de la solvabilité de l\'acheteur',
    solvency_pending_offer: 'En attente d\'acceptation de l\'offre',
    complete_passport_btn: 'Compléter le passeport',
    second_buyer_title: 'Vérification d\'Identité — 2e Titulaire',
    second_buyer_pending_buyer: 'Votre second acheteur doit compléter sa vérification',
    second_buyer_pending_seller: 'En attente : le second acheteur doit vérifier son identité',
    second_buyer_confirmed: 'Identité du second titulaire confirmée',
    second_buyer_desc: 'Pour avancer vers le Contrat d\'Arras, le second acheteur doit soumettre ses informations d\'identité. Utilisez le bouton ci-dessous pour les ajouter.',
    add_second_buyer_btn: 'Ajouter les données du 2e acheteur',
    arras_title: 'Contrat d\'Arras',
    arras_signed_both: 'Signé par les deux parties',
    arras_contract_ready: 'Contrat prêt — en attente de signature',
    arras_generating: 'Génération du contrat par IA...',
    arras_both_done: 'Les deux entretiens terminés — génération du contrat',
    arras_buyer_done_buyer: 'Votre entretien terminé — en attente du vendeur',
    arras_buyer_done_seller: 'Acheteur prêt — complétez votre entretien',
    arras_seller_done_seller: 'Votre entretien terminé — en attente de l\'acheteur',
    arras_seller_done_buyer: 'Vendeur prêt — complétez votre entretien',
    arras_complete_yours: 'Complétez votre entretien pour continuer',
    arras_pending_solvency: 'En attente de vérification de solvabilité',
    arras_review_btn: 'Examiner le contrat',
    arras_view_status_btn: 'Voir le statut',
    arras_start_btn: 'Démarrer l\'entretien',
    arras_complete_btn: 'Compléter l\'entretien',
    arras_description: 'Les deux parties doivent compléter leur entretien. L\'IA générera le contrat quand les deux confirmeront leurs réponses.',
    appraisal_title: 'Expertise Immobilière',
    appraisal_done: 'Rapport de l\'expert terminé',
    appraisal_completed_sub: 'Expertise terminée — rapport émis',
    appraisal_accepted_buyer: 'Rendez-vous convenu — en attente de la visite de l\'expert',
    appraisal_accepted_seller: 'Rendez-vous convenu — confirmez quand l\'expert visite le bien',
    appraisal_rejected_buyer: 'Le vendeur a proposé une date alternative — en attente de votre réponse',
    appraisal_rejected_seller: 'Date refusée — en attente d\'une nouvelle proposition de l\'acheteur',
    appraisal_proposed_buyer: 'Date proposée — en attente de confirmation du vendeur',
    appraisal_proposed_seller: 'L\'acheteur a proposé une date — en attente de votre réponse',
    appraisal_pending_buyer: 'Planifiez la visite de l\'expert pour continuer',
    appraisal_pending_seller: 'En attente que l\'acheteur propose une date',
    appraisal_pending_arras: 'En attente de signature des arrhes',
    appraisal_see_confirmed_btn: 'Voir le rendez-vous confirmé',
    appraisal_confirm_visit_btn: 'Confirmer la visite de l\'expert',
    appraisal_see_seller_btn: 'Voir la proposition du vendeur',
    appraisal_waiting_buyer_btn: 'Voir le statut — en attente de l\'acheteur',
    appraisal_see_proposal_btn: 'Voir la proposition envoyée',
    appraisal_accept_reject_btn: 'Accepter ou refuser la proposition',
    appraisal_schedule_btn: 'Planifier la visite de l\'expert',
    fein_confirmed_sub: 'FEIN confirmée — la banque a approuvé le prêt',
    fein_buyer_pending: 'Votre banque doit émettre la FEIN — confirmez à réception',
    fein_seller_pending: 'La banque de l\'acheteur traite la FEIN',
    fein_pending_appraisal: 'En attente après l\'expertise — la banque émet la FEIN',
    fein_locked: 'En attente de signature des arrhes',
    fein_confirm_btn: 'Confirmer la FEIN bancaire',
    notary_title: 'Signature Notariale et Remise des Clés',
    notary_done: 'Actes signés et clés remises',
    notary_pending_fein: 'En attente de formalisation bancaire (FEIN)',
    notary_signing_done: 'Signature effectuée — en attente de remise des clés',
    notary_scheduled: 'Rendez-vous convenu — en attente de signature chez le notaire',
    notary_buyer_pending: 'En attente de rendez-vous notarial — proposez une date et un lieu',
    notary_seller_pending: 'En attente de rendez-vous notarial — l\'acheteur choisira la date',
    notary_view_status: 'Voir le statut de signature',
    notary_confirm_signing_btn: 'Confirmer signature et remise des clés',
    notary_propose_btn: 'Proposer un rendez-vous notarial',
    notary_view_status_btn: 'Voir le statut',
    post_sale_title: 'Après-Vente et Fournitures',
    post_sale_subtitle: 'Gérez le changement de titulaire des contrats de fournitures',
    post_sale_locked: 'Accessible après la signature chez le notaire',
    post_sale_btn: 'Gérer les fournitures',
    visit_confirmed_step: 'Visite Confirmée',
    visit_requested_step: 'Visite Demandée',
    visit_date_confirmed: 'Rendez-vous convenu : {date}',
    visit_date_pending: 'Proposé : {date} — en attente de confirmation',
    visit_date_last: 'Dernière activité : {date}',
    visit_btn: 'Voir l\'agenda des visites',
    talk_to_advisor: 'Parler à un conseiller juridique',
    withdraw_dialog_title: 'Retirer l\'offre',
    withdraw_dialog_content: 'Êtes-vous sûr de vouloir retirer votre offre ? Cette action est irréversible.',
    withdraw_btn: 'Retirer',
    withdraw_ok: 'Offre retirée avec succès',
    withdraw_error: 'Erreur lors du retrait de l\'offre. Veuillez réessayer.',
    accept_counter_title: 'Accepter la contre-offre',
    accept_counter_content: 'Acceptez-vous la contre-offre de {amount} € ?',
    accept_counter_ok: 'Offre acceptée',
    accept_counter_error: 'Erreur lors de l\'acceptation. Veuillez réessayer.',
    new_offer_title_part1: 'Faire une ',
    new_offer_title_part2: 'nouvelle offre',
    new_offer_amount_label: 'Nouveau montant',
    new_offer_amount_required: 'Saisissez un montant',
    new_offer_amount_invalid: 'Montant invalide',
    new_offer_ok: 'Votre nouvelle offre a été envoyée',
    new_offer_error: 'Erreur lors de l\'envoi. Veuillez réessayer.',
    reject_counter_title: 'Refuser la contre-offre',
    reject_counter_content: 'Refusez-vous la contre-offre ? Cette action est irréversible.',
    reject_counter_ok: 'Contre-offre refusée',
    reject_counter_error: 'Erreur lors du refus. Veuillez réessayer.',
    reject_offer_dialog_title: 'Refuser l\'offre',
    reject_offer_dialog_content: 'L\'acheteur sera informé que son offre a été refusée.',
    reject_offer_ok: 'Offre refusée',
    reject_offer_error: 'Erreur lors du refus de l\'offre',
    buyer_solvency_title: 'Solvabilité de l\'acheteur',
    buyer_no_passport: 'L\'acheteur n\'a pas encore de passeport de solvabilité.',
    buyer_passport_incomplete: 'L\'acheteur n\'a pas encore complété le passeport de solvabilité.',
    solvency_joint_purchase: 'Achat conjoint',
    solvency_knows_extra_costs: 'Connait les frais supplémentaires',
    solvency_initial_savings: 'Épargne initiale',
    solvency_pre_approval: 'Pré-approbation hypothécaire',
    solvency_financing: 'Financement',
    accept_solvency_btn: 'Accepter la Solvabilité',
    accept_solvency_ok: 'Solvabilité acceptée',
    accept_solvency_error: 'Erreur lors de l\'acceptation de la solvabilité',
    withdraw_offer_btn: 'Retirer l\'Offre',
    new_offer_btn: 'Nouvelle Offre',
    footer_help: 'Aide',
  },
  'ca-ES': {
    role_buyer: 'COMPRADOR',
    step_offer: 'Oferta Enviada',
    footer_legal: 'Legal',
    fein_cta_review: 'Revisar FEIN',
    fein_cta_default: 'Gestionar FEIN',
    notary_cta_confirm: 'Confirmar cita',
    dialog_withdraw_title: 'Retirar oferta',
    dialog_withdraw_confirm: 'Retirar oferta',
    dialog_new_offer_confirm: 'Enviar oferta',
    solvency_level_silver: 'Plata',
    solvency_none: 'No verificada',
    notaria_time_label: 'Hora',
    notaria_select_time: 'Seleccionar hora',
    notaria_scheduled: 'Cita programada',
    notaria_buyer_label: 'Comprador',
    notaria_detail_notary: 'Notaria',
    notaria_other_buyer: 'el comprador',
    notaria_doc_buyer_1: 'DNI / NIE en vigor (original)',
    notaria_doc_seller_2: 'DNI / NIE en vigor (original)',
    subtitle: 'Segueix el progrés de la teva transacció en temps real',
    home_btn: 'Inici',
    buyer_header_label: 'COMPRADOR',
    in_progress_badge: 'EN CURS',
    offer_sent: 'Oferta Enviada',
    offer_accepted_step: 'Oferta Acceptada',
    offer_withdrawn_step: 'Oferta Retirada',
    offer_rejected_step: 'Oferta Rebutjada',
    seller_accepted_offer: 'El venedor ha acceptat l\'oferta',
    seller_counter_offered: 'El venedor ha fet una contraoferta',
    pending_seller_response: 'Pendent de resposta del venedor',
    withdrawn_by_buyer: 'Oferta retirada pel comprador',
    rejected_by_seller: 'Oferta rebutjada pel venedor',
    solvency_title: 'Verificació de Solvència',
    solvency_validated: 'Validat per InmuFácil Secure-Tech',
    solvency_verifying: 'Verificant solvència del comprador',
    solvency_pending_offer: 'Pendent d\'acceptació d\'oferta',
    complete_passport_btn: 'Completar passaport',
    second_buyer_title: 'Verificació d\'Identitat — 2n Titular',
    second_buyer_pending_buyer: 'El teu segon comprador ha de completar la seva verificació',
    second_buyer_pending_seller: 'Pendent: el segon comprador ha de verificar la seva identitat',
    second_buyer_confirmed: 'Identitat del segon titular confirmada',
    second_buyer_desc: 'Per avançar al contracte d\'Arres, el segon comprador ha d\'enviar les seves dades d\'identitat. Utilitza el botó de sota per afegir-les.',
    add_second_buyer_btn: 'Afegir dades del 2n comprador',
    arras_title: 'Contracte d\'Arres',
    arras_signed_both: 'Signat per ambdues parts',
    arras_contract_ready: 'Contracte llest — pendent de signatura',
    arras_generating: 'Generant contracte amb IA...',
    arras_both_done: 'Ambdues entrevistes completades — generant contracte',
    arras_buyer_done_buyer: 'La teva entrevista completada — esperant el venedor',
    arras_buyer_done_seller: 'Comprador llest — completa la teva entrevista',
    arras_seller_done_seller: 'La teva entrevista completada — esperant el comprador',
    arras_seller_done_buyer: 'Venedor llest — completa la teva entrevista',
    arras_complete_yours: 'Completa la teva entrevista per continuar',
    arras_pending_solvency: 'Pendent de verificació de solvència',
    arras_review_btn: 'Revisar contracte',
    arras_view_status_btn: 'Veure estat',
    arras_start_btn: 'Iniciar entrevista',
    arras_complete_btn: 'Completar entrevista',
    arras_description: 'Ambdues parts han de completar la seva entrevista. La IA generarà el contracte quan ambdues confirmin les seves respostes.',
    appraisal_title: 'Taxació de l\'Habitatge',
    appraisal_done: 'Informe del taxador completat',
    appraisal_completed_sub: 'Taxació completada — informe emès',
    appraisal_accepted_buyer: 'Cita acordada — pendent de visita del taxador',
    appraisal_accepted_seller: 'Cita acordada — confirma quan el taxador visiti l\'habitatge',
    appraisal_rejected_buyer: 'Venedor va proposar data alternativa — pendent de la teva resposta',
    appraisal_rejected_seller: 'Data rebutjada — pendent de nova proposta del comprador',
    appraisal_proposed_buyer: 'Data proposada — pendent de confirmació del venedor',
    appraisal_proposed_seller: 'Comprador va proposar una data — pendent de la teva resposta',
    appraisal_pending_buyer: 'Programa la visita del taxador per continuar',
    appraisal_pending_seller: 'Pendent que el comprador proposi una data',
    appraisal_pending_arras: 'Pendent de signatura d\'arres',
    appraisal_see_confirmed_btn: 'Veure cita confirmada',
    appraisal_confirm_visit_btn: 'Confirmar visita del taxador',
    appraisal_see_seller_btn: 'Veure proposta del venedor',
    appraisal_waiting_buyer_btn: 'Veure estat — esperant comprador',
    appraisal_see_proposal_btn: 'Veure proposta enviada',
    appraisal_accept_reject_btn: 'Acceptar o rebutjar proposta',
    appraisal_schedule_btn: 'Programar visita del taxador',
    fein_confirmed_sub: 'FEIN confirmada — banc ha aprovat la hipoteca',
    fein_buyer_pending: 'El teu banc ha d\'emetre la FEIN — confirma quan la rebis',
    fein_seller_pending: 'El banc del comprador està tramitant la FEIN',
    fein_pending_appraisal: 'Pendent després de taxació — banc emet la FEIN',
    fein_locked: 'Pendent de signatura d\'arres',
    fein_confirm_btn: 'Confirmar FEIN del banc',
    notary_title: 'Signatura a Notaria i Lliurament de Claus',
    notary_done: 'Escriptures signades i claus lliurades',
    notary_pending_fein: 'Pendent de formalització bancària (FEIN)',
    notary_signing_done: 'Signatura realitzada — pendent de lliurament de claus',
    notary_scheduled: 'Cita acordada — pendent de signatura a notaria',
    notary_buyer_pending: 'A l\'espera de cita a notaria — proposa data i lloc',
    notary_seller_pending: 'A l\'espera de cita a notaria — el comprador triarà la data',
    notary_view_status: 'Veure estat de la signatura',
    notary_confirm_signing_btn: 'Confirmar signatura i lliurament de claus',
    notary_propose_btn: 'Proposar cita a notaria',
    notary_view_status_btn: 'Veure estat',
    post_sale_title: 'Post-Venda i Subministraments',
    post_sale_subtitle: 'Gestiona el canvi de titularitat dels subministraments',
    post_sale_locked: 'Accessible després de la signatura a notaria',
    post_sale_btn: 'Gestionar subministraments',
    visit_confirmed_step: 'Visita Confirmada',
    visit_requested_step: 'Visita Sol·licitada',
    visit_date_confirmed: 'Cita acordada: {date}',
    visit_date_pending: 'Proposta: {date} — pendent de confirmació',
    visit_date_last: 'Última activitat: {date}',
    visit_btn: 'Veure agenda de visites',
    talk_to_advisor: 'Parlar amb un assessor legal',
    withdraw_dialog_title: 'Retirar oferta',
    withdraw_dialog_content: 'Segur que vols retirar la teva oferta? Aquesta acció no es pot desfer.',
    withdraw_btn: 'Retirar',
    withdraw_ok: 'Oferta retirada correctament',
    withdraw_error: 'Error en retirar l\'oferta. Torna-ho a intentar.',
    accept_counter_title: 'Acceptar contraoferta',
    accept_counter_content: 'Acceptes la contraoferta de {amount} €?',
    accept_counter_ok: 'Oferta acceptada',
    accept_counter_error: 'Error en acceptar l\'oferta. Torna-ho a intentar.',
    new_offer_title_part1: 'Fer ',
    new_offer_title_part2: 'nova oferta',
    new_offer_amount_label: 'Nou import',
    new_offer_amount_required: 'Introdueix un import',
    new_offer_amount_invalid: 'Import no vàlid',
    new_offer_ok: 'La teva nova oferta ha estat enviada',
    new_offer_error: 'Error en enviar l\'oferta. Torna-ho a intentar.',
    reject_counter_title: 'Rebutjar contraoferta',
    reject_counter_content: 'Rebutges la contraoferta? Aquesta acció no es pot desfer.',
    reject_counter_ok: 'Contraoferta rebutjada',
    reject_counter_error: 'Error en rebutjar l\'oferta. Torna-ho a intentar.',
    reject_offer_dialog_title: 'Rebutjar oferta',
    reject_offer_dialog_content: 'El comprador serà notificat que la seva oferta ha estat rebutjada.',
    reject_offer_ok: 'Oferta rebutjada',
    reject_offer_error: 'Error en rebutjar l\'oferta',
    buyer_solvency_title: 'Solvència del comprador',
    buyer_no_passport: 'El comprador encara no té passaport de solvència.',
    buyer_passport_incomplete: 'El comprador encara no ha completat el passaport de solvència.',
    solvency_joint_purchase: 'Compra conjunta',
    solvency_knows_extra_costs: 'Coneix les despeses addicionals',
    solvency_initial_savings: 'Estalvis inicials',
    solvency_pre_approval: 'Pre-aprovació hipotecària',
    solvency_financing: 'Finançament',
    accept_solvency_btn: 'Acceptar Solvència',
    accept_solvency_ok: 'Solvència acceptada',
    accept_solvency_error: 'Error en acceptar la solvència',
    withdraw_offer_btn: 'Retirar Oferta',
    new_offer_btn: 'Nova Oferta',
    footer_help: 'Ajuda',
  },
  'gl-ES': {
    role_buyer: 'COMPRADOR',
    step_offer: 'Oferta Enviada',
    footer_legal: 'Legal',
    fein_cta_review: 'Revisar FEIN',
    fein_cta_default: 'Xestionar FEIN',
    notary_cta_confirm: 'Confirmar cita',
    dialog_withdraw_title: 'Retirar oferta',
    dialog_withdraw_confirm: 'Retirar oferta',
    dialog_new_offer_confirm: 'Enviar oferta',
    solvency_level_silver: 'Prata',
    solvency_none: 'Non verificada',
    notaria_time_label: 'Hora',
    notaria_select_time: 'Seleccionar hora',
    notaria_scheduled: 'Cita programada',
    notaria_buyer_label: 'Comprador',
    notaria_detail_notary: 'Notaría',
    notaria_other_buyer: 'o comprador',
    notaria_doc_buyer_1: 'DNI / NIE en vigor (orixinal)',
    notaria_doc_seller_2: 'DNI / NIE en vigor (orixinal)',
    subtitle: 'Segue o progreso da túa transacción en tempo real',
    home_btn: 'Inicio',
    buyer_header_label: 'COMPRADOR',
    in_progress_badge: 'EN CURSO',
    offer_sent: 'Oferta Enviada',
    offer_accepted_step: 'Oferta Aceptada',
    offer_withdrawn_step: 'Oferta Retirada',
    offer_rejected_step: 'Oferta Rexeitada',
    seller_accepted_offer: 'O vendedor aceptou a oferta',
    seller_counter_offered: 'O vendedor fixo unha contraoferta',
    pending_seller_response: 'Pendente de resposta do vendedor',
    withdrawn_by_buyer: 'Oferta retirada polo comprador',
    rejected_by_seller: 'Oferta rexeitada polo vendedor',
    solvency_title: 'Verificación de Solvencia',
    solvency_validated: 'Validado por InmuFácil Secure-Tech',
    solvency_verifying: 'Verificando solvencia do comprador',
    solvency_pending_offer: 'Pendente de aceptación de oferta',
    complete_passport_btn: 'Completar pasaporte',
    second_buyer_title: 'Verificación de Identidade — 2.º Titular',
    second_buyer_pending_buyer: 'O teu segundo comprador debe completar a súa verificación',
    second_buyer_pending_seller: 'Pendente: o segundo comprador debe verificar a súa identidade',
    second_buyer_confirmed: 'Identidade do segundo titular confirmada',
    second_buyer_desc: 'Para avanzar ao contrato de Arras, o segundo comprador debe enviar os seus datos de identidade. Usa o botón de abaixo para engadilos.',
    add_second_buyer_btn: 'Engadir datos do 2.º comprador',
    arras_title: 'Contrato de Arras',
    arras_signed_both: 'Asinado por ambas as partes',
    arras_contract_ready: 'Contrato listo — pendente de sinatura',
    arras_generating: 'Xerando contrato con IA...',
    arras_both_done: 'Ambas entrevistas completadas — xerando contrato',
    arras_buyer_done_buyer: 'A túa entrevista completada — agardando o vendedor',
    arras_buyer_done_seller: 'Comprador listo — completa a túa entrevista',
    arras_seller_done_seller: 'A túa entrevista completada — agardando o comprador',
    arras_seller_done_buyer: 'Vendedor listo — completa a túa entrevista',
    arras_complete_yours: 'Completa a túa entrevista para continuar',
    arras_pending_solvency: 'Pendente de verificación de solvencia',
    arras_review_btn: 'Revisar contrato',
    arras_view_status_btn: 'Ver estado',
    arras_start_btn: 'Iniciar entrevista',
    arras_complete_btn: 'Completar entrevista',
    arras_description: 'Ambas partes deben completar a súa entrevista. A IA xerará o contrato cando ambas confirmen as súas respostas.',
    appraisal_title: 'Taxación da Vivenda',
    appraisal_done: 'Informe do taxador completado',
    appraisal_completed_sub: 'Taxación completada — informe emitido',
    appraisal_accepted_buyer: 'Cita acordada — pendente de visita do taxador',
    appraisal_accepted_seller: 'Cita acordada — confirma cando o taxador visite a vivenda',
    appraisal_rejected_buyer: 'O vendedor propuxo data alternativa — pendente da túa resposta',
    appraisal_rejected_seller: 'Data rexeitada — pendente de nova proposta do comprador',
    appraisal_proposed_buyer: 'Data proposta — pendente de confirmación do vendedor',
    appraisal_proposed_seller: 'O comprador propuxo unha data — pendente da túa resposta',
    appraisal_pending_buyer: 'Programa a visita do taxador para continuar',
    appraisal_pending_seller: 'Pendente de que o comprador propoña unha data',
    appraisal_pending_arras: 'Pendente de sinatura de arras',
    appraisal_see_confirmed_btn: 'Ver cita confirmada',
    appraisal_confirm_visit_btn: 'Confirmar visita do taxador',
    appraisal_see_seller_btn: 'Ver proposta do vendedor',
    appraisal_waiting_buyer_btn: 'Ver estado — agardando comprador',
    appraisal_see_proposal_btn: 'Ver proposta enviada',
    appraisal_accept_reject_btn: 'Aceptar ou rexeitar proposta',
    appraisal_schedule_btn: 'Programar visita do taxador',
    fein_confirmed_sub: 'FEIN confirmada — banco aprobou a hipoteca',
    fein_buyer_pending: 'O teu banco debe emitir a FEIN — confirma cando a recibas',
    fein_seller_pending: 'O banco do comprador está tramitando a FEIN',
    fein_pending_appraisal: 'Pendente tras taxación — banco emite a FEIN',
    fein_locked: 'Pendente de sinatura de arras',
    fein_confirm_btn: 'Confirmar FEIN do banco',
    notary_title: 'Sinatura en Notaría e Entrega de Chaves',
    notary_done: 'Escrituras asinadas e chaves entregadas',
    notary_pending_fein: 'Pendente de formalización bancaria (FEIN)',
    notary_signing_done: 'Sinatura realizada — pendente de entrega de chaves',
    notary_scheduled: 'Cita acordada — pendente de sinatura na notaría',
    notary_buyer_pending: 'Á espera de cita na notaría — propón data e lugar',
    notary_seller_pending: 'Á espera de cita na notaría — o comprador elixirá data',
    notary_view_status: 'Ver estado da sinatura',
    notary_confirm_signing_btn: 'Confirmar sinatura e entrega de chaves',
    notary_propose_btn: 'Propor cita na notaría',
    notary_view_status_btn: 'Ver estado',
    post_sale_title: 'Post-Venda e Subministracións',
    post_sale_subtitle: 'Xestiona o cambio de titularidade das subministracións',
    post_sale_locked: 'Accesible tras a sinatura na notaría',
    post_sale_btn: 'Xestionar subministracións',
    visit_confirmed_step: 'Visita Confirmada',
    visit_requested_step: 'Visita Solicitada',
    visit_date_confirmed: 'Cita acordada: {date}',
    visit_date_pending: 'Proposta: {date} — pendente de confirmación',
    visit_date_last: 'Última actividade: {date}',
    visit_btn: 'Ver axenda de visitas',
    talk_to_advisor: 'Falar cun asesor legal',
    withdraw_dialog_title: 'Retirar oferta',
    withdraw_dialog_content: 'Seguro que queres retirar a túa oferta? Esta acción non se pode desfacer.',
    withdraw_btn: 'Retirar',
    withdraw_ok: 'Oferta retirada correctamente',
    withdraw_error: 'Erro ao retirar a oferta. Téntao de novo.',
    accept_counter_title: 'Aceptar contraoferta',
    accept_counter_content: 'Aceptas a contraoferta de {amount} €?',
    accept_counter_ok: 'Oferta aceptada',
    accept_counter_error: 'Erro ao aceptar a oferta. Téntao de novo.',
    new_offer_title_part1: 'Facer ',
    new_offer_title_part2: 'nova oferta',
    new_offer_amount_label: 'Novo importe',
    new_offer_amount_required: 'Introduce un importe',
    new_offer_amount_invalid: 'Importe non válido',
    new_offer_ok: 'A túa nova oferta foi enviada',
    new_offer_error: 'Erro ao enviar a oferta. Téntao de novo.',
    reject_counter_title: 'Rexeitar contraoferta',
    reject_counter_content: 'Rexeitas a contraoferta? Esta acción non se pode desfacer.',
    reject_counter_ok: 'Contraoferta rexeitada',
    reject_counter_error: 'Erro ao rexeitar a oferta. Téntao de novo.',
    reject_offer_dialog_title: 'Rexeitar oferta',
    reject_offer_dialog_content: 'O comprador será notificado de que a súa oferta foi rexeitada.',
    reject_offer_ok: 'Oferta rexeitada',
    reject_offer_error: 'Erro ao rexeitar a oferta',
    buyer_solvency_title: 'Solvencia do comprador',
    buyer_no_passport: 'O comprador aínda non ten pasaporte de solvencia.',
    buyer_passport_incomplete: 'O comprador aínda non completou o pasaporte de solvencia.',
    solvency_joint_purchase: 'Compra conxunta',
    solvency_knows_extra_costs: 'Coñece gastos adicionais',
    solvency_initial_savings: 'Aforros iniciais',
    solvency_pre_approval: 'Preaprobación hipotecaria',
    solvency_financing: 'Financiamento',
    accept_solvency_btn: 'Aceptar Solvencia',
    accept_solvency_ok: 'Solvencia aceptada',
    accept_solvency_error: 'Erro ao aceptar a solvencia',
    withdraw_offer_btn: 'Retirar Oferta',
    new_offer_btn: 'Nova Oferta',
    footer_help: 'Axuda',
  },
  'eu-ES': {
    role_buyer: 'EROSLEA',
    step_offer: 'Eskaintza Bidalita',
    footer_legal: 'Legala',
    fein_cta_review: 'FEIN berrikusi',
    fein_cta_default: 'FEIN kudeatu',
    notary_cta_confirm: 'Hitzordua baieztatu',
    dialog_withdraw_title: 'Eskaintza erretiratu',
    dialog_withdraw_confirm: 'Eskaintza erretiratu',
    dialog_new_offer_confirm: 'Eskaintza bidali',
    solvency_level_silver: 'Zilarra',
    solvency_none: 'Ez egiaztatuta',
    notaria_time_label: 'Ordua',
    notaria_select_time: 'Ordua hautatu',
    notaria_scheduled: 'Hitzordua programatuta',
    notaria_buyer_label: 'Eroslea',
    notaria_detail_notary: 'Notarioa',
    notaria_other_buyer: 'eroslea',
    notaria_doc_buyer_1: 'NAA / NAE indarrean (originala)',
    notaria_doc_seller_2: 'NAA / NAE indarrean (originala)',
    subtitle: 'Jarraitu zure transakzioaren aurrerapena denbora errealean',
    home_btn: 'Hasiera',
    buyer_header_label: 'EROSLEA',
    in_progress_badge: 'ABIAN',
    offer_sent: 'Eskaintza Bidalita',
    offer_accepted_step: 'Eskaintza Onartuta',
    offer_withdrawn_step: 'Eskaintza Erretiratu',
    offer_rejected_step: 'Eskaintza Ukatuta',
    seller_accepted_offer: 'Saltzaileak eskaintza onartu du',
    seller_counter_offered: 'Saltzaileak kontraeskaintza egin du',
    pending_seller_response: 'Saltzailearen erantzunaren zain',
    withdrawn_by_buyer: 'Erosleak erretiratu du eskaintza',
    rejected_by_seller: 'Saltzaileak ukatu du eskaintza',
    solvency_title: 'Solbentzia Egiaztapena',
    solvency_validated: 'InmuFácil Secure-Tech-ek balioztatuta',
    solvency_verifying: 'Eroslearen solbentzia egiaztatzen',
    solvency_pending_offer: 'Eskaintzaren onarpena zain',
    complete_passport_btn: 'Pasaportea osatu',
    second_buyer_title: 'Nortasun Egiaztapena — 2. Titularra',
    second_buyer_pending_buyer: 'Zure bigarren erosleak egiaztapena osatu behar du',
    second_buyer_pending_seller: 'Zain: bigarren erosleak bere nortasuna egiaztatu behar du',
    second_buyer_confirmed: 'Bigarren titulariaren nortasuna baieztatuta',
    second_buyer_desc: 'Arras Kontratura aurreratzeko, bigarren erosleak bere nortasun-datuak bidali behar ditu.',
    add_second_buyer_btn: '2. eroslearen datuak gehitu',
    arras_title: 'Arras Kontratua',
    arras_signed_both: 'Bi aldeak sinatu dute',
    arras_contract_ready: 'Kontratua prest — sinaduraren zain',
    arras_generating: 'Kontratua IArekin sortzen...',
    arras_both_done: 'Bi elkarrizketak osatuta — kontratua sortzen',
    arras_buyer_done_buyer: 'Zure elkarrizketa osatuta — saltzailearen zain',
    arras_buyer_done_seller: 'Eroslea prest — osatu zure elkarrizketa',
    arras_seller_done_seller: 'Zure elkarrizketa osatuta — eroslearen zain',
    arras_seller_done_buyer: 'Saltzailea prest — osatu zure elkarrizketa',
    arras_complete_yours: 'Osatu zure elkarrizketa jarraitzeko',
    arras_pending_solvency: 'Solbentzia egiaztatzearen zain',
    arras_review_btn: 'Kontratua berrikusi',
    arras_view_status_btn: 'Egoera ikusi',
    arras_start_btn: 'Elkarrizketa hasi',
    arras_complete_btn: 'Elkarrizketa osatu',
    arras_description: 'Bi aldeek beren elkarrizketa osatu behar dute. IAk kontratua sortuko du biek erantzunak baieztatzen dituztenean.',
    appraisal_title: 'Etxebizitzaren Balorazioa',
    appraisal_done: 'Baloratzailearen txostena osatuta',
    appraisal_completed_sub: 'Balorazioa osatuta — txostena igortuta',
    appraisal_accepted_buyer: 'Hitzordua adostuta — baloratzailearen bisitaren zain',
    appraisal_accepted_seller: 'Hitzordua adostuta — baiezta ezazu baloratzaileak etxea bisitatzen duenean',
    appraisal_rejected_buyer: 'Saltzaileak data alternatiboa proposatu du — zure erantzunaren zain',
    appraisal_rejected_seller: 'Data ukatuta — eroslearen proposamen berriaren zain',
    appraisal_proposed_buyer: 'Data proposatuta — saltzailearen baieztatzearen zain',
    appraisal_proposed_seller: 'Erosleak data bat proposatu du — zure erantzunaren zain',
    appraisal_pending_buyer: 'Programa baloratzailearen bisita jarraitzeko',
    appraisal_pending_seller: 'Erosleak data proposatzearen zain',
    appraisal_pending_arras: 'Arrasen sinaduraren zain',
    appraisal_see_confirmed_btn: 'Baieztatutako hitzordua ikusi',
    appraisal_confirm_visit_btn: 'Baloratzailearen bisita baieztatu',
    appraisal_see_seller_btn: 'Saltzailearen proposamena ikusi',
    appraisal_waiting_buyer_btn: 'Egoera ikusi — eroslearen zain',
    appraisal_see_proposal_btn: 'Bidalitako proposamena ikusi',
    appraisal_accept_reject_btn: 'Proposamena onartu edo ukatu',
    appraisal_schedule_btn: 'Baloratzailearen bisita programatu',
    fein_confirmed_sub: 'FEIN baieztatuta — bankuak hipoteka onartu du',
    fein_buyer_pending: 'Zure bankuak FEIN igorri behar du — baiezta ezazu jaso ondoren',
    fein_seller_pending: 'Eroslearen bankua FEIN tramitatu du',
    fein_pending_appraisal: 'Balorazioaren ondoren zain — bankuak FEIN igortzen du',
    fein_locked: 'Arrasen sinaduraren zain',
    fein_confirm_btn: 'Bankuko FEIN baieztatu',
    notary_title: 'Notarioan Sinadura eta Gakoen Entrega',
    notary_done: 'Eskriturak sinatuta eta gakoak emanda',
    notary_pending_fein: 'Banku-formalizazioaren (FEIN) zain',
    notary_signing_done: 'Sinadura eginda — gakoen entregaren zain',
    notary_scheduled: 'Hitzordua adostuta — notarioan sinaduraren zain',
    notary_buyer_pending: 'Notario-hitzordua zain — proposatu data eta lekua',
    notary_seller_pending: 'Notario-hitzordua zain — erosleak data aukeratuko du',
    notary_view_status: 'Sinaduraren egoera ikusi',
    notary_confirm_signing_btn: 'Sinadura eta gakoen entrega baieztatu',
    notary_propose_btn: 'Notario-hitzordua proposatu',
    notary_view_status_btn: 'Egoera ikusi',
    post_sale_title: 'Saltze Ostekoa eta Hornidura',
    post_sale_subtitle: 'Kudeatu horniduraren titularra aldatzea',
    post_sale_locked: 'Notarioan sinatu ondoren eskuragarri',
    post_sale_btn: 'Hornidura kudeatu',
    visit_confirmed_step: 'Bisita Baieztatuta',
    visit_requested_step: 'Bisita Eskatuta',
    visit_date_confirmed: 'Hitzordua adostuta: {date}',
    visit_date_pending: 'Proposatuta: {date} — baieztatzearen zain',
    visit_date_last: 'Azken jarduera: {date}',
    visit_btn: 'Bisiten agenda ikusi',
    talk_to_advisor: 'Lege-aholkulari batekin hitz egin',
    withdraw_dialog_title: 'Eskaintza erretiratu',
    withdraw_dialog_content: 'Ziur zaude zure eskaintza erretiratu nahi duzula? Ekintza hau ezin da desegin.',
    withdraw_btn: 'Erretiratu',
    withdraw_ok: 'Eskaintza behar bezala erretiratu da',
    withdraw_error: 'Errorea eskaintza erretiratzean. Saiatu berriro.',
    accept_counter_title: 'Kontraeskaintza onartu',
    accept_counter_content: '{amount} €ko kontraeskaintza onartzen al duzu?',
    accept_counter_ok: 'Eskaintza onartuta',
    accept_counter_error: 'Errorea eskaintza onartzean. Saiatu berriro.',
    new_offer_title_part1: 'Eskaintza ',
    new_offer_title_part2: 'berria egin',
    new_offer_amount_label: 'Zenbateko berria',
    new_offer_amount_required: 'Sartu zenbateko bat',
    new_offer_amount_invalid: 'Zenbateko ez baliozkoa',
    new_offer_ok: 'Zure eskaintza berria bidali da',
    new_offer_error: 'Errorea eskaintza bidaltzean. Saiatu berriro.',
    reject_counter_title: 'Kontraeskaintza ukatu',
    reject_counter_content: 'Kontraeskaintza ukatzen al duzu? Ekintza hau ezin da desegin.',
    reject_counter_ok: 'Kontraeskaintza ukatuta',
    reject_counter_error: 'Errorea kontraeskaintza ukatzen. Saiatu berriro.',
    reject_offer_dialog_title: 'Eskaintza ukatu',
    reject_offer_dialog_content: 'Erosleak jakinaraziko zaio bere eskaintza ukatu dela.',
    reject_offer_ok: 'Eskaintza ukatuta',
    reject_offer_error: 'Errorea eskaintza ukatzen',
    buyer_solvency_title: 'Eroslearen solbentzia',
    buyer_no_passport: 'Erosleak oraindik ez du solbentzia-pasaporterik.',
    buyer_passport_incomplete: 'Erosleak oraindik ez du solbentzia-pasaportea osatu.',
    solvency_joint_purchase: 'Erosketa bateratua',
    solvency_knows_extra_costs: 'Kostu gehigarriak ezagutzen ditu',
    solvency_initial_savings: 'Hasierako aurrezkiak',
    solvency_pre_approval: 'Hipoteka-aurre-onarpena',
    solvency_financing: 'Finantzaketa',
    accept_solvency_btn: 'Solbentzia Onartu',
    accept_solvency_ok: 'Solbentzia onartuta',
    accept_solvency_error: 'Errorea solbentzia onartzean',
    withdraw_offer_btn: 'Eskaintza Erretiratu',
    new_offer_btn: 'Eskaintza Berria',
    footer_help: 'Laguntza',
  },
};

// va-ES = ca-ES (same content)
tx['va-ES'] = { ...tx['ca-ES'] };
// en-GB, en-CA = en-US
tx['en-GB'] = { ...tx['en-US'] };
tx['en-CA'] = { ...tx['en-US'] };
// fr-CA = fr-FR
tx['fr-CA'] = { ...tx['fr-FR'] };

const langs = ['en-US','en-GB','en-CA','fr-FR','fr-CA','ca-ES','va-ES','eu-ES','gl-ES'];

langs.forEach(lang => {
  const fp = base + lang + '.json';
  const json = JSON.parse(fs.readFileSync(fp, 'utf8'));
  if (!json.transaction) json.transaction = {};
  Object.entries(tx[lang]).forEach(([k, v]) => {
    json.transaction[k] = v;
  });
  fs.writeFileSync(fp, JSON.stringify(json, null, 2), 'utf8');
  console.log(lang + ': transaction-2 updated');
});
