const fs = require('fs');
const base = 'C:/Users/Os/.gemini/antigravity/scratch/InmuFacil_Project/frontend/assets/translations/';

function setVal(obj, path, val) {
  const parts = path.split('.');
  const last = parts.pop();
  const target = parts.reduce((o, k) => { if (!o[k]) o[k] = {}; return o[k]; }, obj);
  target[last] = val;
}

const translations = {
  // PROFILE
  'profile.change_password': { 'en-US':'Change Password','fr-FR':'Changer de mot de passe','ca-ES':'Canviar contrasenya','eu-ES':'Pasahitza aldatu','gl-ES':'Cambiar contrasinal' },
  'profile.tab_my_profile': { 'en-US':'My Profile','fr-FR':'Mon Profil','ca-ES':'El meu Perfil','eu-ES':'Nire Profila','gl-ES':'O meu Perfil' },
  'profile.tab_properties': { 'en-US':'My Properties','fr-FR':'Mes Biens','ca-ES':'Les meves Propietats','eu-ES':'Nire Propietateak','gl-ES':'As miñas Propiedades' },
  'profile.tab_offers': { 'en-US':'My Offers','fr-FR':'Mes Offres','ca-ES':'Les meves Ofertes','eu-ES':'Nire Eskaintzak','gl-ES':'As miñas Ofertas' },
  'profile.tab_visits': { 'en-US':'My Visits','fr-FR':'Mes Visites','ca-ES':'Les meves Visites','eu-ES':'Nire Bisitak','gl-ES':'As miñas Visitas' },
  'profile.tab_messages': { 'en-US':'Messages','fr-FR':'Messages','ca-ES':'Missatges','eu-ES':'Mezuak','gl-ES':'Mensaxes' },
  'profile.personal_info_title': { 'en-US':'Personal Information','fr-FR':'Informations Personnelles','ca-ES':'Informació Personal','eu-ES':'Informazio Pertsonala','gl-ES':'Información Persoal' },
  'profile.notifications_title': { 'en-US':'Notifications','fr-FR':'Notifications','ca-ES':'Notificacions','eu-ES':'Jakinarazpenak','gl-ES':'Notificacións' },
  'profile.email_notifications_label': { 'en-US':'Email Notifications','fr-FR':'Notifications par email','ca-ES':'Notificacions per email','eu-ES':'Posta elektronikoko jakinarazpenak','gl-ES':'Notificacións por email' },
  'profile.email_notifications_on': { 'en-US':'You will receive alerts by email','fr-FR':'Vous recevrez des alertes par email','ca-ES':'Rebràs avisos al teu correu','eu-ES':'Alertak posta elektronikoz jasoko dituzu','gl-ES':'Recibirás avisos no teu correo' },
  'profile.email_notifications_off': { 'en-US':'You will not receive email alerts','fr-FR':'Vous ne recevrez pas d\'alertes par email','ca-ES':'No rebràs avisos per email','eu-ES':'Ez dituzu posta elektronikoko alertak jasoko','gl-ES':'Non recibirás avisos por email' },
  'profile.security_title': { 'en-US':'Security','fr-FR':'Sécurité','ca-ES':'Seguretat','eu-ES':'Segurtasuna','gl-ES':'Seguridade' },
  'profile.password_label': { 'en-US':'Password','fr-FR':'Mot de passe','ca-ES':'Contrasenya','eu-ES':'Pasahitza','gl-ES':'Contrasinal' },
  'profile.password_update_hint': { 'en-US':'Update your password regularly','fr-FR':'Mettez à jour votre mot de passe régulièrement','ca-ES':'Actualitza la teva contrasenya regularment','eu-ES':'Eguneratu zure pasahitza aldizka','gl-ES':'Actualiza o teu contrasinal regularmente' },
  'profile.suspend_account': { 'en-US':'Suspend Account','fr-FR':'Suspendre le Compte','ca-ES':'Suspendre el Compte','eu-ES':'Kontua Eten','gl-ES':'Suspender Conta' },
  'profile.suspend_hint': { 'en-US':'Your account will temporarily become invisible.','fr-FR':'Votre compte deviendra temporairement invisible.','ca-ES':'El teu compte deixarà de ser visible temporalment.','eu-ES':'Zure kontua aldi baterako ikusezin bihurtuko da.','gl-ES':'A túa conta deixará de ser visible temporalmente.' },
  'profile.reactivate': { 'en-US':'Reactivate','fr-FR':'Réactiver','ca-ES':'Reactivar','eu-ES':'Berriro aktibatu','gl-ES':'Reactivar' },
  'profile.suspend_button': { 'en-US':'Suspend','fr-FR':'Suspendre','ca-ES':'Suspendre','eu-ES':'Eten','gl-ES':'Suspender' },
  'profile.delete_account': { 'en-US':'Delete Account','fr-FR':'Supprimer le Compte','ca-ES':'Eliminar Compte','eu-ES':'Kontua Ezabatu','gl-ES':'Eliminar Conta' },
  'profile.delete_hint': { 'en-US':'Permanent action. You will lose all your data.','fr-FR':'Action permanente. Vous perdrez toutes vos données.','ca-ES':'Acció permanent. Perdràs totes les teves dades.','eu-ES':'Ekintza iraunkorra. Zure datu guztiak galduko dituzu.','gl-ES':'Acción permanente. Perderás todos os teus datos.' },
  'profile.delete_photo_title': { 'en-US':'Delete photo','fr-FR':'Supprimer la photo','ca-ES':'Eliminar foto','eu-ES':'Argazkia ezabatu','gl-ES':'Eliminar foto' },
  'profile.delete_photo_confirm': { 'en-US':'Are you sure you want to delete your profile photo?','fr-FR':'Êtes-vous sûr de vouloir supprimer votre photo de profil ?','ca-ES':'Estàs segur que vols eliminar la teva foto de perfil?','eu-ES':'Ziur zaude zure profil-argazkia ezabatu nahi duzula?','gl-ES':'Estás seguro de que queres eliminar a túa foto de perfil?' },
  'profile.solvency_buyers_only': { 'en-US':'BUYERS ONLY','fr-FR':'ACHETEURS SEULEMENT','ca-ES':'NOMÉS COMPRADORS','eu-ES':'EROSLEAK BAKARRIK','gl-ES':'SÓ COMPRADORES' },
  'profile.trust_level_button': { 'en-US':'My Trust Level','fr-FR':'Mon Niveau de Confiance','ca-ES':'El meu Nivell de Confiança','eu-ES':'Nire Konfiantza Maila','gl-ES':'O meu Nivel de Confianza' },
  'profile.lifestyle_button': { 'en-US':'My Lifestyle','fr-FR':'Mon Style de Vie','ca-ES':'El meu Estil de Vida','eu-ES':'Nire Bizimodua','gl-ES':'O meu Estilo de Vida' },
  'profile.promo_title': { 'en-US':'Selling your home?','fr-FR':'Vous vendez votre bien ?','ca-ES':'Vens la teva casa?','eu-ES':'Zure etxea saltzen al duzu?','gl-ES':'Vendes a túa casa?' },
  'profile.promo_body': { 'en-US':'List it on InmuFácil and manage the entire process without commissions.','fr-FR':'Publiez-le sur InmuFácil et gérez tout le processus sans commissions.','ca-ES':'Publícala a InmuFácil i gestiona tot el procés sense comissions.','eu-ES':'Argitaratu InmuFácil-en eta kudeatu prozesua osoa komisiorik gabe.','gl-ES':'Publícaa en InmuFácil e xestiona todo o proceso sen comisións.' },
  'profile.promo_button': { 'en-US':'List Property','fr-FR':'Publier un Bien','ca-ES':'Publicar Propietat','eu-ES':'Propietatea Argitaratu','gl-ES':'Publicar Propiedade' },
  'profile.my_properties_title': { 'en-US':'My Properties','fr-FR':'Mes Biens','ca-ES':'Les meves Propietats','eu-ES':'Nire Propietateak','gl-ES':'As miñas Propiedades' },
  'profile.my_properties_subtitle': { 'en-US':'Manage your listings and drafts','fr-FR':'Gérez vos annonces et brouillons','ca-ES':'Gestiona els teus anuncis i esborranys','eu-ES':'Kudeatu zure iragarkiak eta zirriborroak','gl-ES':'Xestiona os teus anuncios e borradores' },
  'profile.properties_error': { 'en-US':'Error loading properties: {error}','fr-FR':'Erreur lors du chargement des biens : {error}','ca-ES':'Error en carregar propietats: {error}','eu-ES':'Propietateak kargatzean errorea: {error}','gl-ES':'Erro ao cargar propiedades: {error}' },
  'profile.see_drafts': { 'en-US':'View my drafts','fr-FR':'Voir mes brouillons','ca-ES':'Veure els meus esborranys','eu-ES':'Ikusi nire zirriborroak','gl-ES':'Ver os meus borradores' },
  'profile.member_since': { 'en-US':'Member since {year}','fr-FR':'Membre depuis {year}','ca-ES':'Membre des de {year}','eu-ES':'{year}tik kidea','gl-ES':'Membro dende {year}' },
  'profile.personal_info.full_name': { 'en-US':'Full name','fr-FR':'Nom complet','ca-ES':'Nom complet','eu-ES':'Izen osoa','gl-ES':'Nome completo' },
  'profile.personal_info.phone': { 'en-US':'Phone','fr-FR':'Téléphone','ca-ES':'Telèfon','eu-ES':'Telefonoa','gl-ES':'Teléfono' },
  'profile.personal_info.email_readonly': { 'en-US':'Email (Not editable)','fr-FR':'Email (Non modifiable)','ca-ES':'Email (No editable)','eu-ES':'Emaila (Ez editagarria)','gl-ES':'Email (Non editable)' },
  'profile.personal_info.save_btn': { 'en-US':'Save changes','fr-FR':'Sauvegarder les modifications','ca-ES':'Desar canvis','eu-ES':'Aldaketak gorde','gl-ES':'Gardar cambios' },
  'profile.personal_info.edit_btn': { 'en-US':'Edit profile','fr-FR':'Modifier le profil','ca-ES':'Editar perfil','eu-ES':'Profila editatu','gl-ES':'Editar perfil' },
  'profile.personal_info.save_success': { 'en-US':'Profile updated successfully','fr-FR':'Profil mis à jour avec succès','ca-ES':'Perfil actualitzat correctament','eu-ES':'Profila behar bezala eguneratu da','gl-ES':'Perfil actualizado correctamente' },
  'profile.security.suspension_not_available': { 'en-US':'Account suspension is not yet available.','fr-FR':'La suspension de compte n\'est pas encore disponible.','ca-ES':'La suspensió de compte encara no està disponible.','eu-ES':'Kontuaren etendura oraindik ez dago eskuragarri.','gl-ES':'A suspensión de conta aínda non está dispoñible.' },
  'profile.solvency.passport_title': { 'en-US':'SOLVENCY PASSPORT','fr-FR':'PASSEPORT SOLVABILITÉ','ca-ES':'PASSAPORT SOLVÈNCIA','eu-ES':'KAUDIMENAREN PASAPORTEA','gl-ES':'PASAPORTE SOLVENCIA' },
  'profile.solvency.passport_desc': { 'en-US':'Increase your chances of success by 80%.','fr-FR':'Augmentez vos chances de succès de 80 %.','ca-ES':'Augmenta les teves possibilitats d\'èxit en un 80%.','eu-ES':'Handitu zure arrakasta-aukerak %80an.','gl-ES':'Aumenta as túas posibilidades de éxito nun 80%.' },
  'profile.solvency.level': { 'en-US':'Level {level}','fr-FR':'Niveau {level}','ca-ES':'Nivell {level}','eu-ES':'{level} maila','gl-ES':'Nivel {level}' },
  'profile.solvency.gold': { 'en-US':'Gold','fr-FR':'Or','ca-ES':'Or','eu-ES':'Urre','gl-ES':'Ouro' },
  'profile.solvency.silver': { 'en-US':'Silver','fr-FR':'Argent','ca-ES':'Plata','eu-ES':'Zilar','gl-ES':'Prata' },
  'profile.solvency.bronze': { 'en-US':'Bronze','fr-FR':'Bronze','ca-ES':'Bronze','eu-ES':'Brontze','gl-ES':'Bronce' },
  'profile.trust.dashboard_desc': { 'en-US':'See how sellers see you','fr-FR':'Voir comment les vendeurs vous voient','ca-ES':'Veure com et veuen els venedors','eu-ES':'Ikusi saltzaileek nola ikusten zaituzten','gl-ES':'Ver como te ven os vendedores' },
  'profile.lifestyle.button_desc': { 'en-US':'Personalise your recommendations','fr-FR':'Personnalisez vos recommandations','ca-ES':'Personalitza les teves recomanacions','eu-ES':'Pertsonalizatu zure gomendioak','gl-ES':'Personaliza as túas recomendacións' },
  'profile.my_properties.filter_all': { 'en-US':'All','fr-FR':'Toutes','ca-ES':'Totes','eu-ES':'Guztiak','gl-ES':'Todas' },
  'profile.my_properties.filter_published': { 'en-US':'Published','fr-FR':'Publiées','ca-ES':'Publicades','eu-ES':'Argitaratuak','gl-ES':'Publicadas' },
  'profile.my_properties.filter_drafts': { 'en-US':'Drafts','fr-FR':'Brouillons','ca-ES':'Esborranys','eu-ES':'Zirriborroak','gl-ES':'Borradores' },
  'profile.my_properties.filter_unpublished': { 'en-US':'Unpublished','fr-FR':'Retirées','ca-ES':'Retirades','eu-ES':'Argitaratu gabeak','gl-ES':'Retiradas' },
  'profile.my_properties.sort_oldest': { 'en-US':'Oldest','fr-FR':'Plus anciennes','ca-ES':'Més antigues','eu-ES':'Zaharrenak','gl-ES':'Máis antigas' },
  'profile.property_analytics.views': { 'en-US':'{} views','fr-FR':'{} vues','ca-ES':'{} vistes','eu-ES':'{} ikustaldi','gl-ES':'{} vistas' },
  'profile.verification.pending_msg': { 'en-US':'Your verification is in progress. We will notify you when it is ready.','fr-FR':'Votre vérification est en cours. Nous vous notifierons quand elle sera prête.','ca-ES':'La teva verificació està en curs. T\'avisarem quan estigui llesta.','eu-ES':'Zure egiaztapena abian da. Jakinaraziko dizugun prest dagoenean.','gl-ES':'A túa verificación está en curso. Notificarémoste cando estea lista.' },
  'profile.verification.rejected_msg': { 'en-US':'Your verification was rejected. You can try again.','fr-FR':'Votre vérification a été rejetée. Vous pouvez réessayer.','ca-ES':'La teva verificació va ser rebutjada. Pots tornar-ho a intentar.','eu-ES':'Zure egiaztapena ukatu egin da. Berriro saiatu zaitezke.','gl-ES':'A túa verificación foi rexeitada. Podes volver a intentalo.' },
  'profile.verification.prompt_msg': { 'en-US':'Verify your identity for greater security and to highlight your listings.','fr-FR':'Vérifiez votre identité pour plus de sécurité et pour mettre en valeur vos annonces.','ca-ES':'Verifica la teva identitat per a major seguretat i destacar els teus anuncis.','eu-ES':'Egiaztatu zure identitatea segurtasun handiagoa eta zure iragarkiak nabarmentzeko.','gl-ES':'Verifica a túa identidade para maior seguridade e destacar os teus anuncios.' },
  'profile.verification.status_btn': { 'en-US':'View Status','fr-FR':'Voir le Statut','ca-ES':'Veure Estat','eu-ES':'Ikusi Egoera','gl-ES':'Ver Estado' },
  'profile.verification.retry_btn': { 'en-US':'Try Again','fr-FR':'Réessayer','ca-ES':'Reintentar','eu-ES':'Saiatu berriro','gl-ES':'Reintentar' },
  'profile.verification.verify_btn': { 'en-US':'Verify Now','fr-FR':'Vérifier Maintenant','ca-ES':'Verificar Ara','eu-ES':'Egiaztatu Orain','gl-ES':'Verificar Agora' },
  'profile.offers_tab.title': { 'en-US':'My Offers','fr-FR':'Mes Offres','ca-ES':'Les meves Ofertes','eu-ES':'Nire Eskaintzak','gl-ES':'As miñas Ofertas' },
  'profile.offers_tab.subtitle': { 'en-US':'Sent and received offers.','fr-FR':'Offres envoyées et reçues.','ca-ES':'Ofertes enviades i rebudes.','eu-ES':'Bidalitako eta jasotako eskaintzak.','gl-ES':'Ofertas enviadas e recibidas.' },
  'profile.offers_tab.no_offers': { 'en-US':'No offers yet.','fr-FR':'Aucune offre pour l\'instant.','ca-ES':'No hi ha ofertes encara.','eu-ES':'Oraingoz ez dago eskaintzarik.','gl-ES':'Non hai ofertas aínda.' },
  'profile.visits_tab.title': { 'en-US':'My Visits','fr-FR':'Mes Visites','ca-ES':'Les meves Visites','eu-ES':'Nire Bisitak','gl-ES':'As miñas Visitas' },
  'profile.visits_tab.subtitle': { 'en-US':'Visits scheduled as buyer or seller.','fr-FR':'Visites planifiées en tant qu\'acheteur ou vendeur.','ca-ES':'Visites programades com a comprador o venedor.','eu-ES':'Erosle edo saltzaile gisa programatutako bisitak.','gl-ES':'Visitas programadas como comprador ou vendedor.' },
  'profile.visits_tab.no_visits_title': { 'en-US':'No scheduled visits','fr-FR':'Aucune visite programmée','ca-ES':'Sense visites programades','eu-ES':'Ez dago bisitarik programatuta','gl-ES':'Sen visitas programadas' },
  'profile.visits_tab.no_visits_desc': { 'en-US':'The visits you book or accept will appear here.','fr-FR':'Les visites que vous réservez ou acceptez apparaîtront ici.','ca-ES':'Les visites que reservis o acceptis apareixeran aquí.','eu-ES':'Erreserba egiten edo onartzen dituzun bisitak hemen agertuko dira.','gl-ES':'As visitas que reserves ou aceptes aparecerán aquí.' },
  'profile.visits_tab.upcoming': { 'en-US':'Upcoming visits','fr-FR':'Visites à venir','ca-ES':'Properes visites','eu-ES':'Datozen bisitak','gl-ES':'Próximas visitas' },
  'profile.visits_tab.past': { 'en-US':'Past visits','fr-FR':'Visites passées','ca-ES':'Visites passades','eu-ES':'Iraganeko bisitak','gl-ES':'Visitas pasadas' },
  'profile.visits_tab.no_upcoming': { 'en-US':'You have no upcoming visits.','fr-FR':'Vous n\'avez aucune visite à venir.','ca-ES':'No tens visites properes.','eu-ES':'Ez duzu bisitarik datozenetan.','gl-ES':'Non tes visitas próximas.' },
  'profile.visits_tab.no_past': { 'en-US':'No visits in history.','fr-FR':'Aucune visite dans l\'historique.','ca-ES':'No hi ha visites a l\'historial.','eu-ES':'Ez dago bisitarik historian.','gl-ES':'Non hai visitas no historial.' },
  'profile.visits_tab.buyer': { 'en-US':'Buyer','fr-FR':'Acheteur','ca-ES':'Comprador','eu-ES':'Eroslea','gl-ES':'Comprador' },
  'profile.visits_tab.seller': { 'en-US':'Seller','fr-FR':'Vendeur','ca-ES':'Venedor','eu-ES':'Saltzailea','gl-ES':'Vendedor' },
  'profile.visits_tab.status_requested': { 'en-US':'Pending','fr-FR':'En attente','ca-ES':'Pendent','eu-ES':'Zain','gl-ES':'Pendente' },
  'profile.visits_tab.status_approved': { 'en-US':'Confirmed','fr-FR':'Confirmée','ca-ES':'Confirmada','eu-ES':'Berretsia','gl-ES':'Confirmada' },
  'profile.visits_tab.status_rejected': { 'en-US':'Rejected','fr-FR':'Rejetée','ca-ES':'Rebutjada','eu-ES':'Ukatuta','gl-ES':'Rexeitada' },
  'profile.visits_tab.status_cancelled': { 'en-US':'Cancelled','fr-FR':'Annulée','ca-ES':'Cancel·lada','eu-ES':'Bertan behera utzia','gl-ES':'Cancelada' },
  'profile.visits_tab.status_completed': { 'en-US':'Completed','fr-FR':'Terminée','ca-ES':'Completada','eu-ES':'Osatuta','gl-ES':'Completada' },
  'profile.visits_tab.status_no_show': { 'en-US':'No show','fr-FR':'Absence','ca-ES':'No presentat','eu-ES':'Ez da agert','gl-ES':'Non presentado' },
  'profile.visits_tab.accept_btn': { 'en-US':'Accept','fr-FR':'Accepter','ca-ES':'Acceptar','eu-ES':'Onartu','gl-ES':'Aceptar' },
  'profile.visits_tab.reject_btn': { 'en-US':'Reject','fr-FR':'Rejeter','ca-ES':'Rebutjar','eu-ES':'Ukatu','gl-ES':'Rexeitar' },
  'profile.visits_tab.accept_success': { 'en-US':'Visit accepted','fr-FR':'Visite acceptée','ca-ES':'Visita acceptada','eu-ES':'Bisita onartuta','gl-ES':'Visita aceptada' },
  'profile.visits_tab.reject_success': { 'en-US':'Visit rejected','fr-FR':'Visite rejetée','ca-ES':'Visita rebutjada','eu-ES':'Bisita ukatuta','gl-ES':'Visita rexeitada' },
  'profile.visits_tab.accept_error': { 'en-US':'Error accepting the visit','fr-FR':'Erreur lors de l\'acceptation de la visite','ca-ES':'Error en acceptar la visita','eu-ES':'Bisita onartzean errorea','gl-ES':'Erro ao aceptar a visita' },
  'profile.messages_tab.title': { 'en-US':'Messages','fr-FR':'Messages','ca-ES':'Missatges','eu-ES':'Mezuak','gl-ES':'Mensaxes' },
  'profile.messages_tab.subtitle': { 'en-US':'Your active conversations with buyers and sellers.','fr-FR':'Vos conversations actives avec les acheteurs et vendeurs.','ca-ES':'Les teves converses actives amb compradors i venedors.','eu-ES':'Erosle eta saltzaileekin dituzun elkarrizketa aktiboak.','gl-ES':'As túas conversas activas con compradores e vendedores.' },
  'profile.messages_tab.sort_unread': { 'en-US':'Unread first','fr-FR':'Non lus en premier','ca-ES':'No llegits primer','eu-ES':'Irakurri gabeak lehenengo','gl-ES':'Non lidos primeiro' },
  'profile.messages_tab.no_messages': { 'en-US':'No messages yet.','fr-FR':'Aucun message pour l\'instant.','ca-ES':'No hi ha missatges encara.','eu-ES':'Oraingoz ez dago mezurik.','gl-ES':'Non hai mensaxes aínda.' },
  'profile.messages_tab.no_conversations_title': { 'en-US':'No active conversations','fr-FR':'Aucune conversation active','ca-ES':'Sense converses actives','eu-ES':'Ez dago elkarrizketa aktiborik','gl-ES':'Sen conversas activas' },
  'profile.messages_tab.no_conversations_desc': { 'en-US':'When there are messages in an offer, they will appear here.','fr-FR':'Lorsqu\'il y a des messages dans une offre, ils apparaîtront ici.','ca-ES':'Quan hi hagi missatges en una oferta, apareixeran aquí.','eu-ES':'Eskaintza batean mezuak daudenean, hemen agertuko dira.','gl-ES':'Cando haxa mensaxes nunha oferta, aparecerán aquí.' },
  'profile.messages_tab.yesterday': { 'en-US':'YESTERDAY','fr-FR':'HIER','ca-ES':'AHIR','eu-ES':'ATZO','gl-ES':'ONTE' },
  'profile.messages_tab.days': { 'en-US':'MON,TUE,WED,THU,FRI,SAT,SUN','fr-FR':'LUN,MAR,MER,JEU,VEN,SAM,DIM','ca-ES':'DLL,DIM,DIM,DIJ,DIV,DIS,DIG','eu-ES':'AST,MAR,OTZ,OST,OST,LAR,IGA','gl-ES':'LUN,MAR,MER,XOV,VEN,SAB,DOM' },
  'profile.manage_btn': { 'en-US':'Manage','fr-FR':'Gérer','ca-ES':'Gestionar','eu-ES':'Kudeatu','gl-ES':'Xestionar' },
  // OFFERS
  'offers.make_offer_title': { 'en-US':'Make a Formal Offer','fr-FR':'Faire une Offre Formelle','ca-ES':'Fer una Oferta Formal','eu-ES':'Eskaintza Formal bat Egin','gl-ES':'Facer unha Oferta Formal' },
  'offers.make_offer_subtitle': { 'en-US':'Send a binding proposal to the seller','fr-FR':'Envoyez une proposition contraignante au vendeur','ca-ES':'Envia una proposta vinculant al venedor','eu-ES':'Bidali proposamen loteslea saltzaileari','gl-ES':'Envía unha proposta vinculante ao vendedor' },
  'offers.payment_method': { 'en-US':'Payment Method','fr-FR':'Mode de Paiement','ca-ES':'Forma de Pagament','eu-ES':'Ordainketa Metodoa','gl-ES':'Forma de Pago' },
  'offers.cash_label': { 'en-US':'Cash','fr-FR':'Comptant','ca-ES':'Al comptat','eu-ES':'Eskudirutan','gl-ES':'Ao contado' },
  'offers.cash_subtitle': { 'en-US':'Own funds available','fr-FR':'Fonds propres disponibles','ca-ES':'Fons propis disponibles','eu-ES':'Eskuragarri dauden funts propioak','gl-ES':'Fondos propios dispoñibles' },
  'offers.mortgage_label': { 'en-US':'I Need a Mortgage','fr-FR':'J\'ai besoin d\'un prêt','ca-ES':'Necessito Hipoteca','eu-ES':'Hipoteka behar dut','gl-ES':'Necesito Hipoteca' },
  'offers.mortgage_subtitle': { 'en-US':'Pending bank approval','fr-FR':'En attente d\'approbation bancaire','ca-ES':'Pendent d\'aprovació bancària','eu-ES':'Bankuaren onespena zain','gl-ES':'Pendente de aprobación bancaria' },
  'offers.signing_date_label': { 'en-US':'Desired signing date','fr-FR':'Date de signature souhaitée','ca-ES':'Data desitjada d\'escriptura','eu-ES':'Nahi den sinadura-data','gl-ES':'Data desexada de escritura' },
  'offers.date_placeholder': { 'en-US':'dd/mm/yyyy','fr-FR':'jj/mm/aaaa','ca-ES':'dd/mm/aaaa','eu-ES':'ee/hh/uuuu','gl-ES':'dd/mm/aaaa' },
  'offers.signing_date_note': { 'en-US':'The final date will be agreed upon before a notary.','fr-FR':'La date finale sera convenue d\'un commun accord devant un notaire.','ca-ES':'La data final serà acordada de mutu acord davant notari.','eu-ES':'Azken data notario baten aurrean adostua izango da.','gl-ES':'A data final será acordada de mutuo acordo ante notario.' },
  'offers.message_label': { 'en-US':'Message to seller (optional)','fr-FR':'Message au vendeur (optionnel)','ca-ES':'Missatge al venedor (opcional)','eu-ES':'Mezua saltzaileari (aukerakoa)','gl-ES':'Mensaxe ao vendedor (opcional)' },
  'offers.message_hint': { 'en-US':'Add any detail you want to share with the owner...','fr-FR':'Ajoutez un détail que vous souhaitez partager avec le propriétaire...','ca-ES':'Afegeix algun detall que vulguis comentar al propietari...','eu-ES':'Gehitu jabe-ari esan nahi diozun xeheren bat...','gl-ES':'Engade algún detalle que queiras comentar ao propietario...' },
  'offers.binding_commitment': { 'en-US':'I understand that this offer is a serious purchase commitment and I am willing to formalise it through an arras contract.','fr-FR':'Je comprends que cette offre est un engagement sérieux d\'achat et je suis prêt à la formaliser par un contrat d\'arrhes.','ca-ES':'Entenc que aquesta oferta és un compromís seriós de compra i estic disposat a formalitzar-la mitjançant un contracte d\'arres.','eu-ES':'Ulertzen dut eskaintza hau erosketa-konpromiso seriotsua dela eta arras kontratuen bidez formalizatzeko prest nagoela.','gl-ES':'Entendo que esta oferta é un compromiso serio de compra e estou disposto a formalizala mediante contrato de arras.' },
  'offers.total_label': { 'en-US':'TOTAL OFFER','fr-FR':'OFFRE TOTALE','ca-ES':'OFERTA TOTAL','eu-ES':'ESKAINTZA OSOA','gl-ES':'OFERTA TOTAL' },
  'offers.send_offer': { 'en-US':'Send Formal Offer','fr-FR':'Envoyer l\'Offre Formelle','ca-ES':'Enviar Oferta Formal','eu-ES':'Bidali Eskaintza Formala','gl-ES':'Enviar Oferta Formal' },
  'offers.protected_badge': { 'en-US':'OFFER PROTECTED BY INMUFÁCIL SECURE TECH','fr-FR':'OFFRE PROTÉGÉE PAR INMUFÁCIL SECURE TECH','ca-ES':'OFERTA PROTEGIDA PER INMUFÁCIL SECURE TECH','eu-ES':'ESKAINTZA INMUFÁCIL SECURE TECH-EK BABESTUTA','gl-ES':'OFERTA PROTEXIDA POR INMUFÁCIL SECURE TECH' },
  'offers.disclaimer_text': { 'en-US':'By sending this offer, the platform will instantly notify the seller. Your personal data is protected by GDPR and will only be shared after offer acceptance for the corresponding legal procedures.','fr-FR':'En envoyant cette offre, la plateforme notifiera instantanément le vendeur. Vos données personnelles sont protégées par le RGPD et ne seront partagées qu\'après l\'acceptation de l\'offre pour les procédures légales correspondantes.','ca-ES':'En enviar aquesta oferta, la plataforma notificarà instantàniament el venedor. Les teves dades personals estan protegides pel RGPD i només es compartiran després de l\'acceptació de l\'oferta per als tràmits legals corresponents.','eu-ES':'Eskaintza hau bidaltzean, plataformak saltzaileari berehala jakinaraziko dio. Zure datu pertsonalak GDPRak babesten ditu eta eskaintza onartu ondoren bakarrik partekatuko dira dagokion legezko tramiteen arabera.','gl-ES':'Ao enviar esta oferta, a plataforma notificará instantaneamente ao vendedor. Os teus datos persoais están protexidos polo RGPD e só se compartirán tras a aceptación da oferta para os trámites legais correspondentes.' },
  'offers.legal_notice': { 'en-US':'Legal Notice','fr-FR':'Mention Légale','ca-ES':'Avís Legal','eu-ES':'Ohar Legala','gl-ES':'Aviso Legal' },
  'offers.privacy': { 'en-US':'Privacy','fr-FR':'Confidentialité','ca-ES':'Privacitat','eu-ES':'Pribazitatea','gl-ES':'Privacidade' },
  'offers.security_link': { 'en-US':'Security','fr-FR':'Sécurité','ca-ES':'Seguretat','eu-ES':'Segurtasuna','gl-ES':'Seguridade' },
  'offers.help_link': { 'en-US':'Help','fr-FR':'Aide','ca-ES':'Ajuda','eu-ES':'Laguntza','gl-ES':'Axuda' },
  'offers.success_snackbar': { 'en-US':'Offer sent successfully','fr-FR':'Offre envoyée avec succès','ca-ES':'Oferta enviada correctament','eu-ES':'Eskaintza behar bezala bidali da','gl-ES':'Oferta enviada correctamente' },
  'offers.error_snackbar': { 'en-US':'Error sending offer','fr-FR':'Erreur lors de l\'envoi de l\'offre','ca-ES':'Error en enviar oferta','eu-ES':'Eskaintza bidaltzean errorea','gl-ES':'Erro ao enviar oferta' },
  'offers.home_button': { 'en-US':'Home','fr-FR':'Accueil','ca-ES':'Inici','eu-ES':'Hasiera','gl-ES':'Inicio' },
  'offers.economic_proposal': { 'en-US':'YOUR ECONOMIC PROPOSAL','fr-FR':'VOTRE PROPOSITION ÉCONOMIQUE','ca-ES':'LA TEVA PROPOSTA ECONÒMICA','eu-ES':'ZURE PROPOSAMEN EKONOMIKOA','gl-ES':'A TÚA PROPOSTA ECONÓMICA' },
  'offers.low_offer_warning': { 'en-US':'Your offer is {}% below the asking price','fr-FR':'Votre offre est inférieure de {}% au prix de vente','ca-ES':'La teva oferta és un {}% inferior al preu de sortida','eu-ES':'Zure eskaintza irteera-prezioa baino {}% baxuagoa da','gl-ES':'A túa oferta é un {}% inferior ao prezo de saída' },
  'offers.asking_price_label': { 'en-US':'Asking price:  ','fr-FR':'Prix de vente :  ','ca-ES':'Preu de sortida:  ','eu-ES':'Irteera-prezioa:  ','gl-ES':'Prezo de saída:  ' },
  'offers.available_status': { 'en-US':'AVAILABLE','fr-FR':'DISPONIBLE','ca-ES':'DISPONIBLE','eu-ES':'ESKURAGARRI','gl-ES':'DISPOÑIBLE' },
  'offers.sort_newest': { 'en-US':'Most recent','fr-FR':'Les plus récentes','ca-ES':'Més recents','eu-ES':'Berrienak','gl-ES':'Máis recentes' },
  'offers.sort_oldest': { 'en-US':'Oldest','fr-FR':'Les plus anciennes','ca-ES':'Més antigues','eu-ES':'Zaharrenak','gl-ES':'Máis antigas' },
  'offers.sort_price_asc': { 'en-US':'Price: low to high','fr-FR':'Prix : croissant','ca-ES':'Preu: de menor a major','eu-ES':'Prezioa: txikitik handira','gl-ES':'Prezo: menor a maior' },
  'offers.sort_price_desc': { 'en-US':'Price: high to low','fr-FR':'Prix : décroissant','ca-ES':'Preu: de major a menor','eu-ES':'Prezioa: handitik txikira','gl-ES':'Prezo: maior a menor' },
  'offers.received_title': { 'en-US':'Received Offers','fr-FR':'Offres Reçues','ca-ES':'Ofertes Rebudes','eu-ES':'Jasotako Eskaintzak','gl-ES':'Ofertas Recibidas' },
  'offers.error_loading': { 'en-US':'Error loading offers','fr-FR':'Erreur lors du chargement des offres','ca-ES':'Error en carregar ofertes','eu-ES':'Eskaintzak kargatzean errorea','gl-ES':'Erro ao cargar ofertas' },
  'offers.retry': { 'en-US':'Retry','fr-FR':'Réessayer','ca-ES':'Reintentar','eu-ES':'Saiatu berriro','gl-ES':'Reintentar' },
  'offers.no_offers': { 'en-US':'You have not received any offers yet','fr-FR':'Vous n\'avez pas encore reçu d\'offres','ca-ES':'Encara no has rebut cap oferta','eu-ES':'Oraindik ez duzu eskaintzarik jaso','gl-ES':'Aínda non recibiches ningunha oferta' },
  'offers.property_fallback': { 'en-US':'Property','fr-FR':'Bien','ca-ES':'Propietat','eu-ES':'Propietatea','gl-ES':'Propiedade' },
  'offers.starting_price': { 'en-US':'Asking price {}','fr-FR':'Prix de vente {}','ca-ES':'Preu de sortida {}','eu-ES':'Irteera-prezioa {}','gl-ES':'Prezo de saída {}' },
  'offers.starting_price_empty': { 'en-US':'Asking price —','fr-FR':'Prix de vente —','ca-ES':'Preu de sortida —','eu-ES':'Irteera-prezioa —','gl-ES':'Prezo de saída —' },
  'offers.stat_offers': { 'en-US':'OFFERS','fr-FR':'OFFRES','ca-ES':'OFERTES','eu-ES':'ESKAINTZAK','gl-ES':'OFERTAS' },
  'offers.stat_visits': { 'en-US':'VISITS','fr-FR':'VISITES','ca-ES':'VISITES','eu-ES':'BISITAK','gl-ES':'VISITAS' },
  'offers.stat_favorites': { 'en-US':'FAVOURITES','fr-FR':'FAVORIS','ca-ES':'PREFERITS','eu-ES':'GOGOKOAK','gl-ES':'FAVORITOS' },
  'offers.status_active': { 'en-US':'ACTIVE','fr-FR':'ACTIF','ca-ES':'ACTIU','eu-ES':'AKTIBO','gl-ES':'ACTIVO' },
  'offers.status_draft': { 'en-US':'DRAFT','fr-FR':'BROUILLON','ca-ES':'ESBORRANY','eu-ES':'ZIRRIBORROA','gl-ES':'BORRADOR' },
  'offers.status_unpublished': { 'en-US':'UNPUBLISHED','fr-FR':'RETIRÉ','ca-ES':'RETIRAT','eu-ES':'ARGITARATU GABE','gl-ES':'RETIRADO' },
  'offers.buyer_fallback': { 'en-US':'Buyer','fr-FR':'Acheteur','ca-ES':'Comprador','eu-ES':'Eroslea','gl-ES':'Comprador' },
  'offers.received_on': { 'en-US':'Received on {}','fr-FR':'Reçue le {}','ca-ES':'Rebuda el {}','eu-ES':'{} egunean jasota','gl-ES':'Recibida o {}' },
  'offers.amount_offered': { 'en-US':'AMOUNT OFFERED','fr-FR':'MONTANT PROPOSÉ','ca-ES':'QUANTITAT OFERTA','eu-ES':'ESKAINITAKO ZENBATEKOA','gl-ES':'CANTIDADE OFRECIDA' },
  'offers.conditions_header': { 'en-US':'CONDITIONS','fr-FR':'CONDITIONS','ca-ES':'CONDICIONS','eu-ES':'BALDINTZAK','gl-ES':'CONDICIÓNS' },
  'offers.closing_date': { 'en-US':'CLOSING DATE','fr-FR':'DATE DE CLÔTURE','ca-ES':'DATA TANCAMENT','eu-ES':'ITXIERA DATA','gl-ES':'DATA PECHE' },
  'offers.payment_cash': { 'en-US':'Cash\nPayment','fr-FR':'Paiement\nComptant','ca-ES':'Pagament\nal Comptat','eu-ES':'Eskudiruzkoa\nordainketa','gl-ES':'Pago\nao Contado' },
  'offers.payment_mortgage': { 'en-US':'Needs\nMortgage','fr-FR':'Besoin\nd\'un prêt','ca-ES':'Necessita\nHipoteca','eu-ES':'Hipoteka\nbehar du','gl-ES':'Necesita\nHipoteca' },
  'offers.immediate': { 'en-US':'Immediate','fr-FR':'Immédiat','ca-ES':'Immediat','eu-ES':'Berehalakoa','gl-ES':'Inmediato' },
  'offers.hide_message': { 'en-US':'Hide message','fr-FR':'Masquer le message','ca-ES':'Amagar missatge','eu-ES':'Ezkutatu mezua','gl-ES':'Ocultar mensaxe' },
  'offers.read_message': { 'en-US':'Read full message','fr-FR':'Lire le message complet','ca-ES':'Llegir missatge complet','eu-ES':'Irakurri mezu osoa','gl-ES':'Ler mensaxe completo' },
  'offers.accept_title': { 'en-US':'Accept offer','fr-FR':'Accepter l\'offre','ca-ES':'Acceptar oferta','eu-ES':'Eskaintza onartu','gl-ES':'Aceptar oferta' },
  'offers.accept_body': { 'en-US':'You are about to accept the offer of {}. This action cannot be undone.','fr-FR':'Vous êtes sur le point d\'accepter l\'offre de {}. Cette action ne peut pas être annulée.','ca-ES':'Vas a acceptar l\'oferta de {}. Aquesta acció no es pot desfer.','eu-ES':'{} eskaintza onartzera zoaz. Ekintza hau ezin da desegin.','gl-ES':'Vas a aceptar a oferta de {}. Esta acción non se pode desfacer.' },
  'offers.reject_title': { 'en-US':'Reject offer','fr-FR':'Rejeter l\'offre','ca-ES':'Rebutjar oferta','eu-ES':'Eskaintza ukatu','gl-ES':'Rexeitar oferta' },
  'offers.reject_body': { 'en-US':'The buyer will be notified that their offer has been rejected.','fr-FR':'L\'acheteur sera informé que son offre a été rejetée.','ca-ES':'El comprador serà notificat que la seva oferta ha estat rebutjada.','eu-ES':'Erosleari jakinaraziko zaio bere eskaintza ukatu dela.','gl-ES':'O comprador será notificado de que a súa oferta foi rexeitada.' },
  'offers.reject_body_solvency': { 'en-US':'The buyer will be notified that their offer has been rejected. This action cannot be undone.','fr-FR':'L\'acheteur sera informé que son offre a été rejetée. Cette action ne peut pas être annulée.','ca-ES':'El comprador serà notificat que la seva oferta ha estat rebutjada. Aquesta acció no es pot desfer.','eu-ES':'Erosleari jakinaraziko zaio bere eskaintza ukatu dela. Ekintza hau ezin da desegin.','gl-ES':'O comprador será notificado de que a súa oferta foi rexeitada. Esta acción non se pode desfacer.' },
  'offers.counter_title_prefix': { 'en-US':'Counter','fr-FR':'Contre','ca-ES':'Contra','eu-ES':'Kontra','gl-ES':'Contra' },
  'offers.counter_title_suffix': { 'en-US':'offer','fr-FR':'offre','ca-ES':'oferta','eu-ES':'eskaintza','gl-ES':'oferta' },
  'offers.counter_label': { 'en-US':'Your counteroffer','fr-FR':'Votre contre-offre','ca-ES':'La teva contraoferta','eu-ES':'Zure kontraeskaintza','gl-ES':'A túa contraoferta' },
  'offers.accept_btn': { 'en-US':'Accept Offer','fr-FR':'Accepter l\'Offre','ca-ES':'Acceptar Oferta','eu-ES':'Onartu Eskaintza','gl-ES':'Aceptar Oferta' },
  'offers.counter_btn': { 'en-US':'Counter Offer','fr-FR':'Contre-offrir','ca-ES':'Contraofertar','eu-ES':'Kontraeskaintzatu','gl-ES':'Contraofertar' },
  'offers.reject_btn': { 'en-US':'Reject','fr-FR':'Rejeter','ca-ES':'Rebutjar','eu-ES':'Ukatu','gl-ES':'Rexeitar' },
  'offers.verified': { 'en-US':'VERIFIED','fr-FR':'VÉRIFIÉ','ca-ES':'VERIFICAT','eu-ES':'EGIAZTATUTA','gl-ES':'VERIFICADO' },
  'offers.status_pending': { 'en-US':'PENDING','fr-FR':'EN ATTENTE','ca-ES':'PENDENT','eu-ES':'ZAIN','gl-ES':'PENDENTE' },
  'offers.status_accepted': { 'en-US':'ACCEPTED','fr-FR':'ACCEPTÉE','ca-ES':'ACCEPTADA','eu-ES':'ONARTUTA','gl-ES':'ACEPTADA' },
  'offers.status_counter': { 'en-US':'COUNTEROFFER SENT','fr-FR':'CONTRE-OFFRE ENVOYÉE','ca-ES':'CONTRAOFERTA ENVIADA','eu-ES':'KONTRAESKAINTZA BIDALITA','gl-ES':'CONTRAOFERTA ENVIADA' },
  'offers.status_signing': { 'en-US':'IN SIGNING','fr-FR':'EN SIGNATURE','ca-ES':'EN FIRMA','eu-ES':'SINATZEN','gl-ES':'EN FIRMA' },
  'offers.status_signed': { 'en-US':'SIGNED','fr-FR':'SIGNÉE','ca-ES':'FIRMADA','eu-ES':'SINATUTA','gl-ES':'ASINADA' },
  'offers.status_completed': { 'en-US':'COMPLETED','fr-FR':'COMPLÉTÉE','ca-ES':'COMPLETADA','eu-ES':'OSATUTA','gl-ES':'COMPLETADA' },
  'offers.status_rejected': { 'en-US':'REJECTED','fr-FR':'REJETÉE','ca-ES':'REBUTJADA','eu-ES':'UKATUTA','gl-ES':'REXEITADA' },
  'offers.status_withdrawn': { 'en-US':'WITHDRAWN','fr-FR':'RETIRÉE','ca-ES':'RETIRADA','eu-ES':'ATZERA EGINDAKOA','gl-ES':'RETIRADA' },
  'offers.solvency_title': { 'en-US':'Buyer\'s solvency','fr-FR':'Solvabilité de l\'acheteur','ca-ES':'Solvència del comprador','eu-ES':'Eroslearen kaudimena','gl-ES':'Solvencia do comprador' },
  'offers.no_passport': { 'en-US':'The buyer does not yet have a solvency passport.','fr-FR':'L\'acheteur n\'a pas encore de passeport de solvabilité.','ca-ES':'El comprador encara no té passaport de solvència.','eu-ES':'Erosleak oraindik ez du kaudimenaren pasaporterik.','gl-ES':'O comprador aínda non ten pasaporte de solvencia.' },
  'offers.incomplete_passport': { 'en-US':'The buyer has not yet completed the solvency passport.','fr-FR':'L\'acheteur n\'a pas encore complété le passeport de solvabilité.','ca-ES':'El comprador encara no ha completat el passaport de solvència.','eu-ES':'Erosleak oraindik ez du kaudimenaren pasaportea osatu.','gl-ES':'O comprador aínda non completou o pasaporte de solvencia.' },
  'offers.gold': { 'en-US':'Gold','fr-FR':'Or','ca-ES':'Or','eu-ES':'Urre','gl-ES':'Ouro' },
  'offers.silver': { 'en-US':'Silver','fr-FR':'Argent','ca-ES':'Plata','eu-ES':'Zilar','gl-ES':'Prata' },
  'offers.bronze': { 'en-US':'Bronze','fr-FR':'Bronze','ca-ES':'Bronze','eu-ES':'Brontze','gl-ES':'Bronce' },
  'offers.level': { 'en-US':'Level {}','fr-FR':'Niveau {}','ca-ES':'Nivell {}','eu-ES':'{} maila','gl-ES':'Nivel {}' },
  'offers.joint_purchase': { 'en-US':'Joint purchase','fr-FR':'Achat conjoint','ca-ES':'Compra conjunta','eu-ES':'Erosketa bateratua','gl-ES':'Compra conxunta' },
  'offers.knows_costs': { 'en-US':'Aware of additional costs','fr-FR':'Connait les frais supplémentaires','ca-ES':'Coneix despeses addicionals','eu-ES':'Gastu gehigarriak ezagutzen ditu','gl-ES':'Coñece gastos adicionais' },
  'offers.initial_savings': { 'en-US':'Initial savings','fr-FR':'Épargne initiale','ca-ES':'Estalvis inicials','eu-ES':'Hasierako aurrezkiak','gl-ES':'Aforros iniciais' },
  'offers.preapproval': { 'en-US':'Mortgage pre-approval','fr-FR':'Préapprobation hypothécaire','ca-ES':'Preaprovació hipotecària','eu-ES':'Hipotekaren aurre-onespena','gl-ES':'Preaprobación hipotecaria' },
  'offers.financing': { 'en-US':'Financing','fr-FR':'Financement','ca-ES':'Finançament','eu-ES':'Finantzaketa','gl-ES':'Financiamento' },
  'offers.second_buyer': { 'en-US':'Second buyer','fr-FR':'Second acheteur','ca-ES':'Segon comprador','eu-ES':'Bigarren eroslea','gl-ES':'Segundo comprador' },
  'offers.accept_solvency': { 'en-US':'Accept solvency and view timeline','fr-FR':'Accepter la solvabilité et voir le calendrier','ca-ES':'Acceptar solvència i veure timeline','eu-ES':'Kaudimena onartu eta denbora-lerroa ikusi','gl-ES':'Aceptar solvencia e ver timeline' },
  'offers.offer_rejected_snackbar': { 'en-US':'Offer rejected','fr-FR':'Offre rejetée','ca-ES':'Oferta rebutjada','eu-ES':'Eskaintza ukatuta','gl-ES':'Oferta rexeitada' },
  'offers.reject_error_snackbar': { 'en-US':'Error rejecting the offer. Please try again.','fr-FR':'Erreur lors du rejet de l\'offre. Veuillez réessayer.','ca-ES':'Error en rebutjar l\'oferta. Torna-ho a intentar.','eu-ES':'Eskaintza ukatzean errorea. Saiatu berriro.','gl-ES':'Erro ao rexeitar a oferta. Inténtao de novo.' },
  'offers.all_binding': { 'en-US':'All offers are legally binding','fr-FR':'Toutes les offres sont juridiquement contraignantes','ca-ES':'Totes les ofertes són legalment vinculants','eu-ES':'Eskaintza guztiak juridikoki lotesleak dira','gl-ES':'Todas as ofertas son legalmente vinculantes' },
  'offers.identity_secured': { 'en-US':'InmuFácil secures the identity of every buyer.','fr-FR':'InmuFácil sécurise l\'identité de chaque acheteur.','ca-ES':'InmuFácil assegura la identitat de cada comprador.','eu-ES':'InmuFácil-ek erosle bakoitzaren identitatea bermatzen du.','gl-ES':'InmuFácil asegura a identidade de cada comprador.' },
  'offers.view_closing': { 'en-US':'View closing\nprocess','fr-FR':'Voir le processus\nde clôture','ca-ES':'Veure procés\nde tancament','eu-ES':'Ikusi itxiera\nprozesua','gl-ES':'Ver proceso\nde peche' },
  'offers.footer_text': { 'en-US':'InmuFácil Secure-Tech  ·  © 2023 InmuFácil S.L. All rights reserved. Secure transaction system under AES-256 protocol','fr-FR':'InmuFácil Secure-Tech  ·  © 2023 InmuFácil S.L. Tous droits réservés. Système de transactions sécurisées sous protocole AES-256','ca-ES':'InmuFácil Secure-Tech  ·  © 2023 InmuFácil S.L. Tots els drets reservats. Sistema de transaccions segures sota protocol AES-256','eu-ES':'InmuFácil Secure-Tech  ·  © 2023 InmuFácil S.L. Eskubide guztiak erreserbatuak. AES-256 protokoloan oinarritutako transakzio seguruen sistema','gl-ES':'InmuFácil Secure-Tech  ·  © 2023 InmuFácil S.L. Todos os dereitos reservados. Sistema de transaccións seguras baixo protocolo AES-256' },
  'offers.help': { 'en-US':'Help','fr-FR':'Aide','ca-ES':'Ajuda','eu-ES':'Laguntza','gl-ES':'Axuda' },
  'offers.legal_link': { 'en-US':'Legal','fr-FR':'Légal','ca-ES':'Legal','eu-ES':'Legala','gl-ES':'Legal' },
  'offers.security_mgmt_link': { 'en-US':'Security','fr-FR':'Sécurité','ca-ES':'Seguretat','eu-ES':'Segurtasuna','gl-ES':'Seguridade' },
  'offers.chat': { 'en-US':'Chat','fr-FR':'Chat','ca-ES':'Xat','eu-ES':'Txata','gl-ES':'Chat' },
  'offers.month_jan': { 'en-US':'Jan','fr-FR':'Jan','ca-ES':'Gen','eu-ES':'Urt','gl-ES':'Xan' },
  'offers.month_feb': { 'en-US':'Feb','fr-FR':'Fév','ca-ES':'Feb','eu-ES':'Ots','gl-ES':'Feb' },
  'offers.month_mar': { 'en-US':'Mar','fr-FR':'Mar','ca-ES':'Mar','eu-ES':'Mar','gl-ES':'Mar' },
  'offers.month_apr': { 'en-US':'Apr','fr-FR':'Avr','ca-ES':'Abr','eu-ES':'Api','gl-ES':'Abr' },
  'offers.month_may': { 'en-US':'May','fr-FR':'Mai','ca-ES':'Mai','eu-ES':'Mai','gl-ES':'Mai' },
  'offers.month_jun': { 'en-US':'Jun','fr-FR':'Jun','ca-ES':'Jun','eu-ES':'Eka','gl-ES':'Xuñ' },
  'offers.month_jul': { 'en-US':'Jul','fr-FR':'Juil','ca-ES':'Jul','eu-ES':'Uzt','gl-ES':'Xul' },
  'offers.month_aug': { 'en-US':'Aug','fr-FR':'Août','ca-ES':'Ago','eu-ES':'Abu','gl-ES':'Ago' },
  'offers.month_sep': { 'en-US':'Sep','fr-FR':'Sep','ca-ES':'Set','eu-ES':'Ira','gl-ES':'Set' },
  'offers.month_oct': { 'en-US':'Oct','fr-FR':'Oct','ca-ES':'Oct','eu-ES':'Urr','gl-ES':'Out' },
  'offers.month_nov': { 'en-US':'Nov','fr-FR':'Nov','ca-ES':'Nov','eu-ES':'Aza','gl-ES':'Nov' },
  'offers.month_dec': { 'en-US':'Dec','fr-FR':'Déc','ca-ES':'Des','eu-ES':'Abe','gl-ES':'Dec' },
};

const langs = ['en-US','en-GB','en-CA','fr-FR','fr-CA','ca-ES','va-ES','eu-ES','gl-ES'];

langs.forEach(lang => {
  const fp = base + lang + '.json';
  const json = JSON.parse(fs.readFileSync(fp, 'utf8'));
  let count = 0;
  Object.entries(translations).forEach(([path, vals]) => {
    let src = lang;
    if (lang === 'en-GB' || lang === 'en-CA') src = 'en-US';
    if (lang === 'fr-CA') src = 'fr-FR';
    if (lang === 'va-ES') src = 'ca-ES';
    const val = vals[src] || vals['en-US'];
    if (val !== undefined) {
      setVal(json, path, val);
      count++;
    }
  });
  fs.writeFileSync(fp, JSON.stringify(json, null, 2), 'utf8');
  console.log(lang + ': updated ' + count + ' profile+offers keys');
});
