const fs = require('fs');
const base = 'C:/Users/Os/.gemini/antigravity/scratch/InmuFacil_Project/frontend/assets/translations/';

const translations = {
  'es-ES': {
    urgency: {
      sign_arras_ready: "Arras: Espera que la otra parte complete la entrevista",
      appraisal_pending: "Tasación pendiente de aprobación",
      fein_review: "Revisar el FEIN del banco",
      notary_confirm: "Confirmar fecha en la notaría",
      handover_docs: "Preparar documentación para la entrega de llaves",
      utilities_transfer: "Gestionar el cambio de suministros",
      counter_received: "Has recibido una contraoferta",
      offer_received: "Has recibido una nueva oferta",
      visit_pending: "Tienes una visita pendiente de confirmación",
      docs_pending: "Documentos pendientes de revisión",
      solvency_pending: "Solicitud de solvencia pendiente",
      mortgage_docs: "Documentos de hipoteca pendientes",
      survey_pending: "Encuesta post-venta pendiente"
    },
    transaction: {
      status_in_progress: "EN CURSO",
      role_buyer: "COMPRADOR",
      role_seller: "VENDEDOR",
      step_offer: "Oferta Enviada",
      step_arras: "Contrato de Arras",
      step_appraisal: "Tasación de la Vivienda",
      step_fein: "Formalización Bancaria (FEIN)",
      step_notary: "Firma en Notaría y Entrega de Llaves",
      step_post_sale: "Post-Venta y Suministros",
      help_action: "Hablar con un asesor",
      footer_support: "Soporte",
      arras_status_pending_buyer: "Entrevista pendiente (comprador)",
      arras_status_pending_seller: "Entrevista pendiente (vendedor)",
      arras_status_both_done: "Ambas partes han completado la entrevista",
      arras_status_payment_pending: "Pago de arras pendiente",
      arras_status_signed: "Contrato firmado por ambas partes",
      arras_status_cancelled: "Contrato cancelado",
      arras_status_default: "Contrato de arras en curso",
      arras_cta_schedule: "Programar la firma",
      arras_cta_waiting_seller: "Esperando que el vendedor complete la entrevista",
      arras_cta_waiting_buyer: "Esperando que el comprador complete la entrevista",
      arras_cta_pay: "Realizar pago de arras",
      arras_cta_done: "Contrato finalizado",
      arras_cta_default: "Gestionar arras",
      appraisal_status_requested: "Tasación solicitada",
      appraisal_status_scheduled: "Tasación programada",
      appraisal_status_completed: "Tasación completada",
      appraisal_status_approved: "Tasación aprobada por el banco",
      appraisal_status_default: "Tasación en curso",
      appraisal_cta_request: "Solicitar tasación",
      appraisal_cta_details: "Ver detalles de la tasación",
      appraisal_cta_default: "Gestionar tasación",
      fein_status_requested: "FEIN solicitado al banco",
      fein_status_reviewing: "Revisando FEIN",
      fein_status_accepted: "FEIN aceptado",
      fein_status_default: "Formalización bancaria en curso",
      fein_cta_request: "Solicitar FEIN",
      fein_cta_review: "Revisar FEIN",
      fein_cta_default: "Gestionar FEIN",
      notary_status_scheduling: "Programando fecha en notaría",
      notary_status_scheduled: "Fecha en notaría confirmada",
      notary_status_done: "Firma completada",
      notary_status_default: "Formalización en notaría en curso",
      notary_cta_schedule: "Programar cita en notaría",
      notary_cta_confirm: "Confirmar cita",
      notary_cta_default: "Gestionar notaría",
      dialog_withdraw_title: "Retirar oferta",
      dialog_withdraw_content: "Estás a punto de retirar tu oferta. Esta acción no se puede deshacer.",
      dialog_withdraw_confirm: "Retirar oferta",
      dialog_accept_counter_title: "Aceptar contraoferta",
      dialog_accept_counter_content: "Aceptarás la contraoferta de {amount}. Esta acción iniciará el proceso de firma del contrato de arras.",
      dialog_accept_counter_confirm: "Aceptar contraoferta",
      dialog_new_offer_title: "Nueva oferta",
      dialog_new_offer_label: "Importe de la nueva oferta (€)",
      dialog_new_offer_confirm: "Enviar oferta",
      dialog_reject_counter_title: "Rechazar contraoferta",
      dialog_reject_counter_content: "Rechazarás la contraoferta. La negociación finalizará.",
      dialog_reject_counter_confirm: "Rechazar contraoferta",
      dialog_reject_offer_title: "Rechazar oferta",
      dialog_reject_offer_content: "Rechazarás la oferta de {amount}. La negociación finalizará.",
      dialog_reject_offer_confirm: "Rechazar oferta",
      dialog_solvency_title: "Verificación de solvencia",
      dialog_solvency_content: "Para continuar, necesitamos verificar tu capacidad financiera. ¿Deseas iniciar el proceso?",
      dialog_solvency_confirm: "Iniciar verificación",
      snack_offer_withdrawn: "Oferta retirada correctamente",
      snack_counter_accepted: "Contraoferta aceptada",
      snack_offer_sent: "Oferta enviada correctamente",
      snack_counter_rejected: "Contraoferta rechazada",
      snack_offer_rejected: "Oferta rechazada",
      snack_error: "Error al procesar la acción. Inténtalo de nuevo.",
      solvency_none: "No verificada"
    },
    arras_interview: {
      title_buyer: "Entrevista de Arras — Comprador",
      title_seller: "Entrevista de Arras — Vendedor",
      step1_header: "Logística y Notaría",
      step2_header: "Condiciones del Contrato",
      step3_header: "Financiación y Pago",
      notary_preference_label: "Preferencia de notaría",
      notary_preference_hint: "Ej.: Notaría Martínez, Paseo de Gracia 45",
      signing_deadline_label: "Plazo para la firma",
      preferred_date_label: "Fecha preferida para la firma",
      penalty_clause_label: "Cláusula penal",
      penalty_clause_subtitle: "Actívala si deseas incluir penalizaciones por incumplimiento",
      extension_allowed_label: "Prórroga permitida",
      extension_allowed_subtitle: "Actívala si permites prórroga del plazo por causa justificada",
      extension_reasons_label: "Motivos de prórroga aceptados",
      payment_method_label: "Método de financiación",
      payment_mortgage: "Hipoteca",
      payment_mixed: "Mixto (efectivo + hipoteca)",
      payment_other: "Otros",
      additional_clauses_label: "Cláusulas adicionales (opcional)",
      extension_reason_job_change: "Cambio laboral",
      extension_reason_financing: "Problemas de financiación",
      extension_reason_legal: "Trámites legales pendientes",
      extension_reason_other: "Otros",
      snack_sent: "Entrevista enviada correctamente",
      snack_error: "Error al enviar la entrevista. Inténtalo de nuevo."
    },
    visit_cancel: {
      title: "Cancelar visita",
      content: "Indica el motivo de la cancelación",
      reason_label: "Motivo",
      reason_withdraw_offer: "Retirar oferta",
      cancel_button: "Cerrar",
      confirm_button: "Confirmar cancelación",
      snack_cancelled: "Visita cancelada",
      snack_error: "Error al cancelar la visita"
    },
    ai_consent: {
      data_label: "Datos que se envían",
      provider_label: "Proveedor de la IA",
      cancel_button: "Cancelar",
      accept_button: "Acepto y continúo",
      error_message: "Es necesario aceptar el consentimiento para continuar"
    }
  },
  'en-US': {
    urgency: {
      sign_arras_ready: "Earnest money contract: Waiting for the other party to complete the interview",
      appraisal_pending: "Appraisal pending approval",
      fein_review: "Review the bank FEIN document",
      notary_confirm: "Confirm notary appointment date",
      handover_docs: "Prepare documentation for key handover",
      utilities_transfer: "Manage utilities transfer",
      counter_received: "You have received a counteroffer",
      offer_received: "You have received a new offer",
      visit_pending: "You have a visit pending confirmation",
      docs_pending: "Documents pending review",
      solvency_pending: "Solvency request pending",
      mortgage_docs: "Mortgage documents pending",
      survey_pending: "Post-sale survey pending"
    },
    transaction: {
      status_in_progress: "IN PROGRESS",
      role_buyer: "BUYER",
      role_seller: "SELLER",
      step_offer: "Offer Submitted",
      step_arras: "Earnest Money Contract",
      step_appraisal: "Property Appraisal",
      step_fein: "Bank Formalization (FEIN)",
      step_notary: "Notary Signing & Key Handover",
      step_post_sale: "Post-Sale & Utilities",
      help_action: "Talk to an advisor",
      footer_support: "Support",
      arras_status_pending_buyer: "Interview pending (buyer)",
      arras_status_pending_seller: "Interview pending (seller)",
      arras_status_both_done: "Both parties have completed the interview",
      arras_status_payment_pending: "Earnest money payment pending",
      arras_status_signed: "Contract signed by both parties",
      arras_status_cancelled: "Contract cancelled",
      arras_status_default: "Earnest money contract in progress",
      arras_cta_schedule: "Schedule signing",
      arras_cta_waiting_seller: "Waiting for seller to complete the interview",
      arras_cta_waiting_buyer: "Waiting for buyer to complete the interview",
      arras_cta_pay: "Make earnest money payment",
      arras_cta_done: "Contract finalized",
      arras_cta_default: "Manage contract",
      appraisal_status_requested: "Appraisal requested",
      appraisal_status_scheduled: "Appraisal scheduled",
      appraisal_status_completed: "Appraisal completed",
      appraisal_status_approved: "Appraisal approved by bank",
      appraisal_status_default: "Appraisal in progress",
      appraisal_cta_request: "Request appraisal",
      appraisal_cta_details: "View appraisal details",
      appraisal_cta_default: "Manage appraisal",
      fein_status_requested: "FEIN requested from bank",
      fein_status_reviewing: "Reviewing FEIN",
      fein_status_accepted: "FEIN accepted",
      fein_status_default: "Bank formalization in progress",
      fein_cta_request: "Request FEIN",
      fein_cta_review: "Review FEIN",
      fein_cta_default: "Manage FEIN",
      notary_status_scheduling: "Scheduling notary appointment",
      notary_status_scheduled: "Notary appointment confirmed",
      notary_status_done: "Signing completed",
      notary_status_default: "Notary formalization in progress",
      notary_cta_schedule: "Schedule notary appointment",
      notary_cta_confirm: "Confirm appointment",
      notary_cta_default: "Manage notary",
      dialog_withdraw_title: "Withdraw offer",
      dialog_withdraw_content: "You are about to withdraw your offer. This action cannot be undone.",
      dialog_withdraw_confirm: "Withdraw offer",
      dialog_accept_counter_title: "Accept counteroffer",
      dialog_accept_counter_content: "You will accept the counteroffer of {amount}. This will start the earnest money contract signing process.",
      dialog_accept_counter_confirm: "Accept counteroffer",
      dialog_new_offer_title: "New offer",
      dialog_new_offer_label: "New offer amount (€)",
      dialog_new_offer_confirm: "Submit offer",
      dialog_reject_counter_title: "Reject counteroffer",
      dialog_reject_counter_content: "You will reject the counteroffer. The negotiation will end.",
      dialog_reject_counter_confirm: "Reject counteroffer",
      dialog_reject_offer_title: "Reject offer",
      dialog_reject_offer_content: "You will reject the offer of {amount}. The negotiation will end.",
      dialog_reject_offer_confirm: "Reject offer",
      dialog_solvency_title: "Solvency verification",
      dialog_solvency_content: "To continue, we need to verify your financial capacity. Do you want to start the process?",
      dialog_solvency_confirm: "Start verification",
      snack_offer_withdrawn: "Offer withdrawn successfully",
      snack_counter_accepted: "Counteroffer accepted",
      snack_offer_sent: "Offer submitted successfully",
      snack_counter_rejected: "Counteroffer rejected",
      snack_offer_rejected: "Offer rejected",
      snack_error: "Error processing the action. Please try again.",
      solvency_none: "Not verified"
    },
    arras_interview: {
      title_buyer: "Earnest Money Interview — Buyer",
      title_seller: "Earnest Money Interview — Seller",
      step1_header: "Logistics & Notary",
      step2_header: "Contract Terms",
      step3_header: "Financing & Payment",
      notary_preference_label: "Notary preference",
      notary_preference_hint: "E.g.: Notary Martinez, 45 Passeig de Gracia",
      signing_deadline_label: "Signing deadline",
      preferred_date_label: "Preferred signing date",
      penalty_clause_label: "Penalty clause",
      penalty_clause_subtitle: "Enable if you want to include penalties for non-compliance",
      extension_allowed_label: "Extension allowed",
      extension_allowed_subtitle: "Enable if you allow a deadline extension for justified cause",
      extension_reasons_label: "Accepted extension reasons",
      payment_method_label: "Financing method",
      payment_mortgage: "Mortgage",
      payment_mixed: "Mixed (cash + mortgage)",
      payment_other: "Other",
      additional_clauses_label: "Additional clauses (optional)",
      extension_reason_job_change: "Job change",
      extension_reason_financing: "Financing issues",
      extension_reason_legal: "Pending legal procedures",
      extension_reason_other: "Other",
      snack_sent: "Interview submitted successfully",
      snack_error: "Error submitting the interview. Please try again."
    },
    visit_cancel: {
      title: "Cancel visit",
      content: "Please indicate the reason for cancellation",
      reason_label: "Reason",
      reason_withdraw_offer: "Withdraw offer",
      cancel_button: "Close",
      confirm_button: "Confirm cancellation",
      snack_cancelled: "Visit cancelled",
      snack_error: "Error cancelling the visit"
    },
    ai_consent: {
      data_label: "Data being sent",
      provider_label: "AI Provider",
      cancel_button: "Cancel",
      accept_button: "I accept and continue",
      error_message: "You must accept the consent to continue"
    }
  },
  'fr-FR': {
    urgency: {
      sign_arras_ready: "Avant-contrat : en attente que l'autre partie complete l'entretien",
      appraisal_pending: "Expertise en attente d'approbation",
      fein_review: "Examiner le FEIN de la banque",
      notary_confirm: "Confirmer la date chez le notaire",
      handover_docs: "Preparer les documents pour la remise des cles",
      utilities_transfer: "Gerer le transfert des contrats d'energie",
      counter_received: "Vous avez recu une contre-offre",
      offer_received: "Vous avez recu une nouvelle offre",
      visit_pending: "Vous avez une visite en attente de confirmation",
      docs_pending: "Documents en attente de revision",
      solvency_pending: "Demande de solvabilite en attente",
      mortgage_docs: "Documents hypothecaires en attente",
      survey_pending: "Enquete post-vente en attente"
    },
    transaction: {
      status_in_progress: "EN COURS",
      role_buyer: "ACHETEUR",
      role_seller: "VENDEUR",
      step_offer: "Offre soumise",
      step_arras: "Avant-contrat (arrhes)",
      step_appraisal: "Expertise du bien",
      step_fein: "Formalisation bancaire (FEIN)",
      step_notary: "Signature chez le notaire et remise des cles",
      step_post_sale: "Post-vente et contrats d'energie",
      help_action: "Parler a un conseiller",
      footer_support: "Assistance",
      arras_status_pending_buyer: "Entretien en attente (acheteur)",
      arras_status_pending_seller: "Entretien en attente (vendeur)",
      arras_status_both_done: "Les deux parties ont complete l'entretien",
      arras_status_payment_pending: "Paiement des arrhes en attente",
      arras_status_signed: "Contrat signe par les deux parties",
      arras_status_cancelled: "Contrat annule",
      arras_status_default: "Avant-contrat en cours",
      arras_cta_schedule: "Planifier la signature",
      arras_cta_waiting_seller: "En attente que le vendeur complete l'entretien",
      arras_cta_waiting_buyer: "En attente que l'acheteur complete l'entretien",
      arras_cta_pay: "Effectuer le paiement des arrhes",
      arras_cta_done: "Contrat finalise",
      arras_cta_default: "Gerer les arrhes",
      appraisal_status_requested: "Expertise demandee",
      appraisal_status_scheduled: "Expertise planifiee",
      appraisal_status_completed: "Expertise completee",
      appraisal_status_approved: "Expertise approuvee par la banque",
      appraisal_status_default: "Expertise en cours",
      appraisal_cta_request: "Demander une expertise",
      appraisal_cta_details: "Voir les details de l'expertise",
      appraisal_cta_default: "Gerer l'expertise",
      fein_status_requested: "FEIN demande a la banque",
      fein_status_reviewing: "Examen du FEIN en cours",
      fein_status_accepted: "FEIN accepte",
      fein_status_default: "Formalisation bancaire en cours",
      fein_cta_request: "Demander le FEIN",
      fein_cta_review: "Examiner le FEIN",
      fein_cta_default: "Gerer le FEIN",
      notary_status_scheduling: "Planification du rendez-vous chez le notaire",
      notary_status_scheduled: "Rendez-vous chez le notaire confirme",
      notary_status_done: "Signature completee",
      notary_status_default: "Formalisation notariale en cours",
      notary_cta_schedule: "Planifier le rendez-vous chez le notaire",
      notary_cta_confirm: "Confirmer le rendez-vous",
      notary_cta_default: "Gerer le notaire",
      dialog_withdraw_title: "Retirer l'offre",
      dialog_withdraw_content: "Vous etes sur le point de retirer votre offre. Cette action est irreversible.",
      dialog_withdraw_confirm: "Retirer l'offre",
      dialog_accept_counter_title: "Accepter la contre-offre",
      dialog_accept_counter_content: "Vous allez accepter la contre-offre de {amount}. Cela lancera le processus de signature de l'avant-contrat.",
      dialog_accept_counter_confirm: "Accepter la contre-offre",
      dialog_new_offer_title: "Nouvelle offre",
      dialog_new_offer_label: "Montant de la nouvelle offre (€)",
      dialog_new_offer_confirm: "Soumettre l'offre",
      dialog_reject_counter_title: "Rejeter la contre-offre",
      dialog_reject_counter_content: "Vous allez rejeter la contre-offre. La negociation prendra fin.",
      dialog_reject_counter_confirm: "Rejeter la contre-offre",
      dialog_reject_offer_title: "Rejeter l'offre",
      dialog_reject_offer_content: "Vous allez rejeter l'offre de {amount}. La negociation prendra fin.",
      dialog_reject_offer_confirm: "Rejeter l'offre",
      dialog_solvency_title: "Verification de solvabilite",
      dialog_solvency_content: "Pour continuer, nous devons verifier votre capacite financiere. Voulez-vous demarrer le processus ?",
      dialog_solvency_confirm: "Demarrer la verification",
      snack_offer_withdrawn: "Offre retiree avec succes",
      snack_counter_accepted: "Contre-offre acceptee",
      snack_offer_sent: "Offre soumise avec succes",
      snack_counter_rejected: "Contre-offre rejetee",
      snack_offer_rejected: "Offre rejetee",
      snack_error: "Erreur lors du traitement de l'action. Veuillez reessayer.",
      solvency_none: "Non verifiee"
    },
    arras_interview: {
      title_buyer: "Entretien avant-contrat — Acheteur",
      title_seller: "Entretien avant-contrat — Vendeur",
      step1_header: "Logistique et notaire",
      step2_header: "Conditions du contrat",
      step3_header: "Financement et paiement",
      notary_preference_label: "Preference de notaire",
      notary_preference_hint: "Ex. : Maitre Dupont, 45 rue de la Paix",
      signing_deadline_label: "Delai de signature",
      preferred_date_label: "Date de signature souhaitee",
      penalty_clause_label: "Clause penale",
      penalty_clause_subtitle: "Activez si vous souhaitez inclure des penalites en cas de manquement",
      extension_allowed_label: "Prolongation autorisee",
      extension_allowed_subtitle: "Activez si vous autorisez une prolongation du delai pour motif justifie",
      extension_reasons_label: "Motifs de prolongation acceptes",
      payment_method_label: "Mode de financement",
      payment_mortgage: "Pret immobilier",
      payment_mixed: "Mixte (apport + pret)",
      payment_other: "Autre",
      additional_clauses_label: "Clauses supplementaires (optionnel)",
      extension_reason_job_change: "Changement professionnel",
      extension_reason_financing: "Difficultes de financement",
      extension_reason_legal: "Demarches administratives en cours",
      extension_reason_other: "Autre",
      snack_sent: "Entretien soumis avec succes",
      snack_error: "Erreur lors de la soumission de l'entretien. Veuillez reessayer."
    },
    visit_cancel: {
      title: "Annuler la visite",
      content: "Veuillez indiquer le motif d'annulation",
      reason_label: "Motif",
      reason_withdraw_offer: "Retirer l'offre",
      cancel_button: "Fermer",
      confirm_button: "Confirmer l'annulation",
      snack_cancelled: "Visite annulee",
      snack_error: "Erreur lors de l'annulation de la visite"
    },
    ai_consent: {
      data_label: "Donnees transmises",
      provider_label: "Fournisseur IA",
      cancel_button: "Annuler",
      accept_button: "J'accepte et continue",
      error_message: "Vous devez accepter le consentement pour continuer"
    }
  }
};

translations['en-GB'] = JSON.parse(JSON.stringify(translations['en-US']));
translations['en-CA'] = JSON.parse(JSON.stringify(translations['en-US']));
translations['fr-CA'] = JSON.parse(JSON.stringify(translations['fr-FR']));

const langs = Object.keys(translations);

langs.forEach(lang => {
  const filePath = base + lang + '.json';
  const json = JSON.parse(fs.readFileSync(filePath, 'utf8'));
  const t = translations[lang];
  Object.keys(t).forEach(block => {
    if (!json[block]) json[block] = {};
    Object.assign(json[block], t[block]);
  });
  fs.writeFileSync(filePath, JSON.stringify(json, null, 2), 'utf8');
  console.log('Updated ' + lang + ' — urgency keys: ' + Object.keys(json.urgency || {}).length);
});

const esEs = JSON.parse(fs.readFileSync(base + 'es-ES.json', 'utf8'));
const enUs = JSON.parse(fs.readFileSync(base + 'en-US.json', 'utf8'));
const frFr = JSON.parse(fs.readFileSync(base + 'fr-FR.json', 'utf8'));
console.log('\nVerification:');
console.log('es-ES urgency.counter_received:', esEs.urgency && esEs.urgency.counter_received);
console.log('en-US transaction.role_buyer:', enUs.transaction && enUs.transaction.role_buyer);
console.log('fr-FR arras_interview.title_buyer:', frFr.arras_interview && frFr.arras_interview.title_buyer);
console.log('en-GB visit_cancel.confirm_button:', JSON.parse(fs.readFileSync(base + 'en-GB.json', 'utf8')).visit_cancel && JSON.parse(fs.readFileSync(base + 'en-GB.json', 'utf8')).visit_cancel.confirm_button);
