const fs=require('fs'),path=require('path');
const dir=path.join(__dirname,'..','assets','translations');

const t={
es:{
fein_title:"Paso previo a la Notaria",
fein_buyer_banner:"Tu banco ha recibido el informe de tasacion y debe emitir la FEIN al menos 10 dias antes de la firma. Confirma cuando la hayas recibido.",
fein_seller_banner:"El banco del comprador esta procesando la FEIN. Recibiras una notificacion cuando el comprador confirme.",
fein_what_is:"Que es la FEIN?",
fein_faq1_title:"FEIN",fein_faq1_body:"Ficha Europea de Informacion Normalizada. Documento oficial del banco con las condiciones definitivas del prestamo.",
fein_faq2_title:"FIPER",fein_faq2_body:"Ficha de Informacion Personalizada. Version espanola equivalente a la FEIN para prestamos variables.",
fein_faq3_title:"10 dias",fein_faq3_body:"Plazo obligatorio entre la recepcion de la FEIN y la firma en notaria. Exigido por ley (LCCI 2019).",
fein_process_title:"Proceso bancario",
fein_step1_title:"Tasacion completada",fein_step1_body:"El banco recibe el informe del tasador",
fein_step2_title:"Banco estudia la operacion",fein_step2_body:"Calcula riesgo con la tasacion oficial",
fein_step3_title:"Banco emite la FEIN",fein_step3_body:"Te la envian por correo o app bancaria",
fein_step4_title:"Periodo de reflexion (10 dias)",fein_step4_body:"Lee con calma todas las condiciones",
fein_step5_title:"Firma en Notaria",fein_step5_body:"Con la FEIN aceptada, se puede firmar",
fein_form_title:"Confirmar recepcion de la FEIN",
fein_check1:"He recibido la FEIN/FIPER de mi banco con las condiciones definitivas.",
fein_check2:"He leido y entiendo las condiciones del prestamo (TAE, cuota, vinculaciones).",
fein_form_warn:"Tras confirmar, deberan pasar al menos 10 dias antes de poder firmar en notaria. Este plazo es obligatorio por ley (LCCI 2019).",
fein_seller_wait_title:"Esperando confirmacion del comprador",
fein_seller_wait_body:"El banco del comprador esta tramitando la FEIN. Recibiras notificacion cuando el comprador la confirme.",
fein_error_confirm:"Error al confirmar. Verifica que la tasacion este completada.",
fein_success_title:"FEIN confirmada",
fein_success_buyer:"Has confirmado la recepcion de la FEIN. El plazo de 10 dias es informativo — ya puedes coordinar la cita en notaria.",
fein_success_seller:"El comprador ha confirmado la FEIN. Ya podeis coordinar la cita en notaria para la firma final.",
fein_success_warn:"La ley exige 10 dias entre la recepcion de la FEIN y la firma. Asegurate de coordinar la cita con ese margen.",
fein_goto_notary:"Ir a Firma en Notaria",
fein_back_timeline:"Volver al timeline"
},
en:{
fein_title:"Pre-Notary Step",
fein_buyer_banner:"Your bank has received the appraisal report and must issue the FEIN at least 10 days before signing. Confirm when you have received it.",
fein_seller_banner:"The buyer's bank is processing the FEIN. You will receive a notification when the buyer confirms.",
fein_what_is:"What is the FEIN?",
fein_faq1_title:"FEIN",fein_faq1_body:"European Standardised Information Sheet. Official bank document with the final loan conditions.",
fein_faq2_title:"FIPER",fein_faq2_body:"Customized Information Sheet. Spanish equivalent to FEIN for variable loans.",
fein_faq3_title:"10 days",fein_faq3_body:"Mandatory period between receiving the FEIN and signing at the notary. Required by law (LCCI 2019).",
fein_process_title:"Banking Process",
fein_step1_title:"Appraisal completed",fein_step1_body:"The bank receives the appraiser's report",
fein_step2_title:"Bank studies the operation",fein_step2_body:"Calculates risk with the official appraisal",
fein_step3_title:"Bank issues the FEIN",fein_step3_body:"Sent to you by mail or banking app",
fein_step4_title:"Cooling-off period (10 days)",fein_step4_body:"Read all conditions carefully",
fein_step5_title:"Notary Signing",fein_step5_body:"With accepted FEIN, signing can proceed",
fein_form_title:"Confirm FEIN receipt",
fein_check1:"I have received the FEIN/FIPER from my bank with the final conditions.",
fein_check2:"I have read and understand the loan conditions (APR, installment, ties).",
fein_form_warn:"After confirming, at least 10 days must pass before signing at the notary. This period is required by law (LCCI 2019).",
fein_seller_wait_title:"Waiting for buyer confirmation",
fein_seller_wait_body:"The buyer's bank is processing the FEIN. You will receive a notification when the buyer confirms it.",
fein_error_confirm:"Error confirming. Verify the appraisal is completed.",
fein_success_title:"FEIN confirmed",
fein_success_buyer:"You have confirmed the receipt of the FEIN. The 10-day period is informative — you can now coordinate the notary appointment.",
fein_success_seller:"The buyer has confirmed the FEIN. You can now coordinate the notary appointment for the final signing.",
fein_success_warn:"The law requires 10 days between receiving the FEIN and signing. Ensure to coordinate the appointment with that margin.",
fein_goto_notary:"Go to Notary Signing",
fein_back_timeline:"Back to timeline"
},
fr:{
fein_title:"Etape pre-Notaire",
fein_buyer_banner:"Votre banque a recu le rapport d'expertise et doit emettre la FEIN au moins 10 jours avant la signature. Confirmez lorsque vous l'avez recu.",
fein_seller_banner:"La banque de l'acheteur traite la FEIN. Vous recevrez une notification lorsque l'acheteur confirmera.",
fein_what_is:"Qu'est-ce que la FEIN ?",
fein_faq1_title:"FEIN",fein_faq1_body:"Fiche Europeenne d'Information Standardisee. Document bancaire officiel avec les conditions definitives du pret.",
fein_faq2_title:"FIPER",fein_faq2_body:"Fiche d'Information Personnalisee. Equivalent espagnol a la FEIN pour les prets variables.",
fein_faq3_title:"10 jours",fein_faq3_body:"Delai obligatoire entre la reception de la FEIN et la signature chez le notaire. Requis par la loi (LCCI 2019).",
fein_process_title:"Processus bancaire",
fein_step1_title:"Expertise terminee",fein_step1_body:"La banque recoit le rapport de l'expert",
fein_step2_title:"La banque etudie l'operation",fein_step2_body:"Calcule le risque avec l'expertise officielle",
fein_step3_title:"La banque emet la FEIN",fein_step3_body:"Envoyee par courrier ou application bancaire",
fein_step4_title:"Delai de reflexion (10 jours)",fein_step4_body:"Lisez attentivement toutes les conditions",
fein_step5_title:"Signature Notaire",fein_step5_body:"Avec la FEIN acceptee, la signature peut avoir lieu",
fein_form_title:"Confirmer la reception de la FEIN",
fein_check1:"J'ai recu la FEIN/FIPER de ma banque avec les conditions definitives.",
fein_check2:"J'ai lu et compris les conditions du pret (TAEG, mensualite, liens).",
fein_form_warn:"Apres confirmation, au moins 10 jours doivent s'ecouler avant la signature chez le notaire. Ce delai est legal (LCCI 2019).",
fein_seller_wait_title:"En attente de la confirmation de l'acheteur",
fein_seller_wait_body:"La banque de l'acheteur traite la FEIN. Vous serez notifie lorsque l'acheteur la confirmera.",
fein_error_confirm:"Erreur de confirmation. Verifiez que l'expertise est terminee.",
fein_success_title:"FEIN confirmee",
fein_success_buyer:"Vous avez confirme la reception de la FEIN. Le delai de 10 jours est informatif — vous pouvez coordonner le rendez-vous chez le notaire.",
fein_success_seller:"L'acheteur a confirme la FEIN. Vous pouvez coordonner le rendez-vous notarial pour la signature finale.",
fein_success_warn:"La loi exige 10 jours entre la reception de la FEIN et la signature. Veillez a coordonner le rendez-vous avec cette marge.",
fein_goto_notary:"Aller a la Signature chez le Notaire",
fein_back_timeline:"Retour a la timeline"
},
ca:{
fein_title:"Pas previ a la Notaria",
fein_buyer_banner:"El teu banc ha rebut l'informe de taxacio i ha d'emetre la FEIN almenys 10 dies abans de la signatura. Confirma quan l'hagis rebut.",
fein_seller_banner:"El banc del comprador esta processant la FEIN. Rebras una notificacio quan el comprador confirmi.",
fein_what_is:"Que es la FEIN?",
fein_faq1_title:"FEIN",fein_faq1_body:"Fitxa Europea d'Informacio Normalitzada. Document oficial del banc amb les condicions definitives del prestec.",
fein_faq2_title:"FIPER",fein_faq2_body:"Fitxa d'Informacio Personalitzada. Versio espanyola equivalent a la FEIN per a prestecs variables.",
fein_faq3_title:"10 dies",fein_faq3_body:"Termini obligatori entre la recepcio de la FEIN i la signatura a notaria. Exigit per llei (LCCI 2019).",
fein_process_title:"Proces bancari",
fein_step1_title:"Taxacio completada",fein_step1_body:"El banc rep l'informe del taxador",
fein_step2_title:"Banc estudia l'operacio",fein_step2_body:"Calcula risc amb la taxacio oficial",
fein_step3_title:"Banc emet la FEIN",fein_step3_body:"Te l'envien per correu o app bancaria",
fein_step4_title:"Periode de reflexio (10 dies)",fein_step4_body:"Llegeix amb calma totes les condicions",
fein_step5_title:"Signatura a Notaria",fein_step5_body:"Amb la FEIN acceptada, es pot signar",
fein_form_title:"Confirmar recepcio de la FEIN",
fein_check1:"He rebut la FEIN/FIPER del meu banc amb les condicions definitives.",
fein_check2:"He llegit i entenc les condicions del prestec (TAE, quota, vinculacions).",
fein_form_warn:"Despres de confirmar, hauran de passar almenys 10 dies abans de poder signar a notaria. Aquest termini es obligatori per llei (LCCI 2019).",
fein_seller_wait_title:"Esperant confirmacio del comprador",
fein_seller_wait_body:"El banc del comprador esta tramitant la FEIN. Rebras notificacio quan el comprador la confirmi.",
fein_error_confirm:"Error en confirmar. Verifica que la taxacio estigui completada.",
fein_success_title:"FEIN confirmada",
fein_success_buyer:"Has confirmat la recepcio de la FEIN. El termini de 10 dies es informatiu — ja pots coordinar la cita a notaria.",
fein_success_seller:"El comprador ha confirmat la FEIN. Ja podeu coordinar la cita a notaria per a la signatura final.",
fein_success_warn:"La llei exigeix 10 dies entre la recepcio de la FEIN i la signatura. Assegura't de coordinar la cita amb aquest marge.",
fein_goto_notary:"Anar a Signatura a Notaria",
fein_back_timeline:"Tornar al timeline"
},
eu:{
fein_title:"Notaria aurreko urratsa",
fein_buyer_banner:"Zure bankuak tasazio txostena jaso du eta FEINa eman behar du sinatu baino gutxienez 10 egun lehenago. Berretsi jaso duzunean.",
fein_seller_banner:"Eroslearen bankua FEINa prozesatzen ari da. Jakinarazpen bat jasoko duzu erosleak berresten duenean.",
fein_what_is:"Zer da FEIN?",
fein_faq1_title:"FEIN",fein_faq1_body:"Informazio Normalizatuaren Europako Fitxa. Bankuaren agiri ofiziala maileguaren behin betiko baldintzekin.",
fein_faq2_title:"FIPER",fein_faq2_body:"Informazio Pertsonalizatuaren Fitxa. Aldagai maileguetarako FEINaren baliokidea Espainian.",
fein_faq3_title:"10 egun",fein_faq3_body:"FEINa jaso eta notarioan sinatu arteko derrigorrezko epea. Legez eskatua (LCCI 2019).",
fein_process_title:"Banku prozesua",
fein_step1_title:"Tasazioa osatuta",fein_step1_body:"Bankuak tasatzailearen txostena jasotzen du",
fein_step2_title:"Bankuak operazioa aztertzen du",fein_step2_body:"Arriskua kalkulatzen du tasazio ofizialarekin",
fein_step3_title:"Bankuak FEINa ematen du",fein_step3_body:"Postaz edo banku app bidez bidaltzen dizute",
fein_step4_title:"Gogoeta epea (10 egun)",fein_step4_body:"Irakurri arretaz baldintza guztiak",
fein_step5_title:"Notarioan Sinadura",fein_step5_body:"FEINa onartuta, sinatu daiteke",
fein_form_title:"FEIN jasotzea berretsi",
fein_check1:"Nire bankuaren FEIN/FIPER jaso dut behin betiko baldintzekin.",
fein_check2:"Maileguaren baldintzak (UTB, kuota, loturak) irakurri eta ulertzen ditut.",
fein_form_warn:"Berretsi ondoren, gutxienez 10 egun igaro beharko dira notarioan sinatu ahal izateko. Epe hau legez derrigorrezkoa da (LCCI 2019).",
fein_seller_wait_title:"Eroslearen berrespenaren zain",
fein_seller_wait_body:"Eroslearen bankua FEINa bideratzen ari da. Erosleak berresten duenean jakinarazpena jasoko duzu.",
fein_error_confirm:"Errorea berrestean. Egiaztatu tasazioa osatuta dagoela.",
fein_success_title:"FEIN berretsita",
fein_success_buyer:"FEINaren harrera berretsi duzu. 10 eguneko epea informatiboa da — hitzordua notarioan koordinatu dezakezu dagoeneko.",
fein_success_seller:"Erosleak FEINa berretsi du. Azken sinadurarako hitzordua notarioan koordinatu dezakezue dagoeneko.",
fein_success_warn:"Legeak 10 egun eskatzen ditu FEINa jaso eta sinadura artean. Ziurtatu hitzordua tarte horrekin koordinatzen duzula.",
fein_goto_notary:"Notarioan Sinadurara joan",
fein_back_timeline:"Timeline-ra itzuli"
},
gl:{
fein_title:"Paso previo a Notaría",
fein_buyer_banner:"O teu banco recibiu o informe de taxacion e debe emitir a FEIN polo menos 10 dias antes da sinatura. Confirma cando a recibiras.",
fein_seller_banner:"O banco do comprador esta a procesar a FEIN. Recibiras unha notificacion cando o comprador confirme.",
fein_what_is:"Que e a FEIN?",
fein_faq1_title:"FEIN",fein_faq1_body:"Ficha Europea de Informacion Normalizada. Documento oficial do banco coas condicions definitivas do prestamo.",
fein_faq2_title:"FIPER",fein_faq2_body:"Ficha de Informacion Personalizada. Version española equivalente a FEIN para prestamos variables.",
fein_faq3_title:"10 dias",fein_faq3_body:"Prazo obrigatorio entre a recepcion da FEIN e a sinatura en notaría. Esixido por lei (LCCI 2019).",
fein_process_title:"Proceso bancario",
fein_step1_title:"Taxacion completada",fein_step1_body:"O banco recibe o informe do taxador",
fein_step2_title:"Banco estuda a operacion",fein_step2_body:"Calcula risco coa taxacion oficial",
fein_step3_title:"Banco emite a FEIN",fein_step3_body:"Enviancha por correo ou app bancaria",
fein_step4_title:"Periodo de reflexion (10 dias)",fein_step4_body:"Le con calma todas as condicions",
fein_step5_title:"Sinatura en Notaría",fein_step5_body:"Coa FEIN aceptada, podese asinar",
fein_form_title:"Confirmar recepcion da FEIN",
fein_check1:"Recibin a FEIN/FIPER do meu banco coas condicions definitivas.",
fein_check2:"Lin e entendo as condicions do prestamo (TAE, cota, vinculacions).",
fein_form_warn:"Tras confirmar, deberan pasar polo menos 10 dias antes de poder asinar en notaría. Este prazo e obrigatorio por lei (LCCI 2019).",
fein_seller_wait_title:"Agardando confirmacion do comprador",
fein_seller_wait_body:"O banco do comprador esta a tramitar a FEIN. Recibiras notificacion cando o comprador a confirme.",
fein_error_confirm:"Erro ao confirmar. Verifica que a taxacion estea completada.",
fein_success_title:"FEIN confirmada",
fein_success_buyer:"Confirmaches a recepcion da FEIN. O prazo de 10 dias e informativo — xa podes coordinar a cita en notaría.",
fein_success_seller:"O comprador confirmou a FEIN. Xa podedes coordinar a cita en notaría para a sinatura final.",
fein_success_warn:"A lei esixe 10 dias entre a recepcion da FEIN e a sinatura. Asegurate de coordinar a cita con esa marxe.",
fein_goto_notary:"Ir a Sinatura en Notaría",
fein_back_timeline:"Volver ao timeline"
}
};

const map={
'es-ES':'es','en-US':'en','en-GB':'en','en-CA':'en',
'fr-FR':'fr','fr-CA':'fr','ca-ES':'ca','eu-ES':'eu','gl-ES':'gl'
};

Object.entries(map).forEach(([locale,lang])=>{
  const file=path.join(dir,locale+'.json');
  const json=JSON.parse(fs.readFileSync(file,'utf8'));
  Object.assign(json.transaction, t[lang]);
  fs.writeFileSync(file,JSON.stringify(json,null,2)+'\n','utf8');
  console.log(`${locale}: +${Object.keys(t[lang]).length} fein keys`);
});
