const fs=require('fs'),path=require('path');
const dir=path.join(__dirname,'..','assets','translations');

const t={
es:{
  keys_confirm_wait_snack: "Tu confirmacion registrada. Esperando a la otra parte.",
  keys_confirm_error: "Error al confirmar. Intentalo de nuevo.",
  keys_completed_title: "Transaccion completada",
  keys_completed_desc: "Felicidades. La compraventa ha finalizado con exito.\nLas llaves han sido entregadas.",
  keys_accept: "Aceptar",
  keys_delivered_title: "Llaves entregadas",
  keys_pending_title: "Entrega de llaves pendiente",
  keys_delivered_desc: "La transaccion ha concluido exitosamente.",
  keys_pending_desc: "Ambas partes deben confirmar la entrega\npara cerrar la transaccion.",
  keys_seller: "Vendedor",
  keys_buyer: "Comprador",
  keys_confirmed: "Entrega confirmada",
  keys_confirm_prompt: "Confirma cuando hayas entregado/recibido las llaves",
  keys_waiting_confirm: "Esperando confirmacion",
  keys_confirm_btn: "Confirmar",
  keys_docs_title: "Documentacion a entregar",
  keys_doc1: "Copia de las escrituras firmadas",
  keys_doc2: "Certificado energetico (CEE)",
  keys_doc3: "Manual de uso de la vivienda",
  keys_doc4: "Llaves de todas las cerraduras",
  keys_doc5: "Tarjeta de garantia de electrodomesticos",
  keys_doc6: "Datos de la comunidad y administrador",
  keys_tips_title: "Consejos para la entrega",
  keys_tip1: "Revisa el estado de la vivienda antes de firmar la entrega",
  keys_tip2: "Anota las lecturas de los contadores de agua, luz y gas",
  keys_tip3: "Solicita el certificado de estar al corriente de pagos en la comunidad",
  keys_tip4: "Cambia el cilindro de la cerradura por seguridad"
},
en:{
  keys_confirm_wait_snack: "Your confirmation is registered. Waiting for the other party.",
  keys_confirm_error: "Error confirming. Please try again.",
  keys_completed_title: "Transaction completed",
  keys_completed_desc: "Congratulations. The sale has been successfully completed.\nThe keys have been delivered.",
  keys_accept: "Accept",
  keys_delivered_title: "Keys delivered",
  keys_pending_title: "Key delivery pending",
  keys_delivered_desc: "The transaction has successfully concluded.",
  keys_pending_desc: "Both parties must confirm the delivery\nto close the transaction.",
  keys_seller: "Seller",
  keys_buyer: "Buyer",
  keys_confirmed: "Delivery confirmed",
  keys_confirm_prompt: "Confirm when you have delivered/received the keys",
  keys_waiting_confirm: "Waiting for confirmation",
  keys_confirm_btn: "Confirm",
  keys_docs_title: "Documentation to deliver",
  keys_doc1: "Copy of signed deeds",
  keys_doc2: "Energy certificate (EPC)",
  keys_doc3: "Home user manual",
  keys_doc4: "Keys for all locks",
  keys_doc5: "Appliance warranty cards",
  keys_doc6: "Community and administrator details",
  keys_tips_title: "Delivery tips",
  keys_tip1: "Check the state of the home before signing the delivery",
  keys_tip2: "Record water, electricity, and gas meter readings",
  keys_tip3: "Request the certificate of being up to date with community payments",
  keys_tip4: "Change the lock cylinder for security"
},
fr:{
  keys_confirm_wait_snack: "Votre confirmation est enregistree. En attente de l'autre partie.",
  keys_confirm_error: "Erreur lors de la confirmation. Veuillez reessayer.",
  keys_completed_title: "Transaction terminee",
  keys_completed_desc: "Felicitations. La vente a ete conclue avec succes.\nLes cles ont ete remises.",
  keys_accept: "Accepter",
  keys_delivered_title: "Cles remises",
  keys_pending_title: "Remise des cles en attente",
  keys_delivered_desc: "La transaction s'est conclue avec succes.",
  keys_pending_desc: "Les deux parties doivent confirmer la remise\npour cloturer la transaction.",
  keys_seller: "Vendeur",
  keys_buyer: "Acheteur",
  keys_confirmed: "Remise confirmee",
  keys_confirm_prompt: "Confirmez lorsque vous avez remis/recu les cles",
  keys_waiting_confirm: "En attente de confirmation",
  keys_confirm_btn: "Confirmer",
  keys_docs_title: "Documentation a remettre",
  keys_doc1: "Copie des actes signes",
  keys_doc2: "Certificat energetique (DPE)",
  keys_doc3: "Manuel d'utilisation du logement",
  keys_doc4: "Cles de toutes les serrures",
  keys_doc5: "Cartes de garantie des appareils electromenagers",
  keys_doc6: "Coordonnees de la copropriete et de l'administrateur",
  keys_tips_title: "Conseils pour la remise",
  keys_tip1: "Verifiez l'etat du logement avant de signer la remise",
  keys_tip2: "Relevez les compteurs d'eau, d'electricite et de gaz",
  keys_tip3: "Demandez le certificat d'absence de dettes envers la copropriete",
  keys_tip4: "Changez le cylindre de la serrure pour plus de securite"
},
ca:{
  keys_confirm_wait_snack: "La teva confirmacio esta registrada. Esperant a l'altra part.",
  keys_confirm_error: "Error en confirmar. Torna-ho a provar.",
  keys_completed_title: "Transaccio completada",
  keys_completed_desc: "Felicitats. La compravenda ha finalitzat amb exit.\nLes claus han estat lliurades.",
  keys_accept: "Acceptar",
  keys_delivered_title: "Claus lliurades",
  keys_pending_title: "Lliurament de claus pendent",
  keys_delivered_desc: "La transaccio ha conclos exitosament.",
  keys_pending_desc: "Ambdues parts han de confirmar el lliurament\nper tancar la transaccio.",
  keys_seller: "Venedor",
  keys_buyer: "Comprador",
  keys_confirmed: "Lliurament confirmat",
  keys_confirm_prompt: "Confirma quan hagis lliurat/rebut les claus",
  keys_waiting_confirm: "Esperant confirmacio",
  keys_confirm_btn: "Confirmar",
  keys_docs_title: "Documentacio a lliurar",
  keys_doc1: "Copia de les escriptures signades",
  keys_doc2: "Certificat energetic (CEE)",
  keys_doc3: "Manual d'us de l'habitatge",
  keys_doc4: "Claus de totes les panys",
  keys_doc5: "Targeta de garantia d'electrodomestics",
  keys_doc6: "Dades de la comunitat i administrador",
  keys_tips_title: "Consells per al lliurament",
  keys_tip1: "Revisa l'estat de l'habitatge abans de signar el lliurament",
  keys_tip2: "Anota les lectures dels comptadors d'aigua, llum i gas",
  keys_tip3: "Sol·licita el certificat d'estar al corrent de pagaments a la comunitat",
  keys_tip4: "Canvia el cilindre del pany per seguretat"
},
eu:{
  keys_confirm_wait_snack: "Zure berrespena erregistratu da. Beste aldearen zain.",
  keys_confirm_error: "Errorea berrestean. Saiatu berriro.",
  keys_completed_title: "Transakzioa osatuta",
  keys_completed_desc: "Zorionak. Salerosketa arrakastaz amaitu da.\nGiltzak entregatu dira.",
  keys_accept: "Onartu",
  keys_delivered_title: "Giltzak entregatuta",
  keys_pending_title: "Giltzak entregatzeko zain",
  keys_delivered_desc: "Transakzioa arrakastaz amaitu da.",
  keys_pending_desc: "Bi aldeek entrega berretsi behar dute\ntransakzioa ixteko.",
  keys_seller: "Saltzailea",
  keys_buyer: "Eroslea",
  keys_confirmed: "Entrega berretsita",
  keys_confirm_prompt: "Berretsi giltzak entregatu/jaso dituzunean",
  keys_waiting_confirm: "Berrespenaren zain",
  keys_confirm_btn: "Berretsi",
  keys_docs_title: "Entregatu beharreko dokumentazioa",
  keys_doc1: "Sinatutako eskrituren kopia",
  keys_doc2: "Ziurtagiri energetikoa (CEE)",
  keys_doc3: "Etxebizitzaren erabilera eskuliburua",
  keys_doc4: "Sarraila guztien giltzak",
  keys_doc5: "Etxetresna elektrikoen berme-txartela",
  keys_doc6: "Komunitatearen eta administratzailearen datuak",
  keys_tips_title: "Entregarako aholkuak",
  keys_tip1: "Egiaztatu etxebizitzaren egoera entrega sinatu aurretik",
  keys_tip2: "Idatzi ur, argi eta gas kontagailuen irakurketak",
  keys_tip3: "Eskatu komunitatean ordainketak egunean izatearen ziurtagiria",
  keys_tip4: "Aldatu sarrailaren zilindroa segurtasunagatik"
},
gl:{
  keys_confirm_wait_snack: "A túa confirmación rexistrada. Agardando á outra parte.",
  keys_confirm_error: "Erro ao confirmar. Téntao de novo.",
  keys_completed_title: "Transacción completada",
  keys_completed_desc: "Parabéns. A compravenda finalizou con éxito.\nAs chaves foron entregadas.",
  keys_accept: "Aceptar",
  keys_delivered_title: "Chaves entregadas",
  keys_pending_title: "Entrega de chaves pendente",
  keys_delivered_desc: "A transacción concluíu exitosamente.",
  keys_pending_desc: "Ambas as partes deben confirmar a entrega\npara pechar a transacción.",
  keys_seller: "Vendedor",
  keys_buyer: "Comprador",
  keys_confirmed: "Entrega confirmada",
  keys_confirm_prompt: "Confirma cando entregases/recibises as chaves",
  keys_waiting_confirm: "Agardando confirmación",
  keys_confirm_btn: "Confirmar",
  keys_docs_title: "Documentación a entregar",
  keys_doc1: "Copia das escrituras asinadas",
  keys_doc2: "Certificado enerxético (CEE)",
  keys_doc3: "Manual de uso da vivenda",
  keys_doc4: "Chaves de todas as pechaduras",
  keys_doc5: "Tarxeta de garantía de electrodomésticos",
  keys_doc6: "Datos da comunidade e administrador",
  keys_tips_title: "Consellos para a entrega",
  keys_tip1: "Revisa o estado da vivenda antes de asinar a entrega",
  keys_tip2: "Anota as lecturas dos contadores de auga, luz e gas",
  keys_tip3: "Solicita o certificado de estar ao corrente de pagamentos na comunidade",
  keys_tip4: "Cambia o cilindro da pechadura por seguridade"
}
};

const map={
'es-ES':'es','en-US':'en','en-GB':'en','en-CA':'en',
'fr-FR':'fr','fr-CA':'fr','ca-ES':'ca','eu-ES':'eu','gl-ES':'gl'
};

Object.entries(map).forEach(([locale,lang])=>{
  const file=path.join(dir,locale+'.json');
  const json=JSON.parse(fs.readFileSync(file,'utf8'));
  Object.assign(json.transaction, t[lang]);
  fs.writeFileSync(file,JSON.stringify(json,null,2)+'\n','utf8');
  console.log(`${locale}: +${Object.keys(t[lang]).length} keys`);
});
